# 
# Copyright 2024 Ross Video Ltd
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
# 
# 3. Neither the name of the copyright holder nor the names of its
# contributors may be used to endorse or promote products derived from this
# software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# RE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#

#
# This Docker compose file demonstrates the following:
# 1. Set up public and private docker networks.
# 2. How to set up an envoy proxy container.
# 3. How to set up multiple service containers under the private network.
#

version: '3.8'  # Docker Compose file format version

networks:
  catena_network: # Public network for client to communicate with gateway.
    name: catena_network
    driver: bridge
  catena_prv: # Private network for gateway to communicate with services.
    name: catena_prv
    driver: bridge
    internal: true

# Setting up the envoyproxy container.
services:
  envoy_API_gateway:
    image: catena_envoy
    container_name: envoy_API_gateway
    networks: # Must be a part of both pub and prv networks.
      - catena_network
      - catena_prv
    environment:
      - AUTHZ_SERVER=$AUTHZ_SERVER
      - REALM=$REALM
    ports: # Mapping ports from host to container.
      - 6254:6254
      - 6256:6256
      - 6258:6258
      - 6260:6260
    volumes: # letsencrypt contains keys for TLS.
      - /etc/letsencrypt:/etc/letsencrypt:ro
    # Entrypoint defined in catena_envoy_dockerfile.
    
  # Example service container.
  status_update:
    image: catena_status_update
    container_name: catena_status_update
    networks:
      - catena_prv # Only connected to the prv network.
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command:
      - "--authz" # Starting service with authorization enabled.

  use_menus:
    image: catena_use_menus
    container_name: catena_use_menus
    networks:
      - catena_prv
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command:
      - "--authz"

  use_structs:
    image: catena_structs_with_authz
    container_name: catena_structs_with_authz
    networks:
      - catena_prv
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command:
      - "--authz"

  use_commands:
    image: catena_use_commands
    container_name: catena_use_commands
    networks:
      - catena_prv
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command:
      - "--authz"

