version: '3.8'  # Docker Compose file format version

networks:
  catena_network: # Public network for client to communicate with gateway.
    name: catena_network
    driver: bridge
  catena_prv: # Private network for gateway to communicate with services.
    name: catena_prv
    driver: bridge
    internal: true

# Setting up the envoyproxy container.
services:
  envoy_API_gateway:
    image: envoyproxy/envoy:v1.33-latest
    container_name: envoy_API_gateway
    networks: # Must be a part of both pub and prv networks.
      - catena_network
      - catena_prv
    ports: # Mapping ports from host to container.
      - 6254:6254
      - 6256:6256
      - 6258:6258
      - 6260:6260
    volumes: # letsencrypt contains keys for TLS.
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    command:
      - envoy
      - -c
      - /etc/envoy/envoy.yaml
      - --log-level
      - info

  # Example service container.
  status_update:
    image: catena_status_update
    container_name: catena_status_update
    networks:
      - catena_prv # Only connected to the prv network.
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command:
      - "--authz" # Starting service with authorization enabled.

  use_menus:
    image: catena_use_menus
    container_name: catena_use_menus
    networks:
      - catena_prv
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command:
      - "--authz"

  use_structs:
    image: catena_structs_with_authz
    container_name: catena_structs_with_authz
    networks:
      - catena_prv
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command:
      - "--authz"

  use_commands:
    image: catena_use_commands
    container_name: catena_use_commands
    networks:
      - catena_prv
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command:
      - "--authz"

