CATENA_CPP_SDK-v0.0.1: catena::ParamAccessor Class Reference
catena::ParamAccessor Class Reference
Public Types
using Mutex = DeviceModel::Mutex
Mutexlock type.
using Setter = catena::patterns::Functory< catena::Value::KindCase, void, catena::Value *, const void * >
type alias for the setter Functory for scalar types
using Getter = catena::patterns::Functory< catena::Value::KindCase, void, void *, const catena::Value * >
type alias for the getter function for scalar types
using SetterAt = catena::patterns::Functory< catena::Value::KindCase, void, catena::Value *, const void *, const ParamIndex >
type alias for the setter Functory for vector types
using GetterAt = catena::patterns::Functory< catena::Value::KindCase, void, void *, const catena::Value *, const ParamIndex >
type alias for the getter function for vector types
using VariantInfoGetter = catena::patterns::Functory< std::type_index, const VariantInfo & >
type alias for the function that gets the VariantInfo for a type
using ValueGetter = catena::patterns::Functory< catena::Value::KindCase, void, Value *, const Value &, ParamIndex >
type alias for the function that gets values from the device model for delivery to attached clients
using ValueSetter = catena::patterns::Functory< catena::Value::KindCase, void, Value &, const Value &, ParamIndex >
type alias for the function that sets values in the device model in response to client requests
Public Member Functions
ParamAccessor (DeviceModel &dm, DeviceModel::ParamAccessorData &pad, const std::string &oid)
Construct a new ParamAccessor object.
ParamAccessor ()=delete
ParamAccessor has no default constructor.
ParamAccessor (const ParamAccessor &other)=default
ParamAccessor copy constructor.
ParamAccessor & operator= (const ParamAccessor &rhs)=default
ParamAccessor copy assignment.
ParamAccessor (ParamAccessor &&other)=default
ParamAccessor move constructor.
ParamAccessor & operator= (ParamAccessor &&rhs)=default
ParamAccessor move assignment.
template<bool Threadsafe = true>
const Value & value () const
get accessor to the value of the parameter
template<bool Threadsafe>
std::unique_ptr< ParamAccessor > subParam (const std::string &fieldName)
get accessor to sub-parameter matching fieldName
template<bool Threadsafe>
const std::unique_ptr< ParamAccessor > subParam (const std::string &fieldName) const
get accessor to sub-parameter matching fieldName, const version
template<bool Threadsafe = true, typename V >
void setValue (const V &src)
Set the value of the stored parameter to which this object provides access.
template<bool Threadsafe = true, typename V >
void setValueAt (const V &src, const ParamIndex idx)
Set the value of the stored parameter to which this object provides access.
template<bool Threadsafe = true, typename V >
void getValue (V &dst) const
Get the value of the stored parameter to which objects of this class provide access.
template<bool Threadsafe = true, typename V >
void getValueAt (V &dst, const ParamIndex idx) const
Get the value of the stored parameter to which this object provides access from an array with the specified index.
template<bool Threadsafe = true>
void getValue (Value *dst, [[maybe_unused]] ParamIndex idx) const
get the parameter's value packaged as a catena::Value object for sending to a client.
void setValue (const std::string &peer, const Value &src, [[maybe_unused]] ParamIndex idx)
set the parameter's value packaged as a catena::Value object most likely received from client
const std::string & oid () const
get the parameter's fully qualified object id
size_t id () const
get the parameter's unique id
bool operator== (const ParamAccessor &rhs) const
comparison operator, returns true if the 2 ids are equal
bool isList () const
returns true if the param is an array (list in protobuf) type.
Constructor & Destructor Documentation
ParamAccessor() [1/3]
catena::ParamAccessor::ParamAccessor (DeviceModel & dm, DeviceModel::ParamAccessorData & pad, const std::string & oid)
Construct a new ParamAccessor object.
Parameters
dm the parent device model.
pad the data to initialize the param accessor
ParamAccessor() [2/3]
catena::ParamAccessor::ParamAccessor (const ParamAccessor & other) default
ParamAccessor copy constructor.
Parameters
other
ParamAccessor() [3/3]
catena::ParamAccessor::ParamAccessor (ParamAccessor && other) default
ParamAccessor move constructor.
Parameters
other
Member Function Documentation
getValue() [1/2]
template<bool Threadsafe = true, typename V > void catena::ParamAccessor::getValue (V & dst) const inline
Get the value of the stored parameter to which objects of this class provide access.
Exceptions
catena::exception_with_status catena::Status::UNIMPLEMENTED if support for V is not implemented, or with catena::Status::UNKNOWN if an unknown exception is thrown is encountered. Other catena::exception_with_status exceptions are re-thrown with no change to their status.
Template Parameters
V type of the value stored by the param. This must be a native type.
Parameters
dst reference to the destination object written to by this method.
References BAD_STATUS, catena::patterns::Singleton< Functory< K, R, Ms... > >::getInstance(), and catena::VariantInfo::members.
getValue() [2/2]
template<bool Threadsafe = true> void catena::ParamAccessor::getValue (Value * dst, [[maybe_unused] ] ParamIndex idx) const inline
get the parameter's value packaged as a catena::Value object for sending to a client.
Parameters
dst [out] destination for the value
idx [in] index into the array, if set to kParamEnd, the entire array is returned
Exceptions
catena::exception_with_status catena::Status::UNIMPLEMENTED if support for the parameter type is not implemented, or with catena::Status::UNKNOWN if an unknown exception is encountered, or with catena::Status::RANGE_ERROR if the index is out of range.
Template Parameters
Threadsafe if true, the method will assert the DeviceModel's mutex. If false, no lock is asserted - use when making recursive calls to avoid deadlock.
References isList(), and value().
getValueAt()
template<bool Threadsafe = true, typename V > void catena::ParamAccessor::getValueAt (V & dst, const ParamIndex idx) const inline
Get the value of the stored parameter to which this object provides access from an array with the specified index.
Exceptions
catena::exception_with_status catena::Status::UNIMPLEMENTED if support for objects of type V is not supported, or with catena::Status::UNKNOWN if an unknown exception is encountered, or catena::Status::RANGE_ERROR if the index is out of range.
Template Parameters
V type of the value stored by the param. This must be a native type.
Parameters
dst reference to the destination object written to by this method.
idx index into the array
References catena::patterns::Singleton< Functory< K, R, Ms... > >::getInstance(), and catena::getKindCase().
operator=() [1/2]
ParamAccessor& catena::ParamAccessor::operator= (const ParamAccessor & rhs) default
ParamAccessor copy assignment.
Parameters
rhs
operator=() [2/2]
ParamAccessor& catena::ParamAccessor::operator= (ParamAccessor && rhs) default
ParamAccessor move assignment.
Parameters
rhs,right hand side of the equals sign
setValue() [1/2]
void catena::ParamAccessor::setValue (const std::string & peer, const Value & src, [[maybe_unused] ] ParamIndex idx)
set the parameter's value packaged as a catena::Value object most likely received from client
Parameters
dst [out] destination for the value
idx [in] index into the array, if set to kParamEnd, the entire array is returned
Exceptions
catena::exception_with_status catena::Status::UNIMPLEMENTED if support for the parameter type is not implemented, or with catena::Status::UNKNOWN if an unknown exception is encountered, or with catena::Status::RANGE_ERROR if the index is out of range.
Threadsafe - asserts a lock on the DeviceModel's mutex.
setValue() [2/2]
template<bool Threadsafe = true, typename V > void catena::ParamAccessor::setValue (const V & src) inline
Set the value of the stored parameter to which this object provides access.
Exceptions
catena::exception_with_status catena::Status::UNIMPLEMENTED if support for V is not implemented, or with catena::Status::UNKNOWN if an unknown exception is thrown is encountered. Other catena::exception_with_status exceptions are re-thrown with no change to their status.
Template Parameters
V type of the value stored by the param. This must be a native type.
References catena::patterns::Singleton< Functory< K, R, Ms... > >::getInstance(), catena::getKindCase(), catena::VariantInfo::lookup, and catena::VariantInfo::members.
setValueAt()
template<bool Threadsafe = true, typename V > void catena::ParamAccessor::setValueAt (const V & src, const ParamIndex idx) inline
Set the value of the stored parameter to which this object provides access.
Exceptions
catena::exception_with_status catena::Status::UNIMPLEMENTED if support for V is not implemented, or with catena::Status::UNKNOWN if an unknown exception is thrown is encountered. Other catena::exception_with_status exceptions are re-thrown with no change to their status.
Template Parameters
V type of the value stored by the param. This must be a native type.
Threadsafe if true, the method will assert the DeviceModel's mutex.
Parameters
src the value to set the parameter owned by the ParamAccessor to.
idx index into the array, if set to kParamEnd, the value is appended to the array
References catena::patterns::Singleton< Functory< K, R, Ms... > >::getInstance(), and catena::getKindCase().
subParam() [1/2]
template<bool Threadsafe> std::unique_ptr<ParamAccessor> catena::ParamAccessor::subParam (const std::string & fieldName) inline
get accessor to sub-parameter matching fieldName
Parameters
fieldName name of the sub-parameter
Returns
unique_ptr to ParamAccessor interface
Exceptions
catena::exception_with_status if fieldName is not a sub-parameter
catena::exception_with_status if fieldName is not a struct or variant type
Note that the value element of the returned sub-param references the appropriate part of the parent's value element. This is because the value element in the child param descriptor is not part of the active value of the larger object. If even present, it's used as the default value for the matching part of the parent's value object.
This method is threadsafe because it asserts the DeviceModel's mutex.
References BAD_STATUS, and value().
subParam() [2/2]
template<bool Threadsafe> const std::unique_ptr<ParamAccessor> catena::ParamAccessor::subParam (const std::string & fieldName) const inline
get accessor to sub-parameter matching fieldName, const version
Parameters
fieldName name of the sub-parameter
Returns
unique_ptr to ParamAccessor interface
Exceptions
catena::exception_with_status if fieldName is not a sub-parameter
catena::exception_with_status if fieldName is not a struct or variant type
Note that the value element of the returned sub-param references the appropriate part of the parent's value element. This is because the value element in the child param descriptor is not part of the active value of the larger object. If even present, it's used as the default value for the matching part of the parent's value object.
This method is threadsafe because it asserts the DeviceModel's mutex.
References BAD_STATUS, and value().
The documentation for this class was generated from the following file:
/home/runner/work/Catena/Catena/sdks/cpp/common/include/ParamAccessor.h