services:
  catena-toolchain-cpp: # did you set you access token for pushing to ghcr?
  # echo "YOUR_TOKEN" | docker login ghcr.io -u YOUR_USERNAME --password-stdin
    build:
      context: .
      dockerfile: toolchain-cpp.dockerfile
    image: ghcr.io/rossvideo/catena-toolchain-cpp:latest
    env_file: toolchain-cpp.env

