services:
  catena-sdk:
    build:
      context: .
      dockerfile: dockerfile
    image: catena-sdk:latest
    volumes:
      - ../:/home/catena/Catena
    environment:
      - GIT_AUTHOR_NAME=${GIT_AUTHOR_NAME:-$(git config --get user.name)}
      - GIT_AUTHOR_EMAIL=${GIT_AUTHOR_EMAIL:-$(git config --get user.email)}
    command: /bin/bash -c "git config --global user.name \"$$GIT_AUTHOR_NAME\" && git config --global user.email \"$$GIT_AUTHOR_EMAIL\" && /bin/bash"
    # ports:
    #   - 50051:50051
    #   - 433:433
    #   - 80:80
    #   - 6254:6254