//
// Copyright (c) by the Society of Motion Picture and Television Engineers
//
// Redistribution and use in source and binary forms, with or without modification,
// are permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice, this
// list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice,
// this list of conditions and the following disclaimer in the documentation and/or
// other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its contributors
// may be used to endorse or promote products derived from this software without
// specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
// ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
// ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: constraint.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The severity of an Alarm.
type Alarm_Severity int32

const (
	Alarm_INFO    Alarm_Severity = 0
	Alarm_WARNING Alarm_Severity = 1
	Alarm_SEVERE  Alarm_Severity = 2
	Alarm_UNKNOWN Alarm_Severity = 3
	Alarm_REFUSED Alarm_Severity = 4
)

// Enum value maps for Alarm_Severity.
var (
	Alarm_Severity_name = map[int32]string{
		0: "INFO",
		1: "WARNING",
		2: "SEVERE",
		3: "UNKNOWN",
		4: "REFUSED",
	}
	Alarm_Severity_value = map[string]int32{
		"INFO":    0,
		"WARNING": 1,
		"SEVERE":  2,
		"UNKNOWN": 3,
		"REFUSED": 4,
	}
)

func (x Alarm_Severity) Enum() *Alarm_Severity {
	p := new(Alarm_Severity)
	*p = x
	return p
}

func (x Alarm_Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Alarm_Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_constraint_proto_enumTypes[0].Descriptor()
}

func (Alarm_Severity) Type() protoreflect.EnumType {
	return &file_constraint_proto_enumTypes[0]
}

func (x Alarm_Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Alarm_Severity.Descriptor instead.
func (Alarm_Severity) EnumDescriptor() ([]byte, []int) {
	return file_constraint_proto_rawDescGZIP(), []int{0, 0}
}

type Constraint_ConstraintType int32

const (
	Constraint_UNDEFINED            Constraint_ConstraintType = 0
	Constraint_INT_RANGE            Constraint_ConstraintType = 2
	Constraint_FLOAT_RANGE          Constraint_ConstraintType = 4
	Constraint_INT_CHOICE           Constraint_ConstraintType = 5
	Constraint_STRING_CHOICE        Constraint_ConstraintType = 6
	Constraint_STRING_STRING_CHOICE Constraint_ConstraintType = 7
	Constraint_ALARM_TABLE          Constraint_ConstraintType = 8
)

// Enum value maps for Constraint_ConstraintType.
var (
	Constraint_ConstraintType_name = map[int32]string{
		0: "UNDEFINED",
		2: "INT_RANGE",
		4: "FLOAT_RANGE",
		5: "INT_CHOICE",
		6: "STRING_CHOICE",
		7: "STRING_STRING_CHOICE",
		8: "ALARM_TABLE",
	}
	Constraint_ConstraintType_value = map[string]int32{
		"UNDEFINED":            0,
		"INT_RANGE":            2,
		"FLOAT_RANGE":          4,
		"INT_CHOICE":           5,
		"STRING_CHOICE":        6,
		"STRING_STRING_CHOICE": 7,
		"ALARM_TABLE":          8,
	}
)

func (x Constraint_ConstraintType) Enum() *Constraint_ConstraintType {
	p := new(Constraint_ConstraintType)
	*p = x
	return p
}

func (x Constraint_ConstraintType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Constraint_ConstraintType) Descriptor() protoreflect.EnumDescriptor {
	return file_constraint_proto_enumTypes[1].Descriptor()
}

func (Constraint_ConstraintType) Type() protoreflect.EnumType {
	return &file_constraint_proto_enumTypes[1]
}

func (x Constraint_ConstraintType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Constraint_ConstraintType.Descriptor instead.
func (Constraint_ConstraintType) EnumDescriptor() ([]byte, []int) {
	return file_constraint_proto_rawDescGZIP(), []int{7, 0}
}

type Alarm struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	BitValue int32                  `protobuf:"varint,1,opt,name=bit_value,json=bitValue,proto3" json:"bit_value,omitempty"` // range 0 to 31
	Severity Alarm_Severity         `protobuf:"varint,2,opt,name=severity,proto3,enum=st2138.Alarm_Severity" json:"severity,omitempty"`
	// Message to display in client GUI
	Description   *PolyglotText `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alarm) Reset() {
	*x = Alarm{}
	mi := &file_constraint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alarm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alarm) ProtoMessage() {}

func (x *Alarm) ProtoReflect() protoreflect.Message {
	mi := &file_constraint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alarm.ProtoReflect.Descriptor instead.
func (*Alarm) Descriptor() ([]byte, []int) {
	return file_constraint_proto_rawDescGZIP(), []int{0}
}

func (x *Alarm) GetBitValue() int32 {
	if x != nil {
		return x.BitValue
	}
	return 0
}

func (x *Alarm) GetSeverity() Alarm_Severity {
	if x != nil {
		return x.Severity
	}
	return Alarm_INFO
}

func (x *Alarm) GetDescription() *PolyglotText {
	if x != nil {
		return x.Description
	}
	return nil
}

// Alarm Table. Comprises a number of different Alarms.
type AlarmTableConstraint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alarms        []*Alarm               `protobuf:"bytes,1,rep,name=alarms,proto3" json:"alarms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlarmTableConstraint) Reset() {
	*x = AlarmTableConstraint{}
	mi := &file_constraint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlarmTableConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmTableConstraint) ProtoMessage() {}

func (x *AlarmTableConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_constraint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarmTableConstraint.ProtoReflect.Descriptor instead.
func (*AlarmTableConstraint) Descriptor() ([]byte, []int) {
	return file_constraint_proto_rawDescGZIP(), []int{1}
}

func (x *AlarmTableConstraint) GetAlarms() []*Alarm {
	if x != nil {
		return x.Alarms
	}
	return nil
}

// Codes integers for display in client GUI as values or members of a pick list.
type Int32ChoiceConstraint struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Choices       []*Int32ChoiceConstraint_IntChoice `protobuf:"bytes,1,rep,name=choices,proto3" json:"choices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Int32ChoiceConstraint) Reset() {
	*x = Int32ChoiceConstraint{}
	mi := &file_constraint_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int32ChoiceConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int32ChoiceConstraint) ProtoMessage() {}

func (x *Int32ChoiceConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_constraint_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int32ChoiceConstraint.ProtoReflect.Descriptor instead.
func (*Int32ChoiceConstraint) Descriptor() ([]byte, []int) {
	return file_constraint_proto_rawDescGZIP(), []int{2}
}

func (x *Int32ChoiceConstraint) GetChoices() []*Int32ChoiceConstraint_IntChoice {
	if x != nil {
		return x.Choices
	}
	return nil
}

// Range constraint including hard min & max values plus display min & max.
type Int32RangeConstraint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinValue      int32                  `protobuf:"varint,1,opt,name=min_value,json=minValue,proto3" json:"min_value,omitempty"`
	MaxValue      int32                  `protobuf:"varint,2,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`
	Step          int32                  `protobuf:"varint,3,opt,name=step,proto3" json:"step,omitempty"`
	DisplayMin    int32                  `protobuf:"varint,4,opt,name=display_min,json=displayMin,proto3" json:"display_min,omitempty"`
	DisplayMax    int32                  `protobuf:"varint,5,opt,name=display_max,json=displayMax,proto3" json:"display_max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Int32RangeConstraint) Reset() {
	*x = Int32RangeConstraint{}
	mi := &file_constraint_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int32RangeConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int32RangeConstraint) ProtoMessage() {}

func (x *Int32RangeConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_constraint_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int32RangeConstraint.ProtoReflect.Descriptor instead.
func (*Int32RangeConstraint) Descriptor() ([]byte, []int) {
	return file_constraint_proto_rawDescGZIP(), []int{3}
}

func (x *Int32RangeConstraint) GetMinValue() int32 {
	if x != nil {
		return x.MinValue
	}
	return 0
}

func (x *Int32RangeConstraint) GetMaxValue() int32 {
	if x != nil {
		return x.MaxValue
	}
	return 0
}

func (x *Int32RangeConstraint) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *Int32RangeConstraint) GetDisplayMin() int32 {
	if x != nil {
		return x.DisplayMin
	}
	return 0
}

func (x *Int32RangeConstraint) GetDisplayMax() int32 {
	if x != nil {
		return x.DisplayMax
	}
	return 0
}

// Range constraint with hard min & max plus display min & max.
type FloatRangeConstraint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinValue      float32                `protobuf:"fixed32,1,opt,name=min_value,json=minValue,proto3" json:"min_value,omitempty"`
	MaxValue      float32                `protobuf:"fixed32,2,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`
	Step          float32                `protobuf:"fixed32,3,opt,name=step,proto3" json:"step,omitempty"`
	DisplayMin    float32                `protobuf:"fixed32,4,opt,name=display_min,json=displayMin,proto3" json:"display_min,omitempty"`
	DisplayMax    float32                `protobuf:"fixed32,5,opt,name=display_max,json=displayMax,proto3" json:"display_max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FloatRangeConstraint) Reset() {
	*x = FloatRangeConstraint{}
	mi := &file_constraint_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloatRangeConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatRangeConstraint) ProtoMessage() {}

func (x *FloatRangeConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_constraint_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatRangeConstraint.ProtoReflect.Descriptor instead.
func (*FloatRangeConstraint) Descriptor() ([]byte, []int) {
	return file_constraint_proto_rawDescGZIP(), []int{4}
}

func (x *FloatRangeConstraint) GetMinValue() float32 {
	if x != nil {
		return x.MinValue
	}
	return 0
}

func (x *FloatRangeConstraint) GetMaxValue() float32 {
	if x != nil {
		return x.MaxValue
	}
	return 0
}

func (x *FloatRangeConstraint) GetStep() float32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *FloatRangeConstraint) GetDisplayMin() float32 {
	if x != nil {
		return x.DisplayMin
	}
	return 0
}

func (x *FloatRangeConstraint) GetDisplayMax() float32 {
	if x != nil {
		return x.DisplayMax
	}
	return 0
}

// A selection of strings for client GUI to use in pick list and other GUI elements.
type StringChoiceConstraint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Choices       []string               `protobuf:"bytes,1,rep,name=choices,proto3" json:"choices,omitempty"`
	Strict        bool                   `protobuf:"varint,2,opt,name=strict,proto3" json:"strict,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringChoiceConstraint) Reset() {
	*x = StringChoiceConstraint{}
	mi := &file_constraint_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringChoiceConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringChoiceConstraint) ProtoMessage() {}

func (x *StringChoiceConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_constraint_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringChoiceConstraint.ProtoReflect.Descriptor instead.
func (*StringChoiceConstraint) Descriptor() ([]byte, []int) {
	return file_constraint_proto_rawDescGZIP(), []int{5}
}

func (x *StringChoiceConstraint) GetChoices() []string {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *StringChoiceConstraint) GetStrict() bool {
	if x != nil {
		return x.Strict
	}
	return false
}

// A selection of human-friendly strings to display in client GUI that are
// used to select a string intended for machine use.
type StringStringChoiceConstraint struct {
	state         protoimpl.MessageState                             `protogen:"open.v1"`
	Choices       []*StringStringChoiceConstraint_StringStringChoice `protobuf:"bytes,1,rep,name=choices,proto3" json:"choices,omitempty"`
	Strict        bool                                               `protobuf:"varint,2,opt,name=strict,proto3" json:"strict,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringStringChoiceConstraint) Reset() {
	*x = StringStringChoiceConstraint{}
	mi := &file_constraint_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringStringChoiceConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringStringChoiceConstraint) ProtoMessage() {}

func (x *StringStringChoiceConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_constraint_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringStringChoiceConstraint.ProtoReflect.Descriptor instead.
func (*StringStringChoiceConstraint) Descriptor() ([]byte, []int) {
	return file_constraint_proto_rawDescGZIP(), []int{6}
}

func (x *StringStringChoiceConstraint) GetChoices() []*StringStringChoiceConstraint_StringStringChoice {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *StringStringChoiceConstraint) GetStrict() bool {
	if x != nil {
		return x.Strict
	}
	return false
}

type Constraint struct {
	state protoimpl.MessageState    `protogen:"open.v1"`
	Type  Constraint_ConstraintType `protobuf:"varint,1,opt,name=type,proto3,enum=st2138.Constraint_ConstraintType" json:"type,omitempty"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Constraint_RefOid
	//	*Constraint_AlarmTable
	//	*Constraint_Int32Range
	//	*Constraint_Int32Choice
	//	*Constraint_FloatRange
	//	*Constraint_StringChoice
	//	*Constraint_StringStringChoice
	Kind          isConstraint_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Constraint) Reset() {
	*x = Constraint{}
	mi := &file_constraint_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Constraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Constraint) ProtoMessage() {}

func (x *Constraint) ProtoReflect() protoreflect.Message {
	mi := &file_constraint_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Constraint.ProtoReflect.Descriptor instead.
func (*Constraint) Descriptor() ([]byte, []int) {
	return file_constraint_proto_rawDescGZIP(), []int{7}
}

func (x *Constraint) GetType() Constraint_ConstraintType {
	if x != nil {
		return x.Type
	}
	return Constraint_UNDEFINED
}

func (x *Constraint) GetKind() isConstraint_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Constraint) GetRefOid() string {
	if x != nil {
		if x, ok := x.Kind.(*Constraint_RefOid); ok {
			return x.RefOid
		}
	}
	return ""
}

func (x *Constraint) GetAlarmTable() *AlarmTableConstraint {
	if x != nil {
		if x, ok := x.Kind.(*Constraint_AlarmTable); ok {
			return x.AlarmTable
		}
	}
	return nil
}

func (x *Constraint) GetInt32Range() *Int32RangeConstraint {
	if x != nil {
		if x, ok := x.Kind.(*Constraint_Int32Range); ok {
			return x.Int32Range
		}
	}
	return nil
}

func (x *Constraint) GetInt32Choice() *Int32ChoiceConstraint {
	if x != nil {
		if x, ok := x.Kind.(*Constraint_Int32Choice); ok {
			return x.Int32Choice
		}
	}
	return nil
}

func (x *Constraint) GetFloatRange() *FloatRangeConstraint {
	if x != nil {
		if x, ok := x.Kind.(*Constraint_FloatRange); ok {
			return x.FloatRange
		}
	}
	return nil
}

func (x *Constraint) GetStringChoice() *StringChoiceConstraint {
	if x != nil {
		if x, ok := x.Kind.(*Constraint_StringChoice); ok {
			return x.StringChoice
		}
	}
	return nil
}

func (x *Constraint) GetStringStringChoice() *StringStringChoiceConstraint {
	if x != nil {
		if x, ok := x.Kind.(*Constraint_StringStringChoice); ok {
			return x.StringStringChoice
		}
	}
	return nil
}

type isConstraint_Kind interface {
	isConstraint_Kind()
}

type Constraint_RefOid struct {
	// A reference to a shared constraint defined in device.constraints
	RefOid string `protobuf:"bytes,2,opt,name=ref_oid,json=refOid,proto3,oneof"`
}

type Constraint_AlarmTable struct {
	// Int32 Constraints
	AlarmTable *AlarmTableConstraint `protobuf:"bytes,3,opt,name=alarm_table,json=alarmTable,proto3,oneof"`
}

type Constraint_Int32Range struct {
	Int32Range *Int32RangeConstraint `protobuf:"bytes,4,opt,name=int32_range,json=int32Range,proto3,oneof"`
}

type Constraint_Int32Choice struct {
	Int32Choice *Int32ChoiceConstraint `protobuf:"bytes,5,opt,name=int32_choice,json=int32Choice,proto3,oneof"`
}

type Constraint_FloatRange struct {
	// Float Constraints
	FloatRange *FloatRangeConstraint `protobuf:"bytes,6,opt,name=float_range,json=floatRange,proto3,oneof"`
}

type Constraint_StringChoice struct {
	// String Constraints
	StringChoice *StringChoiceConstraint `protobuf:"bytes,7,opt,name=string_choice,json=stringChoice,proto3,oneof"`
}

type Constraint_StringStringChoice struct {
	StringStringChoice *StringStringChoiceConstraint `protobuf:"bytes,8,opt,name=string_string_choice,json=stringStringChoice,proto3,oneof"`
}

func (*Constraint_RefOid) isConstraint_Kind() {}

func (*Constraint_AlarmTable) isConstraint_Kind() {}

func (*Constraint_Int32Range) isConstraint_Kind() {}

func (*Constraint_Int32Choice) isConstraint_Kind() {}

func (*Constraint_FloatRange) isConstraint_Kind() {}

func (*Constraint_StringChoice) isConstraint_Kind() {}

func (*Constraint_StringStringChoice) isConstraint_Kind() {}

type Int32ChoiceConstraint_IntChoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Name          *PolyglotText          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Int32ChoiceConstraint_IntChoice) Reset() {
	*x = Int32ChoiceConstraint_IntChoice{}
	mi := &file_constraint_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int32ChoiceConstraint_IntChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int32ChoiceConstraint_IntChoice) ProtoMessage() {}

func (x *Int32ChoiceConstraint_IntChoice) ProtoReflect() protoreflect.Message {
	mi := &file_constraint_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int32ChoiceConstraint_IntChoice.ProtoReflect.Descriptor instead.
func (*Int32ChoiceConstraint_IntChoice) Descriptor() ([]byte, []int) {
	return file_constraint_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Int32ChoiceConstraint_IntChoice) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Int32ChoiceConstraint_IntChoice) GetName() *PolyglotText {
	if x != nil {
		return x.Name
	}
	return nil
}

type StringStringChoiceConstraint_StringStringChoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Name          *PolyglotText          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringStringChoiceConstraint_StringStringChoice) Reset() {
	*x = StringStringChoiceConstraint_StringStringChoice{}
	mi := &file_constraint_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringStringChoiceConstraint_StringStringChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringStringChoiceConstraint_StringStringChoice) ProtoMessage() {}

func (x *StringStringChoiceConstraint_StringStringChoice) ProtoReflect() protoreflect.Message {
	mi := &file_constraint_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringStringChoiceConstraint_StringStringChoice.ProtoReflect.Descriptor instead.
func (*StringStringChoiceConstraint_StringStringChoice) Descriptor() ([]byte, []int) {
	return file_constraint_proto_rawDescGZIP(), []int{6, 0}
}

func (x *StringStringChoiceConstraint_StringStringChoice) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *StringStringChoiceConstraint_StringStringChoice) GetName() *PolyglotText {
	if x != nil {
		return x.Name
	}
	return nil
}

var File_constraint_proto protoreflect.FileDescriptor

const file_constraint_proto_rawDesc = "" +
	"\n" +
	"\x10constraint.proto\x12\x06st2138\x1a\x0elanguage.proto\"\xd9\x01\n" +
	"\x05Alarm\x12\x1b\n" +
	"\tbit_value\x18\x01 \x01(\x05R\bbitValue\x122\n" +
	"\bseverity\x18\x02 \x01(\x0e2\x16.st2138.Alarm.SeverityR\bseverity\x126\n" +
	"\vdescription\x18\x03 \x01(\v2\x14.st2138.PolyglotTextR\vdescription\"G\n" +
	"\bSeverity\x12\b\n" +
	"\x04INFO\x10\x00\x12\v\n" +
	"\aWARNING\x10\x01\x12\n" +
	"\n" +
	"\x06SEVERE\x10\x02\x12\v\n" +
	"\aUNKNOWN\x10\x03\x12\v\n" +
	"\aREFUSED\x10\x04\"=\n" +
	"\x14AlarmTableConstraint\x12%\n" +
	"\x06alarms\x18\x01 \x03(\v2\r.st2138.AlarmR\x06alarms\"\xa7\x01\n" +
	"\x15Int32ChoiceConstraint\x12A\n" +
	"\achoices\x18\x01 \x03(\v2'.st2138.Int32ChoiceConstraint.IntChoiceR\achoices\x1aK\n" +
	"\tIntChoice\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\x12(\n" +
	"\x04name\x18\x02 \x01(\v2\x14.st2138.PolyglotTextR\x04name\"\xa6\x01\n" +
	"\x14Int32RangeConstraint\x12\x1b\n" +
	"\tmin_value\x18\x01 \x01(\x05R\bminValue\x12\x1b\n" +
	"\tmax_value\x18\x02 \x01(\x05R\bmaxValue\x12\x12\n" +
	"\x04step\x18\x03 \x01(\x05R\x04step\x12\x1f\n" +
	"\vdisplay_min\x18\x04 \x01(\x05R\n" +
	"displayMin\x12\x1f\n" +
	"\vdisplay_max\x18\x05 \x01(\x05R\n" +
	"displayMax\"\xa6\x01\n" +
	"\x14FloatRangeConstraint\x12\x1b\n" +
	"\tmin_value\x18\x01 \x01(\x02R\bminValue\x12\x1b\n" +
	"\tmax_value\x18\x02 \x01(\x02R\bmaxValue\x12\x12\n" +
	"\x04step\x18\x03 \x01(\x02R\x04step\x12\x1f\n" +
	"\vdisplay_min\x18\x04 \x01(\x02R\n" +
	"displayMin\x12\x1f\n" +
	"\vdisplay_max\x18\x05 \x01(\x02R\n" +
	"displayMax\"J\n" +
	"\x16StringChoiceConstraint\x12\x18\n" +
	"\achoices\x18\x01 \x03(\tR\achoices\x12\x16\n" +
	"\x06strict\x18\x02 \x01(\bR\x06strict\"\xdf\x01\n" +
	"\x1cStringStringChoiceConstraint\x12Q\n" +
	"\achoices\x18\x01 \x03(\v27.st2138.StringStringChoiceConstraint.StringStringChoiceR\achoices\x12\x16\n" +
	"\x06strict\x18\x02 \x01(\bR\x06strict\x1aT\n" +
	"\x12StringStringChoice\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12(\n" +
	"\x04name\x18\x02 \x01(\v2\x14.st2138.PolyglotTextR\x04name\"\x9e\x05\n" +
	"\n" +
	"Constraint\x125\n" +
	"\x04type\x18\x01 \x01(\x0e2!.st2138.Constraint.ConstraintTypeR\x04type\x12\x19\n" +
	"\aref_oid\x18\x02 \x01(\tH\x00R\x06refOid\x12?\n" +
	"\valarm_table\x18\x03 \x01(\v2\x1c.st2138.AlarmTableConstraintH\x00R\n" +
	"alarmTable\x12?\n" +
	"\vint32_range\x18\x04 \x01(\v2\x1c.st2138.Int32RangeConstraintH\x00R\n" +
	"int32Range\x12B\n" +
	"\fint32_choice\x18\x05 \x01(\v2\x1d.st2138.Int32ChoiceConstraintH\x00R\vint32Choice\x12?\n" +
	"\vfloat_range\x18\x06 \x01(\v2\x1c.st2138.FloatRangeConstraintH\x00R\n" +
	"floatRange\x12E\n" +
	"\rstring_choice\x18\a \x01(\v2\x1e.st2138.StringChoiceConstraintH\x00R\fstringChoice\x12X\n" +
	"\x14string_string_choice\x18\b \x01(\v2$.st2138.StringStringChoiceConstraintH\x00R\x12stringStringChoice\"\x8d\x01\n" +
	"\x0eConstraintType\x12\r\n" +
	"\tUNDEFINED\x10\x00\x12\r\n" +
	"\tINT_RANGE\x10\x02\x12\x0f\n" +
	"\vFLOAT_RANGE\x10\x04\x12\x0e\n" +
	"\n" +
	"INT_CHOICE\x10\x05\x12\x11\n" +
	"\rSTRING_CHOICE\x10\x06\x12\x18\n" +
	"\x14STRING_STRING_CHOICE\x10\a\x12\x0f\n" +
	"\vALARM_TABLE\x10\bB\x06\n" +
	"\x04kindB.\n" +
	"\x16catena.core.constraintB\x10ConstraintProtosH\x01P\x01b\x06proto3"

var (
	file_constraint_proto_rawDescOnce sync.Once
	file_constraint_proto_rawDescData []byte
)

func file_constraint_proto_rawDescGZIP() []byte {
	file_constraint_proto_rawDescOnce.Do(func() {
		file_constraint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_constraint_proto_rawDesc), len(file_constraint_proto_rawDesc)))
	})
	return file_constraint_proto_rawDescData
}

var file_constraint_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_constraint_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_constraint_proto_goTypes = []any{
	(Alarm_Severity)(0),                                     // 0: st2138.Alarm.Severity
	(Constraint_ConstraintType)(0),                          // 1: st2138.Constraint.ConstraintType
	(*Alarm)(nil),                                           // 2: st2138.Alarm
	(*AlarmTableConstraint)(nil),                            // 3: st2138.AlarmTableConstraint
	(*Int32ChoiceConstraint)(nil),                           // 4: st2138.Int32ChoiceConstraint
	(*Int32RangeConstraint)(nil),                            // 5: st2138.Int32RangeConstraint
	(*FloatRangeConstraint)(nil),                            // 6: st2138.FloatRangeConstraint
	(*StringChoiceConstraint)(nil),                          // 7: st2138.StringChoiceConstraint
	(*StringStringChoiceConstraint)(nil),                    // 8: st2138.StringStringChoiceConstraint
	(*Constraint)(nil),                                      // 9: st2138.Constraint
	(*Int32ChoiceConstraint_IntChoice)(nil),                 // 10: st2138.Int32ChoiceConstraint.IntChoice
	(*StringStringChoiceConstraint_StringStringChoice)(nil), // 11: st2138.StringStringChoiceConstraint.StringStringChoice
	(*PolyglotText)(nil),                                    // 12: st2138.PolyglotText
}
var file_constraint_proto_depIdxs = []int32{
	0,  // 0: st2138.Alarm.severity:type_name -> st2138.Alarm.Severity
	12, // 1: st2138.Alarm.description:type_name -> st2138.PolyglotText
	2,  // 2: st2138.AlarmTableConstraint.alarms:type_name -> st2138.Alarm
	10, // 3: st2138.Int32ChoiceConstraint.choices:type_name -> st2138.Int32ChoiceConstraint.IntChoice
	11, // 4: st2138.StringStringChoiceConstraint.choices:type_name -> st2138.StringStringChoiceConstraint.StringStringChoice
	1,  // 5: st2138.Constraint.type:type_name -> st2138.Constraint.ConstraintType
	3,  // 6: st2138.Constraint.alarm_table:type_name -> st2138.AlarmTableConstraint
	5,  // 7: st2138.Constraint.int32_range:type_name -> st2138.Int32RangeConstraint
	4,  // 8: st2138.Constraint.int32_choice:type_name -> st2138.Int32ChoiceConstraint
	6,  // 9: st2138.Constraint.float_range:type_name -> st2138.FloatRangeConstraint
	7,  // 10: st2138.Constraint.string_choice:type_name -> st2138.StringChoiceConstraint
	8,  // 11: st2138.Constraint.string_string_choice:type_name -> st2138.StringStringChoiceConstraint
	12, // 12: st2138.Int32ChoiceConstraint.IntChoice.name:type_name -> st2138.PolyglotText
	12, // 13: st2138.StringStringChoiceConstraint.StringStringChoice.name:type_name -> st2138.PolyglotText
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_constraint_proto_init() }
func file_constraint_proto_init() {
	if File_constraint_proto != nil {
		return
	}
	file_language_proto_init()
	file_constraint_proto_msgTypes[7].OneofWrappers = []any{
		(*Constraint_RefOid)(nil),
		(*Constraint_AlarmTable)(nil),
		(*Constraint_Int32Range)(nil),
		(*Constraint_Int32Choice)(nil),
		(*Constraint_FloatRange)(nil),
		(*Constraint_StringChoice)(nil),
		(*Constraint_StringStringChoice)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_constraint_proto_rawDesc), len(file_constraint_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_constraint_proto_goTypes,
		DependencyIndexes: file_constraint_proto_depIdxs,
		EnumInfos:         file_constraint_proto_enumTypes,
		MessageInfos:      file_constraint_proto_msgTypes,
	}.Build()
	File_constraint_proto = out.File
	file_constraint_proto_goTypes = nil
	file_constraint_proto_depIdxs = nil
}
