//
// Copyright (c) by the Society of Motion Picture and Television Engineers
//
// Redistribution and use in source and binary forms, with or without modification,
// are permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice, this
// list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice,
// this list of conditions and the following disclaimer in the documentation and/or
// other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its contributors
// may be used to endorse or promote products derived from this software without
// specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
// ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
// ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: device.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// How much of the device model to deliver.
type Device_DetailLevel int32

const (
	Device_FULL          Device_DetailLevel = 0
	Device_SUBSCRIPTIONS Device_DetailLevel = 1
	Device_MINIMAL       Device_DetailLevel = 2
	Device_COMMANDS      Device_DetailLevel = 3
	Device_NONE          Device_DetailLevel = 4
	Device_UNSET         Device_DetailLevel = 5
)

// Enum value maps for Device_DetailLevel.
var (
	Device_DetailLevel_name = map[int32]string{
		0: "FULL",
		1: "SUBSCRIPTIONS",
		2: "MINIMAL",
		3: "COMMANDS",
		4: "NONE",
		5: "UNSET",
	}
	Device_DetailLevel_value = map[string]int32{
		"FULL":          0,
		"SUBSCRIPTIONS": 1,
		"MINIMAL":       2,
		"COMMANDS":      3,
		"NONE":          4,
		"UNSET":         5,
	}
)

func (x Device_DetailLevel) Enum() *Device_DetailLevel {
	p := new(Device_DetailLevel)
	*p = x
	return p
}

func (x Device_DetailLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Device_DetailLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_device_proto_enumTypes[0].Descriptor()
}

func (Device_DetailLevel) Type() protoreflect.EnumType {
	return &file_device_proto_enumTypes[0]
}

func (x Device_DetailLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Device_DetailLevel.Descriptor instead.
func (Device_DetailLevel) EnumDescriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{0, 0}
}

type TrapMessage_TrapMessageType int32

const (
	TrapMessage_UNUSED                  TrapMessage_TrapMessageType = 0 // protobuf requires enums start at 0
	TrapMessage_RESTART                 TrapMessage_TrapMessageType = 1 // Indicates device has just restarted.No trap data
	TrapMessage_PARAM_CHANGED           TrapMessage_TrapMessageType = 2 // trap data is oid of the parameter that changed
	TrapMessage_MENU_CHANGED            TrapMessage_TrapMessageType = 3 // trap data is oid of the menu that changed
	TrapMessage_EXTERNAL_OBJECT_CHANGED TrapMessage_TrapMessageType = 4 // trap data is oid of the external object that changed
	TrapMessage_REVEAL_ELEMENT          TrapMessage_TrapMessageType = 5 // trap data is the id of the element to reveal
	TrapMessage_HIDE_ELEMENT            TrapMessage_TrapMessageType = 6 // trap data is the id of the element to hide
	TrapMessage_RELOAD_UI_ELEMENT       TrapMessage_TrapMessageType = 7 // trap data is the id of the element to reload
	TrapMessage_STRING_OID_CHANGED      TrapMessage_TrapMessageType = 8 // trap data is the oid of the string that changed
	TrapMessage_REBUILD_UI              TrapMessage_TrapMessageType = 9 // No trap data
)

// Enum value maps for TrapMessage_TrapMessageType.
var (
	TrapMessage_TrapMessageType_name = map[int32]string{
		0: "UNUSED",
		1: "RESTART",
		2: "PARAM_CHANGED",
		3: "MENU_CHANGED",
		4: "EXTERNAL_OBJECT_CHANGED",
		5: "REVEAL_ELEMENT",
		6: "HIDE_ELEMENT",
		7: "RELOAD_UI_ELEMENT",
		8: "STRING_OID_CHANGED",
		9: "REBUILD_UI",
	}
	TrapMessage_TrapMessageType_value = map[string]int32{
		"UNUSED":                  0,
		"RESTART":                 1,
		"PARAM_CHANGED":           2,
		"MENU_CHANGED":            3,
		"EXTERNAL_OBJECT_CHANGED": 4,
		"REVEAL_ELEMENT":          5,
		"HIDE_ELEMENT":            6,
		"RELOAD_UI_ELEMENT":       7,
		"STRING_OID_CHANGED":      8,
		"REBUILD_UI":              9,
	}
)

func (x TrapMessage_TrapMessageType) Enum() *TrapMessage_TrapMessageType {
	p := new(TrapMessage_TrapMessageType)
	*p = x
	return p
}

func (x TrapMessage_TrapMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrapMessage_TrapMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_device_proto_enumTypes[1].Descriptor()
}

func (TrapMessage_TrapMessageType) Type() protoreflect.EnumType {
	return &file_device_proto_enumTypes[1]
}

func (x TrapMessage_TrapMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrapMessage_TrapMessageType.Descriptor instead.
func (TrapMessage_TrapMessageType) EnumDescriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{5, 0}
}

// Device model for Catena compatible devices.
type Device struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID for the device, locally unique within the Catena connection.
	Slot        uint32             `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	DetailLevel Device_DetailLevel `protobuf:"varint,2,opt,name=detail_level,json=detailLevel,proto3,enum=st2138.Device_DetailLevel" json:"detail_level,omitempty"`
	// Whether multi-set message is supported
	MultiSetEnabled bool `protobuf:"varint,3,opt,name=multi_set_enabled,json=multiSetEnabled,proto3" json:"multi_set_enabled,omitempty"`
	// Whether subscriptions are supported
	Subscriptions bool `protobuf:"varint,4,opt,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	// The device's shared constraints. A map of Constraint, keyed by their object ids (OIDs).
	Constraints map[string]*Constraint `protobuf:"bytes,5,rep,name=constraints,proto3" json:"constraints,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The device's parameters. A map of Param, keyed by their object ids (OIDs).
	Params map[string]*Param `protobuf:"bytes,6,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The device's default editor UI definition and access scope definitions
	MenuGroups map[string]*MenuGroup `protobuf:"bytes,7,rep,name=menu_groups,json=menuGroups,proto3" json:"menu_groups,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The device's available commands, keyed by their object ids (OIDs).
	Commands map[string]*Param `protobuf:"bytes,8,rep,name=commands,proto3" json:"commands,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The devices language packs
	LanguagePacks *LanguagePacks `protobuf:"bytes,9,opt,name=language_packs,json=languagePacks,proto3" json:"language_packs,omitempty"`
	// The device's access scopes, a list of mutually unique strings
	AccessScopes []string `protobuf:"bytes,10,rep,name=access_scopes,json=accessScopes,proto3" json:"access_scopes,omitempty"`
	// The default scope, index into access_scopes to indicate which of them is the default.
	DefaultScope  string `protobuf:"bytes,11,opt,name=default_scope,json=defaultScope,proto3" json:"default_scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{0}
}

func (x *Device) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *Device) GetDetailLevel() Device_DetailLevel {
	if x != nil {
		return x.DetailLevel
	}
	return Device_FULL
}

func (x *Device) GetMultiSetEnabled() bool {
	if x != nil {
		return x.MultiSetEnabled
	}
	return false
}

func (x *Device) GetSubscriptions() bool {
	if x != nil {
		return x.Subscriptions
	}
	return false
}

func (x *Device) GetConstraints() map[string]*Constraint {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *Device) GetParams() map[string]*Param {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Device) GetMenuGroups() map[string]*MenuGroup {
	if x != nil {
		return x.MenuGroups
	}
	return nil
}

func (x *Device) GetCommands() map[string]*Param {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *Device) GetLanguagePacks() *LanguagePacks {
	if x != nil {
		return x.LanguagePacks
	}
	return nil
}

func (x *Device) GetAccessScopes() []string {
	if x != nil {
		return x.AccessScopes
	}
	return nil
}

func (x *Device) GetDefaultScope() string {
	if x != nil {
		return x.DefaultScope
	}
	return ""
}

// The Device model broken into smaller pieces.
// Design intent is to allow very large Device Models to be delivered
// to clients as a stream of DeviceComponents.
type DeviceComponent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Small device models can be sent as a whole.
	// Larger ones should be broken into a stream of smaller components.
	// Types that are valid to be assigned to Kind:
	//
	//	*DeviceComponent_Device
	//	*DeviceComponent_Param
	//	*DeviceComponent_SharedConstraint
	//	*DeviceComponent_Menu
	//	*DeviceComponent_Command
	//	*DeviceComponent_LanguagePack
	Kind          isDeviceComponent_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceComponent) Reset() {
	*x = DeviceComponent{}
	mi := &file_device_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceComponent) ProtoMessage() {}

func (x *DeviceComponent) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceComponent.ProtoReflect.Descriptor instead.
func (*DeviceComponent) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceComponent) GetKind() isDeviceComponent_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *DeviceComponent) GetDevice() *Device {
	if x != nil {
		if x, ok := x.Kind.(*DeviceComponent_Device); ok {
			return x.Device
		}
	}
	return nil
}

func (x *DeviceComponent) GetParam() *DeviceComponent_ComponentParam {
	if x != nil {
		if x, ok := x.Kind.(*DeviceComponent_Param); ok {
			return x.Param
		}
	}
	return nil
}

func (x *DeviceComponent) GetSharedConstraint() *DeviceComponent_ComponentConstraint {
	if x != nil {
		if x, ok := x.Kind.(*DeviceComponent_SharedConstraint); ok {
			return x.SharedConstraint
		}
	}
	return nil
}

func (x *DeviceComponent) GetMenu() *DeviceComponent_ComponentMenu {
	if x != nil {
		if x, ok := x.Kind.(*DeviceComponent_Menu); ok {
			return x.Menu
		}
	}
	return nil
}

func (x *DeviceComponent) GetCommand() *DeviceComponent_ComponentCommand {
	if x != nil {
		if x, ok := x.Kind.(*DeviceComponent_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *DeviceComponent) GetLanguagePack() *DeviceComponent_ComponentLanguagePack {
	if x != nil {
		if x, ok := x.Kind.(*DeviceComponent_LanguagePack); ok {
			return x.LanguagePack
		}
	}
	return nil
}

type isDeviceComponent_Kind interface {
	isDeviceComponent_Kind()
}

type DeviceComponent_Device struct {
	Device *Device `protobuf:"bytes,2,opt,name=device,proto3,oneof"`
}

type DeviceComponent_Param struct {
	Param *DeviceComponent_ComponentParam `protobuf:"bytes,3,opt,name=param,proto3,oneof"`
}

type DeviceComponent_SharedConstraint struct {
	SharedConstraint *DeviceComponent_ComponentConstraint `protobuf:"bytes,4,opt,name=shared_constraint,json=sharedConstraint,proto3,oneof"`
}

type DeviceComponent_Menu struct {
	Menu *DeviceComponent_ComponentMenu `protobuf:"bytes,5,opt,name=menu,proto3,oneof"`
}

type DeviceComponent_Command struct {
	Command *DeviceComponent_ComponentCommand `protobuf:"bytes,6,opt,name=command,proto3,oneof"`
}

type DeviceComponent_LanguagePack struct {
	LanguagePack *DeviceComponent_ComponentLanguagePack `protobuf:"bytes,7,opt,name=language_pack,json=languagePack,proto3,oneof"`
}

func (*DeviceComponent_Device) isDeviceComponent_Kind() {}

func (*DeviceComponent_Param) isDeviceComponent_Kind() {}

func (*DeviceComponent_SharedConstraint) isDeviceComponent_Kind() {}

func (*DeviceComponent_Menu) isDeviceComponent_Kind() {}

func (*DeviceComponent_Command) isDeviceComponent_Kind() {}

func (*DeviceComponent_LanguagePack) isDeviceComponent_Kind() {}

type RemoveComponents struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*RemoveComponents_Params
	//	*RemoveComponents_SharedConstraints
	//	*RemoveComponents_Menus
	//	*RemoveComponents_Commands
	//	*RemoveComponents_LanguagePacks
	Kind          isRemoveComponents_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveComponents) Reset() {
	*x = RemoveComponents{}
	mi := &file_device_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveComponents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveComponents) ProtoMessage() {}

func (x *RemoveComponents) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveComponents.ProtoReflect.Descriptor instead.
func (*RemoveComponents) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveComponents) GetKind() isRemoveComponents_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *RemoveComponents) GetParams() *RemoveComponents_IdList {
	if x != nil {
		if x, ok := x.Kind.(*RemoveComponents_Params); ok {
			return x.Params
		}
	}
	return nil
}

func (x *RemoveComponents) GetSharedConstraints() *RemoveComponents_IdList {
	if x != nil {
		if x, ok := x.Kind.(*RemoveComponents_SharedConstraints); ok {
			return x.SharedConstraints
		}
	}
	return nil
}

func (x *RemoveComponents) GetMenus() *RemoveComponents_IdList {
	if x != nil {
		if x, ok := x.Kind.(*RemoveComponents_Menus); ok {
			return x.Menus
		}
	}
	return nil
}

func (x *RemoveComponents) GetCommands() *RemoveComponents_IdList {
	if x != nil {
		if x, ok := x.Kind.(*RemoveComponents_Commands); ok {
			return x.Commands
		}
	}
	return nil
}

func (x *RemoveComponents) GetLanguagePacks() *RemoveComponents_IdList {
	if x != nil {
		if x, ok := x.Kind.(*RemoveComponents_LanguagePacks); ok {
			return x.LanguagePacks
		}
	}
	return nil
}

type isRemoveComponents_Kind interface {
	isRemoveComponents_Kind()
}

type RemoveComponents_Params struct {
	Params *RemoveComponents_IdList `protobuf:"bytes,3,opt,name=params,proto3,oneof"`
}

type RemoveComponents_SharedConstraints struct {
	// The oid is relative to the "constraints" child of the device's top-level
	// "types" object.
	SharedConstraints *RemoveComponents_IdList `protobuf:"bytes,4,opt,name=shared_constraints,json=sharedConstraints,proto3,oneof"`
}

type RemoveComponents_Menus struct {
	// Note that menus are grouped into menu groups. They are uniquely identified
	// by the json_pointer field which is relative to the Device's top-level
	// menu-groups object thus: menu-group-name/menu-name.
	// example: status/vendor_info
	Menus *RemoveComponents_IdList `protobuf:"bytes,5,opt,name=menus,proto3,oneof"`
}

type RemoveComponents_Commands struct {
	Commands *RemoveComponents_IdList `protobuf:"bytes,6,opt,name=commands,proto3,oneof"`
}

type RemoveComponents_LanguagePacks struct {
	// This should be the language code that identifies the language e.g. en-uk
	LanguagePacks *RemoveComponents_IdList `protobuf:"bytes,7,opt,name=language_packs,json=languagePacks,proto3,oneof"`
}

func (*RemoveComponents_Params) isRemoveComponents_Kind() {}

func (*RemoveComponents_SharedConstraints) isRemoveComponents_Kind() {}

func (*RemoveComponents_Menus) isRemoveComponents_Kind() {}

func (*RemoveComponents_Commands) isRemoveComponents_Kind() {}

func (*RemoveComponents_LanguagePacks) isRemoveComponents_Kind() {}

type DeviceRequestPayload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Slot           uint32                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`                                                                 // The slot id, must be included
	Language       string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`                                                          // Optionally specify the language for the response
	DetailLevel    Device_DetailLevel     `protobuf:"varint,3,opt,name=detail_level,json=detailLevel,proto3,enum=st2138.Device_DetailLevel" json:"detail_level,omitempty"` // Optionally specify the detail level for the response
	SubscribedOids []string               `protobuf:"bytes,4,rep,name=subscribed_oids,json=subscribedOids,proto3" json:"subscribed_oids,omitempty"`                        // Optionally specify a subscription list for the device (see UpdateSubscriptionsPayload)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeviceRequestPayload) Reset() {
	*x = DeviceRequestPayload{}
	mi := &file_device_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceRequestPayload) ProtoMessage() {}

func (x *DeviceRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceRequestPayload.ProtoReflect.Descriptor instead.
func (*DeviceRequestPayload) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{3}
}

func (x *DeviceRequestPayload) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *DeviceRequestPayload) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *DeviceRequestPayload) GetDetailLevel() Device_DetailLevel {
	if x != nil {
		return x.DetailLevel
	}
	return Device_FULL
}

func (x *DeviceRequestPayload) GetSubscribedOids() []string {
	if x != nil {
		return x.SubscribedOids
	}
	return nil
}

// Initial handshake between client and device.
type ConnectPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	DetailLevel   Device_DetailLevel     `protobuf:"varint,2,opt,name=detail_level,json=detailLevel,proto3,enum=st2138.Device_DetailLevel" json:"detail_level,omitempty"`
	UserAgent     string                 `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"` // Description of the client type and version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectPayload) Reset() {
	*x = ConnectPayload{}
	mi := &file_device_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectPayload) ProtoMessage() {}

func (x *ConnectPayload) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectPayload.ProtoReflect.Descriptor instead.
func (*ConnectPayload) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{4}
}

func (x *ConnectPayload) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ConnectPayload) GetDetailLevel() Device_DetailLevel {
	if x != nil {
		return x.DetailLevel
	}
	return Device_FULL
}

func (x *ConnectPayload) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

// Provides backward compatibility with binary OGP
type TrapMessage struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Type          TrapMessage_TrapMessageType `protobuf:"varint,1,opt,name=type,proto3,enum=st2138.TrapMessage_TrapMessageType" json:"type,omitempty"`
	TrapData      []string                    `protobuf:"bytes,2,rep,name=trap_data,json=trapData,proto3" json:"trap_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrapMessage) Reset() {
	*x = TrapMessage{}
	mi := &file_device_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrapMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrapMessage) ProtoMessage() {}

func (x *TrapMessage) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrapMessage.ProtoReflect.Descriptor instead.
func (*TrapMessage) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{5}
}

func (x *TrapMessage) GetType() TrapMessage_TrapMessageType {
	if x != nil {
		return x.Type
	}
	return TrapMessage_UNUSED
}

func (x *TrapMessage) GetTrapData() []string {
	if x != nil {
		return x.TrapData
	}
	return nil
}

type SlotList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slots         []uint32               `protobuf:"varint,1,rep,packed,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotList) Reset() {
	*x = SlotList{}
	mi := &file_device_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotList) ProtoMessage() {}

func (x *SlotList) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotList.ProtoReflect.Descriptor instead.
func (*SlotList) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{6}
}

func (x *SlotList) GetSlots() []uint32 {
	if x != nil {
		return x.Slots
	}
	return nil
}

// Messages that the device can push to the client.
type PushUpdates struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Slot  uint32                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	// Types that are valid to be assigned to Kind:
	//
	//	*PushUpdates_Value
	//	*PushUpdates_DeviceComponent
	//	*PushUpdates_Refused
	//	*PushUpdates_InvalidatedExternalObjectId
	//	*PushUpdates_TrapMessage
	//	*PushUpdates_InvalidateDeviceModel
	//	*PushUpdates_ExternalObject
	//	*PushUpdates_RemoveDeviceComponents
	//	*PushUpdates_SlotsAdded
	//	*PushUpdates_SlotsRemoved
	Kind          isPushUpdates_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushUpdates) Reset() {
	*x = PushUpdates{}
	mi := &file_device_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushUpdates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushUpdates) ProtoMessage() {}

func (x *PushUpdates) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushUpdates.ProtoReflect.Descriptor instead.
func (*PushUpdates) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{7}
}

func (x *PushUpdates) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *PushUpdates) GetKind() isPushUpdates_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *PushUpdates) GetValue() *PushUpdates_PushValue {
	if x != nil {
		if x, ok := x.Kind.(*PushUpdates_Value); ok {
			return x.Value
		}
	}
	return nil
}

func (x *PushUpdates) GetDeviceComponent() *DeviceComponent {
	if x != nil {
		if x, ok := x.Kind.(*PushUpdates_DeviceComponent); ok {
			return x.DeviceComponent
		}
	}
	return nil
}

func (x *PushUpdates) GetRefused() *Exception {
	if x != nil {
		if x, ok := x.Kind.(*PushUpdates_Refused); ok {
			return x.Refused
		}
	}
	return nil
}

func (x *PushUpdates) GetInvalidatedExternalObjectId() string {
	if x != nil {
		if x, ok := x.Kind.(*PushUpdates_InvalidatedExternalObjectId); ok {
			return x.InvalidatedExternalObjectId
		}
	}
	return ""
}

func (x *PushUpdates) GetTrapMessage() *TrapMessage {
	if x != nil {
		if x, ok := x.Kind.(*PushUpdates_TrapMessage); ok {
			return x.TrapMessage
		}
	}
	return nil
}

func (x *PushUpdates) GetInvalidateDeviceModel() bool {
	if x != nil {
		if x, ok := x.Kind.(*PushUpdates_InvalidateDeviceModel); ok {
			return x.InvalidateDeviceModel
		}
	}
	return false
}

func (x *PushUpdates) GetExternalObject() *PushUpdates_PushExternalObject {
	if x != nil {
		if x, ok := x.Kind.(*PushUpdates_ExternalObject); ok {
			return x.ExternalObject
		}
	}
	return nil
}

func (x *PushUpdates) GetRemoveDeviceComponents() *RemoveComponents {
	if x != nil {
		if x, ok := x.Kind.(*PushUpdates_RemoveDeviceComponents); ok {
			return x.RemoveDeviceComponents
		}
	}
	return nil
}

func (x *PushUpdates) GetSlotsAdded() *SlotList {
	if x != nil {
		if x, ok := x.Kind.(*PushUpdates_SlotsAdded); ok {
			return x.SlotsAdded
		}
	}
	return nil
}

func (x *PushUpdates) GetSlotsRemoved() *SlotList {
	if x != nil {
		if x, ok := x.Kind.(*PushUpdates_SlotsRemoved); ok {
			return x.SlotsRemoved
		}
	}
	return nil
}

type isPushUpdates_Kind interface {
	isPushUpdates_Kind()
}

type PushUpdates_Value struct {
	Value *PushUpdates_PushValue `protobuf:"bytes,2,opt,name=value,proto3,oneof"` // e.g. audio meters
}

type PushUpdates_DeviceComponent struct {
	DeviceComponent *DeviceComponent `protobuf:"bytes,3,opt,name=device_component,json=deviceComponent,proto3,oneof"`
}

type PushUpdates_Refused struct {
	Refused *Exception `protobuf:"bytes,4,opt,name=refused,proto3,oneof"`
}

type PushUpdates_InvalidatedExternalObjectId struct {
	InvalidatedExternalObjectId string `protobuf:"bytes,5,opt,name=invalidated_external_object_id,json=invalidatedExternalObjectId,proto3,oneof"`
}

type PushUpdates_TrapMessage struct {
	TrapMessage *TrapMessage `protobuf:"bytes,6,opt,name=trap_message,json=trapMessage,proto3,oneof"`
}

type PushUpdates_InvalidateDeviceModel struct {
	InvalidateDeviceModel bool `protobuf:"varint,7,opt,name=invalidate_device_model,json=invalidateDeviceModel,proto3,oneof"`
}

type PushUpdates_ExternalObject struct {
	ExternalObject *PushUpdates_PushExternalObject `protobuf:"bytes,8,opt,name=external_object,json=externalObject,proto3,oneof"`
}

type PushUpdates_RemoveDeviceComponents struct {
	RemoveDeviceComponents *RemoveComponents `protobuf:"bytes,9,opt,name=remove_device_components,json=removeDeviceComponents,proto3,oneof"`
}

type PushUpdates_SlotsAdded struct {
	SlotsAdded *SlotList `protobuf:"bytes,10,opt,name=slots_added,json=slotsAdded,proto3,oneof"`
}

type PushUpdates_SlotsRemoved struct {
	SlotsRemoved *SlotList `protobuf:"bytes,11,opt,name=slots_removed,json=slotsRemoved,proto3,oneof"`
}

func (*PushUpdates_Value) isPushUpdates_Kind() {}

func (*PushUpdates_DeviceComponent) isPushUpdates_Kind() {}

func (*PushUpdates_Refused) isPushUpdates_Kind() {}

func (*PushUpdates_InvalidatedExternalObjectId) isPushUpdates_Kind() {}

func (*PushUpdates_TrapMessage) isPushUpdates_Kind() {}

func (*PushUpdates_InvalidateDeviceModel) isPushUpdates_Kind() {}

func (*PushUpdates_ExternalObject) isPushUpdates_Kind() {}

func (*PushUpdates_RemoveDeviceComponents) isPushUpdates_Kind() {}

func (*PushUpdates_SlotsAdded) isPushUpdates_Kind() {}

func (*PushUpdates_SlotsRemoved) isPushUpdates_Kind() {}

// Request to refresh the access token with the one in the RPC metadata
// and extend the expiry time of all active connections to the exp
// claim in the new token.
type RefreshTokenPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"` // e.g. avoid timeout, key rotation, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenPayload) Reset() {
	*x = RefreshTokenPayload{}
	mi := &file_device_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenPayload) ProtoMessage() {}

func (x *RefreshTokenPayload) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenPayload.ProtoReflect.Descriptor instead.
func (*RefreshTokenPayload) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{8}
}

func (x *RefreshTokenPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Response to the RefreshToken request.
// If the client has any active streaming connections, the connected field
// will be true and the exp field will be the time that the new token will expire.
type ConnectionStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connected     bool                   `protobuf:"varint,1,opt,name=connected,proto3" json:"connected,omitempty"` // True if client has any active streaming connections
	Exp           uint64                 `protobuf:"varint,2,opt,name=exp,proto3" json:"exp,omitempty"`             // Time that new token will expire
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionStatus) Reset() {
	*x = ConnectionStatus{}
	mi := &file_device_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionStatus) ProtoMessage() {}

func (x *ConnectionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionStatus.ProtoReflect.Descriptor instead.
func (*ConnectionStatus) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{9}
}

func (x *ConnectionStatus) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *ConnectionStatus) GetExp() uint64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

// Request to revoke access for a subject.
// If revoke_all is true, all active connections for the subject will be revoked.
type RevokeAccessPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`                       // e.g. user id, device id, etc.
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                         // e.g. avoid timeout, key rotation, etc.
	RevokeAll     bool                   `protobuf:"varint,3,opt,name=revoke_all,json=revokeAll,proto3" json:"revoke_all,omitempty"` // True to revoke access for all subjects
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAccessPayload) Reset() {
	*x = RevokeAccessPayload{}
	mi := &file_device_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAccessPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAccessPayload) ProtoMessage() {}

func (x *RevokeAccessPayload) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAccessPayload.ProtoReflect.Descriptor instead.
func (*RevokeAccessPayload) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{10}
}

func (x *RevokeAccessPayload) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *RevokeAccessPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RevokeAccessPayload) GetRevokeAll() bool {
	if x != nil {
		return x.RevokeAll
	}
	return false
}

// Response to the RevokeAccess request.
// Lists sub fields of remaining and revoked subjects.
type RevocationResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RemainingSubjects []string               `protobuf:"bytes,1,rep,name=remaining_subjects,json=remainingSubjects,proto3" json:"remaining_subjects,omitempty"` // user / system ids still connected
	RevokedSubjects   []string               `protobuf:"bytes,2,rep,name=revoked_subjects,json=revokedSubjects,proto3" json:"revoked_subjects,omitempty"`       // user / system ids that were revoked
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RevocationResponse) Reset() {
	*x = RevocationResponse{}
	mi := &file_device_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevocationResponse) ProtoMessage() {}

func (x *RevocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevocationResponse.ProtoReflect.Descriptor instead.
func (*RevocationResponse) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{11}
}

func (x *RevocationResponse) GetRemainingSubjects() []string {
	if x != nil {
		return x.RemainingSubjects
	}
	return nil
}

func (x *RevocationResponse) GetRevokedSubjects() []string {
	if x != nil {
		return x.RevokedSubjects
	}
	return nil
}

// A parameter or sub-parameter, or sub-sub-parameter, or ...
//
// These can be arbitrarily nested so a JSON pointer (RFC 6901) is used to
// locate the component within the data model.
// This is to allow large parameter trees to be broken into smaller
// components.
//
// The json_pointer is relative to device["params"].
// Let's see how this could be arranged for an audio processing device
// which has a monitor output mix that has gain and eq controls.
//
// monitor - top level object id. The json_pointer is an object id in this
// case. The whole multi-level parameter descriptor would form the body
// of the message.
//
// monitor/eq, monitor/level - sub-params of the top-level monitor
// parameter. The json_pointer is a cascade of object IDs.
// Only the selected sub-param occupies the message body. Note that the eq
// param is likely an array of 4 objects. Without an index in the
// json_pointer, the whole array forms the body of the message.
//
// monitor/eq/1/f, monitor/eq/1/q, monitor/eq/1/gain sub-sub params of
// eq 2 in the monitor output audio processing.
// It's likely not practical to use messages this small to report device
// models, but this illustrates how it could be done if desirable.
type DeviceComponent_ComponentParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Oid           string                 `protobuf:"bytes,1,opt,name=oid,proto3" json:"oid,omitempty"`
	Param         *Param                 `protobuf:"bytes,2,opt,name=param,proto3" json:"param,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceComponent_ComponentParam) Reset() {
	*x = DeviceComponent_ComponentParam{}
	mi := &file_device_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceComponent_ComponentParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceComponent_ComponentParam) ProtoMessage() {}

func (x *DeviceComponent_ComponentParam) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceComponent_ComponentParam.ProtoReflect.Descriptor instead.
func (*DeviceComponent_ComponentParam) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{1, 0}
}

func (x *DeviceComponent_ComponentParam) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

func (x *DeviceComponent_ComponentParam) GetParam() *Param {
	if x != nil {
		return x.Param
	}
	return nil
}

// A menu.
// Note that menus are grouped into menu groups. They are uniquely identified
// by the json_pointer field which is relative to the Device's top-level
// menu-groups object thus: menu-group-name/menu-name.
// example: status/vendor_info
type DeviceComponent_ComponentMenu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Oid           string                 `protobuf:"bytes,1,opt,name=oid,proto3" json:"oid,omitempty"`
	Menu          *Menu                  `protobuf:"bytes,2,opt,name=menu,proto3" json:"menu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceComponent_ComponentMenu) Reset() {
	*x = DeviceComponent_ComponentMenu{}
	mi := &file_device_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceComponent_ComponentMenu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceComponent_ComponentMenu) ProtoMessage() {}

func (x *DeviceComponent_ComponentMenu) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceComponent_ComponentMenu.ProtoReflect.Descriptor instead.
func (*DeviceComponent_ComponentMenu) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{1, 1}
}

func (x *DeviceComponent_ComponentMenu) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

func (x *DeviceComponent_ComponentMenu) GetMenu() *Menu {
	if x != nil {
		return x.Menu
	}
	return nil
}

// A constraint descriptor.
// The oid is relative to the "constraints" child of the device's top-level
// "types" object.
type DeviceComponent_ComponentConstraint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Oid           string                 `protobuf:"bytes,1,opt,name=oid,proto3" json:"oid,omitempty"`
	Constraint    *Constraint            `protobuf:"bytes,2,opt,name=constraint,proto3" json:"constraint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceComponent_ComponentConstraint) Reset() {
	*x = DeviceComponent_ComponentConstraint{}
	mi := &file_device_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceComponent_ComponentConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceComponent_ComponentConstraint) ProtoMessage() {}

func (x *DeviceComponent_ComponentConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceComponent_ComponentConstraint.ProtoReflect.Descriptor instead.
func (*DeviceComponent_ComponentConstraint) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{1, 2}
}

func (x *DeviceComponent_ComponentConstraint) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

func (x *DeviceComponent_ComponentConstraint) GetConstraint() *Constraint {
	if x != nil {
		return x.Constraint
	}
	return nil
}

// A command descriptor.
// Defines a command to be mapped to device.commands.oid
type DeviceComponent_ComponentCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Oid           string                 `protobuf:"bytes,1,opt,name=oid,proto3" json:"oid,omitempty"`
	Command       *Param                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceComponent_ComponentCommand) Reset() {
	*x = DeviceComponent_ComponentCommand{}
	mi := &file_device_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceComponent_ComponentCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceComponent_ComponentCommand) ProtoMessage() {}

func (x *DeviceComponent_ComponentCommand) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceComponent_ComponentCommand.ProtoReflect.Descriptor instead.
func (*DeviceComponent_ComponentCommand) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{1, 3}
}

func (x *DeviceComponent_ComponentCommand) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

func (x *DeviceComponent_ComponentCommand) GetCommand() *Param {
	if x != nil {
		return x.Command
	}
	return nil
}

// A language pack.
type DeviceComponent_ComponentLanguagePack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"` // Language string is the language code that identifies the language e.g. en-uk
	LanguagePack  *LanguagePack          `protobuf:"bytes,2,opt,name=language_pack,json=languagePack,proto3" json:"language_pack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceComponent_ComponentLanguagePack) Reset() {
	*x = DeviceComponent_ComponentLanguagePack{}
	mi := &file_device_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceComponent_ComponentLanguagePack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceComponent_ComponentLanguagePack) ProtoMessage() {}

func (x *DeviceComponent_ComponentLanguagePack) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceComponent_ComponentLanguagePack.ProtoReflect.Descriptor instead.
func (*DeviceComponent_ComponentLanguagePack) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{1, 4}
}

func (x *DeviceComponent_ComponentLanguagePack) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *DeviceComponent_ComponentLanguagePack) GetLanguagePack() *LanguagePack {
	if x != nil {
		return x.LanguagePack
	}
	return nil
}

type RemoveComponents_IdList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Oids          []string               `protobuf:"bytes,1,rep,name=oids,proto3" json:"oids,omitempty"` // A list of object ids (OIDs) to remove
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveComponents_IdList) Reset() {
	*x = RemoveComponents_IdList{}
	mi := &file_device_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveComponents_IdList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveComponents_IdList) ProtoMessage() {}

func (x *RemoveComponents_IdList) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveComponents_IdList.ProtoReflect.Descriptor instead.
func (*RemoveComponents_IdList) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{2, 0}
}

func (x *RemoveComponents_IdList) GetOids() []string {
	if x != nil {
		return x.Oids
	}
	return nil
}

type PushUpdates_PushExternalObject struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Oid            string                 `protobuf:"bytes,1,opt,name=oid,proto3" json:"oid,omitempty"`
	ExternalObject *ExternalObjectPayload `protobuf:"bytes,2,opt,name=external_object,json=externalObject,proto3" json:"external_object,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PushUpdates_PushExternalObject) Reset() {
	*x = PushUpdates_PushExternalObject{}
	mi := &file_device_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushUpdates_PushExternalObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushUpdates_PushExternalObject) ProtoMessage() {}

func (x *PushUpdates_PushExternalObject) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushUpdates_PushExternalObject.ProtoReflect.Descriptor instead.
func (*PushUpdates_PushExternalObject) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{7, 0}
}

func (x *PushUpdates_PushExternalObject) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

func (x *PushUpdates_PushExternalObject) GetExternalObject() *ExternalObjectPayload {
	if x != nil {
		return x.ExternalObject
	}
	return nil
}

type PushUpdates_PushValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Oid           string                 `protobuf:"bytes,1,opt,name=oid,proto3" json:"oid,omitempty"`
	Value         *Value                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushUpdates_PushValue) Reset() {
	*x = PushUpdates_PushValue{}
	mi := &file_device_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushUpdates_PushValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushUpdates_PushValue) ProtoMessage() {}

func (x *PushUpdates_PushValue) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushUpdates_PushValue.ProtoReflect.Descriptor instead.
func (*PushUpdates_PushValue) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{7, 1}
}

func (x *PushUpdates_PushValue) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

func (x *PushUpdates_PushValue) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_device_proto protoreflect.FileDescriptor

const file_device_proto_rawDesc = "" +
	"\n" +
	"\fdevice.proto\x12\x06st2138\x1a\x10constraint.proto\x1a\vparam.proto\x1a\n" +
	"menu.proto\x1a\x0elanguage.proto\x1a\x14externalobject.proto\"\xbf\a\n" +
	"\x06Device\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\rR\x04slot\x12=\n" +
	"\fdetail_level\x18\x02 \x01(\x0e2\x1a.st2138.Device.DetailLevelR\vdetailLevel\x12*\n" +
	"\x11multi_set_enabled\x18\x03 \x01(\bR\x0fmultiSetEnabled\x12$\n" +
	"\rsubscriptions\x18\x04 \x01(\bR\rsubscriptions\x12A\n" +
	"\vconstraints\x18\x05 \x03(\v2\x1f.st2138.Device.ConstraintsEntryR\vconstraints\x122\n" +
	"\x06params\x18\x06 \x03(\v2\x1a.st2138.Device.ParamsEntryR\x06params\x12?\n" +
	"\vmenu_groups\x18\a \x03(\v2\x1e.st2138.Device.MenuGroupsEntryR\n" +
	"menuGroups\x128\n" +
	"\bcommands\x18\b \x03(\v2\x1c.st2138.Device.CommandsEntryR\bcommands\x12<\n" +
	"\x0elanguage_packs\x18\t \x01(\v2\x15.st2138.LanguagePacksR\rlanguagePacks\x12#\n" +
	"\raccess_scopes\x18\n" +
	" \x03(\tR\faccessScopes\x12#\n" +
	"\rdefault_scope\x18\v \x01(\tR\fdefaultScope\x1aR\n" +
	"\x10ConstraintsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.st2138.ConstraintR\x05value:\x028\x01\x1aH\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.st2138.ParamR\x05value:\x028\x01\x1aP\n" +
	"\x0fMenuGroupsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.st2138.MenuGroupR\x05value:\x028\x01\x1aJ\n" +
	"\rCommandsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.st2138.ParamR\x05value:\x028\x01\"Z\n" +
	"\vDetailLevel\x12\b\n" +
	"\x04FULL\x10\x00\x12\x11\n" +
	"\rSUBSCRIPTIONS\x10\x01\x12\v\n" +
	"\aMINIMAL\x10\x02\x12\f\n" +
	"\bCOMMANDS\x10\x03\x12\b\n" +
	"\x04NONE\x10\x04\x12\t\n" +
	"\x05UNSET\x10\x05\"\xe2\x06\n" +
	"\x0fDeviceComponent\x12(\n" +
	"\x06device\x18\x02 \x01(\v2\x0e.st2138.DeviceH\x00R\x06device\x12>\n" +
	"\x05param\x18\x03 \x01(\v2&.st2138.DeviceComponent.ComponentParamH\x00R\x05param\x12Z\n" +
	"\x11shared_constraint\x18\x04 \x01(\v2+.st2138.DeviceComponent.ComponentConstraintH\x00R\x10sharedConstraint\x12;\n" +
	"\x04menu\x18\x05 \x01(\v2%.st2138.DeviceComponent.ComponentMenuH\x00R\x04menu\x12D\n" +
	"\acommand\x18\x06 \x01(\v2(.st2138.DeviceComponent.ComponentCommandH\x00R\acommand\x12T\n" +
	"\rlanguage_pack\x18\a \x01(\v2-.st2138.DeviceComponent.ComponentLanguagePackH\x00R\flanguagePack\x1aG\n" +
	"\x0eComponentParam\x12\x10\n" +
	"\x03oid\x18\x01 \x01(\tR\x03oid\x12#\n" +
	"\x05param\x18\x02 \x01(\v2\r.st2138.ParamR\x05param\x1aC\n" +
	"\rComponentMenu\x12\x10\n" +
	"\x03oid\x18\x01 \x01(\tR\x03oid\x12 \n" +
	"\x04menu\x18\x02 \x01(\v2\f.st2138.MenuR\x04menu\x1a[\n" +
	"\x13ComponentConstraint\x12\x10\n" +
	"\x03oid\x18\x01 \x01(\tR\x03oid\x122\n" +
	"\n" +
	"constraint\x18\x02 \x01(\v2\x12.st2138.ConstraintR\n" +
	"constraint\x1aM\n" +
	"\x10ComponentCommand\x12\x10\n" +
	"\x03oid\x18\x01 \x01(\tR\x03oid\x12'\n" +
	"\acommand\x18\x02 \x01(\v2\r.st2138.ParamR\acommand\x1an\n" +
	"\x15ComponentLanguagePack\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x129\n" +
	"\rlanguage_pack\x18\x02 \x01(\v2\x14.st2138.LanguagePackR\flanguagePackB\x06\n" +
	"\x04kind\"\x87\x03\n" +
	"\x10RemoveComponents\x129\n" +
	"\x06params\x18\x03 \x01(\v2\x1f.st2138.RemoveComponents.IdListH\x00R\x06params\x12P\n" +
	"\x12shared_constraints\x18\x04 \x01(\v2\x1f.st2138.RemoveComponents.IdListH\x00R\x11sharedConstraints\x127\n" +
	"\x05menus\x18\x05 \x01(\v2\x1f.st2138.RemoveComponents.IdListH\x00R\x05menus\x12=\n" +
	"\bcommands\x18\x06 \x01(\v2\x1f.st2138.RemoveComponents.IdListH\x00R\bcommands\x12H\n" +
	"\x0elanguage_packs\x18\a \x01(\v2\x1f.st2138.RemoveComponents.IdListH\x00R\rlanguagePacks\x1a\x1c\n" +
	"\x06IdList\x12\x12\n" +
	"\x04oids\x18\x01 \x03(\tR\x04oidsB\x06\n" +
	"\x04kind\"\xae\x01\n" +
	"\x14DeviceRequestPayload\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\rR\x04slot\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12=\n" +
	"\fdetail_level\x18\x03 \x01(\x0e2\x1a.st2138.Device.DetailLevelR\vdetailLevel\x12'\n" +
	"\x0fsubscribed_oids\x18\x04 \x03(\tR\x0esubscribedOids\"\x8a\x01\n" +
	"\x0eConnectPayload\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12=\n" +
	"\fdetail_level\x18\x02 \x01(\x0e2\x1a.st2138.Device.DetailLevelR\vdetailLevel\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x03 \x01(\tR\tuserAgent\"\xb7\x02\n" +
	"\vTrapMessage\x127\n" +
	"\x04type\x18\x01 \x01(\x0e2#.st2138.TrapMessage.TrapMessageTypeR\x04type\x12\x1b\n" +
	"\ttrap_data\x18\x02 \x03(\tR\btrapData\"\xd1\x01\n" +
	"\x0fTrapMessageType\x12\n" +
	"\n" +
	"\x06UNUSED\x10\x00\x12\v\n" +
	"\aRESTART\x10\x01\x12\x11\n" +
	"\rPARAM_CHANGED\x10\x02\x12\x10\n" +
	"\fMENU_CHANGED\x10\x03\x12\x1b\n" +
	"\x17EXTERNAL_OBJECT_CHANGED\x10\x04\x12\x12\n" +
	"\x0eREVEAL_ELEMENT\x10\x05\x12\x10\n" +
	"\fHIDE_ELEMENT\x10\x06\x12\x15\n" +
	"\x11RELOAD_UI_ELEMENT\x10\a\x12\x16\n" +
	"\x12STRING_OID_CHANGED\x10\b\x12\x0e\n" +
	"\n" +
	"REBUILD_UI\x10\t\" \n" +
	"\bSlotList\x12\x14\n" +
	"\x05slots\x18\x01 \x03(\rR\x05slots\"\xdb\x06\n" +
	"\vPushUpdates\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\rR\x04slot\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.st2138.PushUpdates.PushValueH\x00R\x05value\x12D\n" +
	"\x10device_component\x18\x03 \x01(\v2\x17.st2138.DeviceComponentH\x00R\x0fdeviceComponent\x12-\n" +
	"\arefused\x18\x04 \x01(\v2\x11.st2138.ExceptionH\x00R\arefused\x12E\n" +
	"\x1einvalidated_external_object_id\x18\x05 \x01(\tH\x00R\x1binvalidatedExternalObjectId\x128\n" +
	"\ftrap_message\x18\x06 \x01(\v2\x13.st2138.TrapMessageH\x00R\vtrapMessage\x128\n" +
	"\x17invalidate_device_model\x18\a \x01(\bH\x00R\x15invalidateDeviceModel\x12Q\n" +
	"\x0fexternal_object\x18\b \x01(\v2&.st2138.PushUpdates.PushExternalObjectH\x00R\x0eexternalObject\x12T\n" +
	"\x18remove_device_components\x18\t \x01(\v2\x18.st2138.RemoveComponentsH\x00R\x16removeDeviceComponents\x123\n" +
	"\vslots_added\x18\n" +
	" \x01(\v2\x10.st2138.SlotListH\x00R\n" +
	"slotsAdded\x127\n" +
	"\rslots_removed\x18\v \x01(\v2\x10.st2138.SlotListH\x00R\fslotsRemoved\x1an\n" +
	"\x12PushExternalObject\x12\x10\n" +
	"\x03oid\x18\x01 \x01(\tR\x03oid\x12F\n" +
	"\x0fexternal_object\x18\x02 \x01(\v2\x1d.st2138.ExternalObjectPayloadR\x0eexternalObject\x1aB\n" +
	"\tPushValue\x12\x10\n" +
	"\x03oid\x18\x01 \x01(\tR\x03oid\x12#\n" +
	"\x05value\x18\x03 \x01(\v2\r.st2138.ValueR\x05valueB\x06\n" +
	"\x04kind\"-\n" +
	"\x13RefreshTokenPayload\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"B\n" +
	"\x10ConnectionStatus\x12\x1c\n" +
	"\tconnected\x18\x01 \x01(\bR\tconnected\x12\x10\n" +
	"\x03exp\x18\x02 \x01(\x04R\x03exp\"f\n" +
	"\x13RevokeAccessPayload\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"revoke_all\x18\x03 \x01(\bR\trevokeAll\"n\n" +
	"\x12RevocationResponse\x12-\n" +
	"\x12remaining_subjects\x18\x01 \x03(\tR\x11remainingSubjects\x12)\n" +
	"\x10revoked_subjects\x18\x02 \x03(\tR\x0frevokedSubjectsB&\n" +
	"\x12catena.core.deviceB\fDeviceProtosH\x01P\x01b\x06proto3"

var (
	file_device_proto_rawDescOnce sync.Once
	file_device_proto_rawDescData []byte
)

func file_device_proto_rawDescGZIP() []byte {
	file_device_proto_rawDescOnce.Do(func() {
		file_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_device_proto_rawDesc), len(file_device_proto_rawDesc)))
	})
	return file_device_proto_rawDescData
}

var file_device_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_device_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_device_proto_goTypes = []any{
	(Device_DetailLevel)(0),                // 0: st2138.Device.DetailLevel
	(TrapMessage_TrapMessageType)(0),       // 1: st2138.TrapMessage.TrapMessageType
	(*Device)(nil),                         // 2: st2138.Device
	(*DeviceComponent)(nil),                // 3: st2138.DeviceComponent
	(*RemoveComponents)(nil),               // 4: st2138.RemoveComponents
	(*DeviceRequestPayload)(nil),           // 5: st2138.DeviceRequestPayload
	(*ConnectPayload)(nil),                 // 6: st2138.ConnectPayload
	(*TrapMessage)(nil),                    // 7: st2138.TrapMessage
	(*SlotList)(nil),                       // 8: st2138.SlotList
	(*PushUpdates)(nil),                    // 9: st2138.PushUpdates
	(*RefreshTokenPayload)(nil),            // 10: st2138.RefreshTokenPayload
	(*ConnectionStatus)(nil),               // 11: st2138.ConnectionStatus
	(*RevokeAccessPayload)(nil),            // 12: st2138.RevokeAccessPayload
	(*RevocationResponse)(nil),             // 13: st2138.RevocationResponse
	nil,                                    // 14: st2138.Device.ConstraintsEntry
	nil,                                    // 15: st2138.Device.ParamsEntry
	nil,                                    // 16: st2138.Device.MenuGroupsEntry
	nil,                                    // 17: st2138.Device.CommandsEntry
	(*DeviceComponent_ComponentParam)(nil), // 18: st2138.DeviceComponent.ComponentParam
	(*DeviceComponent_ComponentMenu)(nil),  // 19: st2138.DeviceComponent.ComponentMenu
	(*DeviceComponent_ComponentConstraint)(nil),   // 20: st2138.DeviceComponent.ComponentConstraint
	(*DeviceComponent_ComponentCommand)(nil),      // 21: st2138.DeviceComponent.ComponentCommand
	(*DeviceComponent_ComponentLanguagePack)(nil), // 22: st2138.DeviceComponent.ComponentLanguagePack
	(*RemoveComponents_IdList)(nil),               // 23: st2138.RemoveComponents.IdList
	(*PushUpdates_PushExternalObject)(nil),        // 24: st2138.PushUpdates.PushExternalObject
	(*PushUpdates_PushValue)(nil),                 // 25: st2138.PushUpdates.PushValue
	(*LanguagePacks)(nil),                         // 26: st2138.LanguagePacks
	(*Exception)(nil),                             // 27: st2138.Exception
	(*Constraint)(nil),                            // 28: st2138.Constraint
	(*Param)(nil),                                 // 29: st2138.Param
	(*MenuGroup)(nil),                             // 30: st2138.MenuGroup
	(*Menu)(nil),                                  // 31: st2138.Menu
	(*LanguagePack)(nil),                          // 32: st2138.LanguagePack
	(*ExternalObjectPayload)(nil),                 // 33: st2138.ExternalObjectPayload
	(*Value)(nil),                                 // 34: st2138.Value
}
var file_device_proto_depIdxs = []int32{
	0,  // 0: st2138.Device.detail_level:type_name -> st2138.Device.DetailLevel
	14, // 1: st2138.Device.constraints:type_name -> st2138.Device.ConstraintsEntry
	15, // 2: st2138.Device.params:type_name -> st2138.Device.ParamsEntry
	16, // 3: st2138.Device.menu_groups:type_name -> st2138.Device.MenuGroupsEntry
	17, // 4: st2138.Device.commands:type_name -> st2138.Device.CommandsEntry
	26, // 5: st2138.Device.language_packs:type_name -> st2138.LanguagePacks
	2,  // 6: st2138.DeviceComponent.device:type_name -> st2138.Device
	18, // 7: st2138.DeviceComponent.param:type_name -> st2138.DeviceComponent.ComponentParam
	20, // 8: st2138.DeviceComponent.shared_constraint:type_name -> st2138.DeviceComponent.ComponentConstraint
	19, // 9: st2138.DeviceComponent.menu:type_name -> st2138.DeviceComponent.ComponentMenu
	21, // 10: st2138.DeviceComponent.command:type_name -> st2138.DeviceComponent.ComponentCommand
	22, // 11: st2138.DeviceComponent.language_pack:type_name -> st2138.DeviceComponent.ComponentLanguagePack
	23, // 12: st2138.RemoveComponents.params:type_name -> st2138.RemoveComponents.IdList
	23, // 13: st2138.RemoveComponents.shared_constraints:type_name -> st2138.RemoveComponents.IdList
	23, // 14: st2138.RemoveComponents.menus:type_name -> st2138.RemoveComponents.IdList
	23, // 15: st2138.RemoveComponents.commands:type_name -> st2138.RemoveComponents.IdList
	23, // 16: st2138.RemoveComponents.language_packs:type_name -> st2138.RemoveComponents.IdList
	0,  // 17: st2138.DeviceRequestPayload.detail_level:type_name -> st2138.Device.DetailLevel
	0,  // 18: st2138.ConnectPayload.detail_level:type_name -> st2138.Device.DetailLevel
	1,  // 19: st2138.TrapMessage.type:type_name -> st2138.TrapMessage.TrapMessageType
	25, // 20: st2138.PushUpdates.value:type_name -> st2138.PushUpdates.PushValue
	3,  // 21: st2138.PushUpdates.device_component:type_name -> st2138.DeviceComponent
	27, // 22: st2138.PushUpdates.refused:type_name -> st2138.Exception
	7,  // 23: st2138.PushUpdates.trap_message:type_name -> st2138.TrapMessage
	24, // 24: st2138.PushUpdates.external_object:type_name -> st2138.PushUpdates.PushExternalObject
	4,  // 25: st2138.PushUpdates.remove_device_components:type_name -> st2138.RemoveComponents
	8,  // 26: st2138.PushUpdates.slots_added:type_name -> st2138.SlotList
	8,  // 27: st2138.PushUpdates.slots_removed:type_name -> st2138.SlotList
	28, // 28: st2138.Device.ConstraintsEntry.value:type_name -> st2138.Constraint
	29, // 29: st2138.Device.ParamsEntry.value:type_name -> st2138.Param
	30, // 30: st2138.Device.MenuGroupsEntry.value:type_name -> st2138.MenuGroup
	29, // 31: st2138.Device.CommandsEntry.value:type_name -> st2138.Param
	29, // 32: st2138.DeviceComponent.ComponentParam.param:type_name -> st2138.Param
	31, // 33: st2138.DeviceComponent.ComponentMenu.menu:type_name -> st2138.Menu
	28, // 34: st2138.DeviceComponent.ComponentConstraint.constraint:type_name -> st2138.Constraint
	29, // 35: st2138.DeviceComponent.ComponentCommand.command:type_name -> st2138.Param
	32, // 36: st2138.DeviceComponent.ComponentLanguagePack.language_pack:type_name -> st2138.LanguagePack
	33, // 37: st2138.PushUpdates.PushExternalObject.external_object:type_name -> st2138.ExternalObjectPayload
	34, // 38: st2138.PushUpdates.PushValue.value:type_name -> st2138.Value
	39, // [39:39] is the sub-list for method output_type
	39, // [39:39] is the sub-list for method input_type
	39, // [39:39] is the sub-list for extension type_name
	39, // [39:39] is the sub-list for extension extendee
	0,  // [0:39] is the sub-list for field type_name
}

func init() { file_device_proto_init() }
func file_device_proto_init() {
	if File_device_proto != nil {
		return
	}
	file_constraint_proto_init()
	file_param_proto_init()
	file_menu_proto_init()
	file_language_proto_init()
	file_externalobject_proto_init()
	file_device_proto_msgTypes[1].OneofWrappers = []any{
		(*DeviceComponent_Device)(nil),
		(*DeviceComponent_Param)(nil),
		(*DeviceComponent_SharedConstraint)(nil),
		(*DeviceComponent_Menu)(nil),
		(*DeviceComponent_Command)(nil),
		(*DeviceComponent_LanguagePack)(nil),
	}
	file_device_proto_msgTypes[2].OneofWrappers = []any{
		(*RemoveComponents_Params)(nil),
		(*RemoveComponents_SharedConstraints)(nil),
		(*RemoveComponents_Menus)(nil),
		(*RemoveComponents_Commands)(nil),
		(*RemoveComponents_LanguagePacks)(nil),
	}
	file_device_proto_msgTypes[7].OneofWrappers = []any{
		(*PushUpdates_Value)(nil),
		(*PushUpdates_DeviceComponent)(nil),
		(*PushUpdates_Refused)(nil),
		(*PushUpdates_InvalidatedExternalObjectId)(nil),
		(*PushUpdates_TrapMessage)(nil),
		(*PushUpdates_InvalidateDeviceModel)(nil),
		(*PushUpdates_ExternalObject)(nil),
		(*PushUpdates_RemoveDeviceComponents)(nil),
		(*PushUpdates_SlotsAdded)(nil),
		(*PushUpdates_SlotsRemoved)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_device_proto_rawDesc), len(file_device_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_device_proto_goTypes,
		DependencyIndexes: file_device_proto_depIdxs,
		EnumInfos:         file_device_proto_enumTypes,
		MessageInfos:      file_device_proto_msgTypes,
	}.Build()
	File_device_proto = out.File
	file_device_proto_goTypes = nil
	file_device_proto_depIdxs = nil
}
