//
// Copyright (c) by the Society of Motion Picture and Television Engineers
//
// Redistribution and use in source and binary forms, with or without modification,
// are permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice, this
// list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice,
// this list of conditions and the following disclaimer in the documentation and/or
// other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its contributors
// may be used to endorse or promote products derived from this software without
// specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
// ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
// ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: externalobject.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExternalObjectRequestPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint32                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"` // Uniquely identifies the device at node scope.
	Oid           string                 `protobuf:"bytes,2,opt,name=oid,proto3" json:"oid,omitempty"`    // ID of external object being requested
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalObjectRequestPayload) Reset() {
	*x = ExternalObjectRequestPayload{}
	mi := &file_externalobject_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalObjectRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalObjectRequestPayload) ProtoMessage() {}

func (x *ExternalObjectRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_externalobject_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalObjectRequestPayload.ProtoReflect.Descriptor instead.
func (*ExternalObjectRequestPayload) Descriptor() ([]byte, []int) {
	return file_externalobject_proto_rawDescGZIP(), []int{0}
}

func (x *ExternalObjectRequestPayload) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *ExternalObjectRequestPayload) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

type ExternalObjectPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cachable      bool                   `protobuf:"varint,1,opt,name=cachable,proto3" json:"cachable,omitempty"` // If false, do not cache the external object payload
	Payload       *DataPayload           `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalObjectPayload) Reset() {
	*x = ExternalObjectPayload{}
	mi := &file_externalobject_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalObjectPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalObjectPayload) ProtoMessage() {}

func (x *ExternalObjectPayload) ProtoReflect() protoreflect.Message {
	mi := &file_externalobject_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalObjectPayload.ProtoReflect.Descriptor instead.
func (*ExternalObjectPayload) Descriptor() ([]byte, []int) {
	return file_externalobject_proto_rawDescGZIP(), []int{1}
}

func (x *ExternalObjectPayload) GetCachable() bool {
	if x != nil {
		return x.Cachable
	}
	return false
}

func (x *ExternalObjectPayload) GetPayload() *DataPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_externalobject_proto protoreflect.FileDescriptor

const file_externalobject_proto_rawDesc = "" +
	"\n" +
	"\x14externalobject.proto\x12\x06st2138\x1a\vparam.proto\"D\n" +
	"\x1cExternalObjectRequestPayload\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\rR\x04slot\x12\x10\n" +
	"\x03oid\x18\x02 \x01(\tR\x03oid\"b\n" +
	"\x15ExternalObjectPayload\x12\x1a\n" +
	"\bcachable\x18\x01 \x01(\bR\bcachable\x12-\n" +
	"\apayload\x18\x02 \x01(\v2\x13.st2138.DataPayloadR\apayloadB6\n" +
	"\x1acatena.core.externalobjectB\x14ExternalObjectProtosH\x01P\x01b\x06proto3"

var (
	file_externalobject_proto_rawDescOnce sync.Once
	file_externalobject_proto_rawDescData []byte
)

func file_externalobject_proto_rawDescGZIP() []byte {
	file_externalobject_proto_rawDescOnce.Do(func() {
		file_externalobject_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_externalobject_proto_rawDesc), len(file_externalobject_proto_rawDesc)))
	})
	return file_externalobject_proto_rawDescData
}

var file_externalobject_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_externalobject_proto_goTypes = []any{
	(*ExternalObjectRequestPayload)(nil), // 0: st2138.ExternalObjectRequestPayload
	(*ExternalObjectPayload)(nil),        // 1: st2138.ExternalObjectPayload
	(*DataPayload)(nil),                  // 2: st2138.DataPayload
}
var file_externalobject_proto_depIdxs = []int32{
	2, // 0: st2138.ExternalObjectPayload.payload:type_name -> st2138.DataPayload
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_externalobject_proto_init() }
func file_externalobject_proto_init() {
	if File_externalobject_proto != nil {
		return
	}
	file_param_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_externalobject_proto_rawDesc), len(file_externalobject_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_externalobject_proto_goTypes,
		DependencyIndexes: file_externalobject_proto_depIdxs,
		MessageInfos:      file_externalobject_proto_msgTypes,
	}.Build()
	File_externalobject_proto = out.File
	file_externalobject_proto_goTypes = nil
	file_externalobject_proto_depIdxs = nil
}
