//
// Copyright (c) by the Society of Motion Picture and Television Engineers
//
// Redistribution and use in source and binary forms, with or without modification,
// are permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice, this
// list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice,
// this list of conditions and the following disclaimer in the documentation and/or
// other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its contributors
// may be used to endorse or promote products derived from this software without
// specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
// ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
// ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: menu.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Menu message.
// Defines a logical grouping of commands and parameters that can be displayed
// together in a GUI and have client access control applied.
// Note that sub-parameters (and sub-sub-parameters) can be selected by
// specifying a JSON pointer relative to the device's "params" component.
type Menu struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Display name for the Menu
	Name *PolyglotText `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Whether the menu should be hidden in the client GUI.
	Hidden bool `protobuf:"varint,2,opt,name=hidden,proto3" json:"hidden,omitempty"`
	// Whether the menu should be disabled (shown as read-only) in the client GUI.
	Disabled bool `protobuf:"varint,3,opt,name=disabled,proto3" json:"disabled,omitempty"`
	// The menu's parameter members
	ParamOids []string `protobuf:"bytes,4,rep,name=param_oids,json=paramOids,proto3" json:"param_oids,omitempty"`
	// The menu's command members
	CommandOids []string `protobuf:"bytes,5,rep,name=command_oids,json=commandOids,proto3" json:"command_oids,omitempty"`
	// Locator for a device specific custom user interface descriptor.
	// Additional properties to assist client including ui-url
	ClientHints map[string]string `protobuf:"bytes,6,rep,name=client_hints,json=clientHints,proto3" json:"client_hints,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The menu's display order
	Order         uint32 `protobuf:"varint,7,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Menu) Reset() {
	*x = Menu{}
	mi := &file_menu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Menu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Menu) ProtoMessage() {}

func (x *Menu) ProtoReflect() protoreflect.Message {
	mi := &file_menu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Menu.ProtoReflect.Descriptor instead.
func (*Menu) Descriptor() ([]byte, []int) {
	return file_menu_proto_rawDescGZIP(), []int{0}
}

func (x *Menu) GetName() *PolyglotText {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Menu) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *Menu) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *Menu) GetParamOids() []string {
	if x != nil {
		return x.ParamOids
	}
	return nil
}

func (x *Menu) GetCommandOids() []string {
	if x != nil {
		return x.CommandOids
	}
	return nil
}

func (x *Menu) GetClientHints() map[string]string {
	if x != nil {
		return x.ClientHints
	}
	return nil
}

func (x *Menu) GetOrder() uint32 {
	if x != nil {
		return x.Order
	}
	return 0
}

// A group of 'theme' related menus.
type MenuGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the menu group for display in client GUI
	Name *PolyglotText `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The menus in the group
	Menus map[string]*Menu `protobuf:"bytes,2,rep,name=menus,proto3" json:"menus,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The menu group's display order
	Order         uint32 `protobuf:"varint,3,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuGroup) Reset() {
	*x = MenuGroup{}
	mi := &file_menu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuGroup) ProtoMessage() {}

func (x *MenuGroup) ProtoReflect() protoreflect.Message {
	mi := &file_menu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuGroup.ProtoReflect.Descriptor instead.
func (*MenuGroup) Descriptor() ([]byte, []int) {
	return file_menu_proto_rawDescGZIP(), []int{1}
}

func (x *MenuGroup) GetName() *PolyglotText {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *MenuGroup) GetMenus() map[string]*Menu {
	if x != nil {
		return x.Menus
	}
	return nil
}

func (x *MenuGroup) GetOrder() uint32 {
	if x != nil {
		return x.Order
	}
	return 0
}

var File_menu_proto protoreflect.FileDescriptor

const file_menu_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"menu.proto\x12\x06st2138\x1a\x0elanguage.proto\"\xbe\x02\n" +
	"\x04Menu\x12(\n" +
	"\x04name\x18\x01 \x01(\v2\x14.st2138.PolyglotTextR\x04name\x12\x16\n" +
	"\x06hidden\x18\x02 \x01(\bR\x06hidden\x12\x1a\n" +
	"\bdisabled\x18\x03 \x01(\bR\bdisabled\x12\x1d\n" +
	"\n" +
	"param_oids\x18\x04 \x03(\tR\tparamOids\x12!\n" +
	"\fcommand_oids\x18\x05 \x03(\tR\vcommandOids\x12@\n" +
	"\fclient_hints\x18\x06 \x03(\v2\x1d.st2138.Menu.ClientHintsEntryR\vclientHints\x12\x14\n" +
	"\x05order\x18\a \x01(\rR\x05order\x1a>\n" +
	"\x10ClientHintsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc7\x01\n" +
	"\tMenuGroup\x12(\n" +
	"\x04name\x18\x01 \x01(\v2\x14.st2138.PolyglotTextR\x04name\x122\n" +
	"\x05menus\x18\x02 \x03(\v2\x1c.st2138.MenuGroup.MenusEntryR\x05menus\x12\x14\n" +
	"\x05order\x18\x03 \x01(\rR\x05order\x1aF\n" +
	"\n" +
	"MenusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\"\n" +
	"\x05value\x18\x02 \x01(\v2\f.st2138.MenuR\x05value:\x028\x01B\"\n" +
	"\x10catena.core.menuB\n" +
	"MenuProtosH\x01P\x01b\x06proto3"

var (
	file_menu_proto_rawDescOnce sync.Once
	file_menu_proto_rawDescData []byte
)

func file_menu_proto_rawDescGZIP() []byte {
	file_menu_proto_rawDescOnce.Do(func() {
		file_menu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_menu_proto_rawDesc), len(file_menu_proto_rawDesc)))
	})
	return file_menu_proto_rawDescData
}

var file_menu_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_menu_proto_goTypes = []any{
	(*Menu)(nil),         // 0: st2138.Menu
	(*MenuGroup)(nil),    // 1: st2138.MenuGroup
	nil,                  // 2: st2138.Menu.ClientHintsEntry
	nil,                  // 3: st2138.MenuGroup.MenusEntry
	(*PolyglotText)(nil), // 4: st2138.PolyglotText
}
var file_menu_proto_depIdxs = []int32{
	4, // 0: st2138.Menu.name:type_name -> st2138.PolyglotText
	2, // 1: st2138.Menu.client_hints:type_name -> st2138.Menu.ClientHintsEntry
	4, // 2: st2138.MenuGroup.name:type_name -> st2138.PolyglotText
	3, // 3: st2138.MenuGroup.menus:type_name -> st2138.MenuGroup.MenusEntry
	0, // 4: st2138.MenuGroup.MenusEntry.value:type_name -> st2138.Menu
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_menu_proto_init() }
func file_menu_proto_init() {
	if File_menu_proto != nil {
		return
	}
	file_language_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_menu_proto_rawDesc), len(file_menu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_menu_proto_goTypes,
		DependencyIndexes: file_menu_proto_depIdxs,
		MessageInfos:      file_menu_proto_msgTypes,
	}.Build()
	File_menu_proto = out.File
	file_menu_proto_goTypes = nil
	file_menu_proto_depIdxs = nil
}
