//
// Copyright (c) by the Society of Motion Picture and Television Engineers
//
// Redistribution and use in source and binary forms, with or without modification,
// are permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice, this
// list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice,
// this list of conditions and the following disclaimer in the documentation and/or
// other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its contributors
// may be used to endorse or promote products derived from this software without
// specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
// ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
// ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: param.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParamType int32

const (
	ParamType_UNDEFINED            ParamType = 0
	ParamType_EMPTY                ParamType = 1
	ParamType_INT32                ParamType = 4
	ParamType_FLOAT32              ParamType = 6
	ParamType_STRING               ParamType = 7
	ParamType_STRUCT               ParamType = 10
	ParamType_STRUCT_VARIANT       ParamType = 11
	ParamType_INT32_ARRAY          ParamType = 14
	ParamType_FLOAT32_ARRAY        ParamType = 16
	ParamType_STRING_ARRAY         ParamType = 17
	ParamType_BINARY               ParamType = 18
	ParamType_STRUCT_ARRAY         ParamType = 32
	ParamType_STRUCT_VARIANT_ARRAY ParamType = 33
	ParamType_DATA                 ParamType = 50 // Used to allow commands to accept files
)

// Enum value maps for ParamType.
var (
	ParamType_name = map[int32]string{
		0:  "UNDEFINED",
		1:  "EMPTY",
		4:  "INT32",
		6:  "FLOAT32",
		7:  "STRING",
		10: "STRUCT",
		11: "STRUCT_VARIANT",
		14: "INT32_ARRAY",
		16: "FLOAT32_ARRAY",
		17: "STRING_ARRAY",
		18: "BINARY",
		32: "STRUCT_ARRAY",
		33: "STRUCT_VARIANT_ARRAY",
		50: "DATA",
	}
	ParamType_value = map[string]int32{
		"UNDEFINED":            0,
		"EMPTY":                1,
		"INT32":                4,
		"FLOAT32":              6,
		"STRING":               7,
		"STRUCT":               10,
		"STRUCT_VARIANT":       11,
		"INT32_ARRAY":          14,
		"FLOAT32_ARRAY":        16,
		"STRING_ARRAY":         17,
		"BINARY":               18,
		"STRUCT_ARRAY":         32,
		"STRUCT_VARIANT_ARRAY": 33,
		"DATA":                 50,
	}
)

func (x ParamType) Enum() *ParamType {
	p := new(ParamType)
	*p = x
	return p
}

func (x ParamType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParamType) Descriptor() protoreflect.EnumDescriptor {
	return file_param_proto_enumTypes[0].Descriptor()
}

func (ParamType) Type() protoreflect.EnumType {
	return &file_param_proto_enumTypes[0]
}

func (x ParamType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParamType.Descriptor instead.
func (ParamType) EnumDescriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{0}
}

type UndefinedValue int32

const (
	UndefinedValue_UNDEFINED_VALUE UndefinedValue = 0
)

// Enum value maps for UndefinedValue.
var (
	UndefinedValue_name = map[int32]string{
		0: "UNDEFINED_VALUE",
	}
	UndefinedValue_value = map[string]int32{
		"UNDEFINED_VALUE": 0,
	}
)

func (x UndefinedValue) Enum() *UndefinedValue {
	p := new(UndefinedValue)
	*p = x
	return p
}

func (x UndefinedValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UndefinedValue) Descriptor() protoreflect.EnumDescriptor {
	return file_param_proto_enumTypes[1].Descriptor()
}

func (UndefinedValue) Type() protoreflect.EnumType {
	return &file_param_proto_enumTypes[1]
}

func (x UndefinedValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UndefinedValue.Descriptor instead.
func (UndefinedValue) EnumDescriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{1}
}

type DataPayload_PayloadEncoding int32

const (
	DataPayload_UNCOMPRESSED DataPayload_PayloadEncoding = 0
	DataPayload_GZIP         DataPayload_PayloadEncoding = 1
	DataPayload_DEFLATE      DataPayload_PayloadEncoding = 2
)

// Enum value maps for DataPayload_PayloadEncoding.
var (
	DataPayload_PayloadEncoding_name = map[int32]string{
		0: "UNCOMPRESSED",
		1: "GZIP",
		2: "DEFLATE",
	}
	DataPayload_PayloadEncoding_value = map[string]int32{
		"UNCOMPRESSED": 0,
		"GZIP":         1,
		"DEFLATE":      2,
	}
)

func (x DataPayload_PayloadEncoding) Enum() *DataPayload_PayloadEncoding {
	p := new(DataPayload_PayloadEncoding)
	*p = x
	return p
}

func (x DataPayload_PayloadEncoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataPayload_PayloadEncoding) Descriptor() protoreflect.EnumDescriptor {
	return file_param_proto_enumTypes[2].Descriptor()
}

func (DataPayload_PayloadEncoding) Type() protoreflect.EnumType {
	return &file_param_proto_enumTypes[2]
}

func (x DataPayload_PayloadEncoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataPayload_PayloadEncoding.Descriptor instead.
func (DataPayload_PayloadEncoding) EnumDescriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{1, 0}
}

type ParamInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The parameter's OID
	Oid string `protobuf:"bytes,1,opt,name=oid,proto3" json:"oid,omitempty"`
	// The parameter's name to display in a client GUI
	Name *PolyglotText `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The parameter's type
	Type ParamType `protobuf:"varint,3,opt,name=type,proto3,enum=st2138.ParamType" json:"type,omitempty"`
	// The OID of the template from which this parameter was created
	TemplateOid   string `protobuf:"bytes,4,opt,name=template_oid,json=templateOid,proto3" json:"template_oid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamInfo) Reset() {
	*x = ParamInfo{}
	mi := &file_param_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamInfo) ProtoMessage() {}

func (x *ParamInfo) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamInfo.ProtoReflect.Descriptor instead.
func (*ParamInfo) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{0}
}

func (x *ParamInfo) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

func (x *ParamInfo) GetName() *PolyglotText {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *ParamInfo) GetType() ParamType {
	if x != nil {
		return x.Type
	}
	return ParamType_UNDEFINED
}

func (x *ParamInfo) GetTemplateOid() string {
	if x != nil {
		return x.TemplateOid
	}
	return ""
}

// When streamed, only the payload field will be used after the first message.
type DataPayload struct {
	state           protoimpl.MessageState      `protogen:"open.v1"`
	Metadata        map[string]string           `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` //information about the payload to be interpreted by the client (e.g. mime-type, filename, etc.)
	Digest          []byte                      `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`                                                                               // SHA-256 digest of the payload - used to verify the integrity of the payload
	PayloadEncoding DataPayload_PayloadEncoding `protobuf:"varint,3,opt,name=payload_encoding,json=payloadEncoding,proto3,enum=st2138.DataPayload_PayloadEncoding" json:"payload_encoding,omitempty"`
	// Types that are valid to be assigned to Kind:
	//
	//	*DataPayload_Url
	//	*DataPayload_Payload
	Kind          isDataPayload_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPayload) Reset() {
	*x = DataPayload{}
	mi := &file_param_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPayload) ProtoMessage() {}

func (x *DataPayload) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPayload.ProtoReflect.Descriptor instead.
func (*DataPayload) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{1}
}

func (x *DataPayload) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DataPayload) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *DataPayload) GetPayloadEncoding() DataPayload_PayloadEncoding {
	if x != nil {
		return x.PayloadEncoding
	}
	return DataPayload_UNCOMPRESSED
}

func (x *DataPayload) GetKind() isDataPayload_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *DataPayload) GetUrl() string {
	if x != nil {
		if x, ok := x.Kind.(*DataPayload_Url); ok {
			return x.Url
		}
	}
	return ""
}

func (x *DataPayload) GetPayload() []byte {
	if x != nil {
		if x, ok := x.Kind.(*DataPayload_Payload); ok {
			return x.Payload
		}
	}
	return nil
}

type isDataPayload_Kind interface {
	isDataPayload_Kind()
}

type DataPayload_Url struct {
	Url string `protobuf:"bytes,4,opt,name=url,proto3,oneof"` // URL containing data for the payload
}

type DataPayload_Payload struct {
	Payload []byte `protobuf:"bytes,5,opt,name=payload,proto3,oneof"` // Data for the payload
}

func (*DataPayload_Url) isDataPayload_Kind() {}

func (*DataPayload_Payload) isDataPayload_Kind() {}

type Param struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the parameter's name
	Name *PolyglotText `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// the parameter's type
	Type ParamType `protobuf:"varint,2,opt,name=type,proto3,enum=st2138.ParamType" json:"type,omitempty"`
	// Read only flag. Clients shall style the param's widget as read only when true.
	ReadOnly bool `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	// Identifies the GUI elements to display and adjust the parameter value.
	Widget string `protobuf:"bytes,4,opt,name=widget,proto3" json:"widget,omitempty"`
	// For float params, how many digits to display
	Precision uint32 `protobuf:"varint,5,opt,name=precision,proto3" json:"precision,omitempty"`
	// The parameter's value
	Value *Value `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	// The constraint's on the parameters' value.
	// Can be a reference to a shared constraint or defined in-line.
	Constraint *Constraint `protobuf:"bytes,7,opt,name=constraint,proto3" json:"constraint,omitempty"`
	// For string params, the maximum length of the string
	// @todo - is this really needed? The proto encoding of strings includes their length
	MaxLength uint32 `protobuf:"varint,8,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"`
	// For string array params, the total length of all the strings in the array.
	// @todo - is this really needed? doesn't proto give us this info?
	TotalLength uint32 `protobuf:"varint,9,opt,name=total_length,json=totalLength,proto3" json:"total_length,omitempty"`
	// Access scope
	// if not present, the parameter's access scope is that of its parent.
	// if not a child parameter, the access scope is the default for the device.
	AccessScope string `protobuf:"bytes,10,opt,name=access_scope,json=accessScope,proto3" json:"access_scope,omitempty"`
	// Additional properties to assist client
	ClientHints map[string]string `protobuf:"bytes,11,rep,name=client_hints,json=clientHints,proto3" json:"client_hints,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// If this is a STRUCT or STRUCT_ARRAY Param its sub-params are defined here.
	Params map[string]*Param `protobuf:"bytes,13,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Meaningful when this message is used as a command descriptor
	// true if the command provides a response when executed.
	Response bool `protobuf:"varint,14,opt,name=response,proto3" json:"response,omitempty"`
	// Optional additional information about the usage of the parameter
	Help *PolyglotText `protobuf:"bytes,15,opt,name=help,proto3" json:"help,omitempty"`
	// Import directive
	Import *Import `protobuf:"bytes,16,opt,name=import,proto3" json:"import,omitempty"`
	// Additional OIDs represented by this parameter - used to allow a client to locate a parameter that may have been moved or renamed.
	// The aliases must be fully-qualified.
	OidAliases []string `protobuf:"bytes,17,rep,name=oid_aliases,json=oidAliases,proto3" json:"oid_aliases,omitempty"`
	// When true, indicates that the parameter is part of the minimal set of parameters that should be reported by the device
	MinimalSet bool `protobuf:"varint,18,opt,name=minimal_set,json=minimalSet,proto3" json:"minimal_set,omitempty"`
	// When true, indicates that the parameter is stateless
	// design intent is to signal that values of stateless parameters are not worth persisting
	// and that the device should not be expected to remember them across reboots.
	// Good examples of stateless parameters are: device's current time, audio meters, etc.
	Stateless bool `protobuf:"varint,19,opt,name=stateless,proto3" json:"stateless,omitempty"`
	// The OID of the template from which this parameter was created
	TemplateOid   string `protobuf:"bytes,20,opt,name=template_oid,json=templateOid,proto3" json:"template_oid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Param) Reset() {
	*x = Param{}
	mi := &file_param_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Param) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Param) ProtoMessage() {}

func (x *Param) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Param.ProtoReflect.Descriptor instead.
func (*Param) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{2}
}

func (x *Param) GetName() *PolyglotText {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Param) GetType() ParamType {
	if x != nil {
		return x.Type
	}
	return ParamType_UNDEFINED
}

func (x *Param) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *Param) GetWidget() string {
	if x != nil {
		return x.Widget
	}
	return ""
}

func (x *Param) GetPrecision() uint32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *Param) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Param) GetConstraint() *Constraint {
	if x != nil {
		return x.Constraint
	}
	return nil
}

func (x *Param) GetMaxLength() uint32 {
	if x != nil {
		return x.MaxLength
	}
	return 0
}

func (x *Param) GetTotalLength() uint32 {
	if x != nil {
		return x.TotalLength
	}
	return 0
}

func (x *Param) GetAccessScope() string {
	if x != nil {
		return x.AccessScope
	}
	return ""
}

func (x *Param) GetClientHints() map[string]string {
	if x != nil {
		return x.ClientHints
	}
	return nil
}

func (x *Param) GetParams() map[string]*Param {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Param) GetResponse() bool {
	if x != nil {
		return x.Response
	}
	return false
}

func (x *Param) GetHelp() *PolyglotText {
	if x != nil {
		return x.Help
	}
	return nil
}

func (x *Param) GetImport() *Import {
	if x != nil {
		return x.Import
	}
	return nil
}

func (x *Param) GetOidAliases() []string {
	if x != nil {
		return x.OidAliases
	}
	return nil
}

func (x *Param) GetMinimalSet() bool {
	if x != nil {
		return x.MinimalSet
	}
	return false
}

func (x *Param) GetStateless() bool {
	if x != nil {
		return x.Stateless
	}
	return false
}

func (x *Param) GetTemplateOid() string {
	if x != nil {
		return x.TemplateOid
	}
	return ""
}

// A value that can be one of several types, even within the same array
// The type to apply is determined by the struct_variant_type field which must match one
// of the keys in the descriptor's params map
type StructVariantValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of the variant
	StructVariantType string `protobuf:"bytes,1,opt,name=struct_variant_type,json=structVariantType,proto3" json:"struct_variant_type,omitempty"`
	// The value of the variant
	Value         *Value `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StructVariantValue) Reset() {
	*x = StructVariantValue{}
	mi := &file_param_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StructVariantValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructVariantValue) ProtoMessage() {}

func (x *StructVariantValue) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructVariantValue.ProtoReflect.Descriptor instead.
func (*StructVariantValue) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{3}
}

func (x *StructVariantValue) GetStructVariantType() string {
	if x != nil {
		return x.StructVariantType
	}
	return ""
}

func (x *StructVariantValue) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

// An array of Values, each of which can be one of several types defined in the
// descriptor's params map
type StructVariantList struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StructVariants []*StructVariantValue  `protobuf:"bytes,1,rep,name=struct_variants,json=structVariants,proto3" json:"struct_variants,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StructVariantList) Reset() {
	*x = StructVariantList{}
	mi := &file_param_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StructVariantList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructVariantList) ProtoMessage() {}

func (x *StructVariantList) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructVariantList.ProtoReflect.Descriptor instead.
func (*StructVariantList) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{4}
}

func (x *StructVariantList) GetStructVariants() []*StructVariantValue {
	if x != nil {
		return x.StructVariants
	}
	return nil
}

type Int32List struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ints          []int32                `protobuf:"fixed32,1,rep,packed,name=ints,proto3" json:"ints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Int32List) Reset() {
	*x = Int32List{}
	mi := &file_param_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int32List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int32List) ProtoMessage() {}

func (x *Int32List) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int32List.ProtoReflect.Descriptor instead.
func (*Int32List) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{5}
}

func (x *Int32List) GetInts() []int32 {
	if x != nil {
		return x.Ints
	}
	return nil
}

type Float32List struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Floats        []float32              `protobuf:"fixed32,1,rep,packed,name=floats,proto3" json:"floats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Float32List) Reset() {
	*x = Float32List{}
	mi := &file_param_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Float32List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Float32List) ProtoMessage() {}

func (x *Float32List) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Float32List.ProtoReflect.Descriptor instead.
func (*Float32List) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{6}
}

func (x *Float32List) GetFloats() []float32 {
	if x != nil {
		return x.Floats
	}
	return nil
}

type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strings       []string               `protobuf:"bytes,1,rep,name=strings,proto3" json:"strings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_param_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{7}
}

func (x *StringList) GetStrings() []string {
	if x != nil {
		return x.Strings
	}
	return nil
}

// Structured object comprising named fields that map to dynamically typed values
type StructValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        map[string]*Value      `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StructValue) Reset() {
	*x = StructValue{}
	mi := &file_param_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StructValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructValue) ProtoMessage() {}

func (x *StructValue) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructValue.ProtoReflect.Descriptor instead.
func (*StructValue) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{8}
}

func (x *StructValue) GetFields() map[string]*Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_param_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{9}
}

type StructList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StructValues  []*StructValue         `protobuf:"bytes,1,rep,name=struct_values,json=structValues,proto3" json:"struct_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StructList) Reset() {
	*x = StructList{}
	mi := &file_param_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StructList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructList) ProtoMessage() {}

func (x *StructList) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructList.ProtoReflect.Descriptor instead.
func (*StructList) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{10}
}

func (x *StructList) GetStructValues() []*StructValue {
	if x != nil {
		return x.StructValues
	}
	return nil
}

// Represents a dynamically typed value with straightforward mapping to
// OGP/JSON.
// Note that sfixed32 types are used to prefer marshalling performance
// to wire size.
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Value_UndefinedValue
	//	*Value_EmptyValue
	//	*Value_Int32Value
	//	*Value_Float32Value
	//	*Value_StringValue
	//	*Value_StructValue
	//	*Value_Int32ArrayValues
	//	*Value_Float32ArrayValues
	//	*Value_StringArrayValues
	//	*Value_StructArrayValues
	//	*Value_DataPayload
	//	*Value_StructVariantValue
	//	*Value_StructVariantArrayValues
	Kind          isValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_param_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{11}
}

func (x *Value) GetKind() isValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Value) GetUndefinedValue() UndefinedValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_UndefinedValue); ok {
			return x.UndefinedValue
		}
	}
	return UndefinedValue_UNDEFINED_VALUE
}

func (x *Value) GetEmptyValue() *Empty {
	if x != nil {
		if x, ok := x.Kind.(*Value_EmptyValue); ok {
			return x.EmptyValue
		}
	}
	return nil
}

func (x *Value) GetInt32Value() int32 {
	if x != nil {
		if x, ok := x.Kind.(*Value_Int32Value); ok {
			return x.Int32Value
		}
	}
	return 0
}

func (x *Value) GetFloat32Value() float32 {
	if x != nil {
		if x, ok := x.Kind.(*Value_Float32Value); ok {
			return x.Float32Value
		}
	}
	return 0
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Value) GetStructValue() *StructValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_StructValue); ok {
			return x.StructValue
		}
	}
	return nil
}

func (x *Value) GetInt32ArrayValues() *Int32List {
	if x != nil {
		if x, ok := x.Kind.(*Value_Int32ArrayValues); ok {
			return x.Int32ArrayValues
		}
	}
	return nil
}

func (x *Value) GetFloat32ArrayValues() *Float32List {
	if x != nil {
		if x, ok := x.Kind.(*Value_Float32ArrayValues); ok {
			return x.Float32ArrayValues
		}
	}
	return nil
}

func (x *Value) GetStringArrayValues() *StringList {
	if x != nil {
		if x, ok := x.Kind.(*Value_StringArrayValues); ok {
			return x.StringArrayValues
		}
	}
	return nil
}

func (x *Value) GetStructArrayValues() *StructList {
	if x != nil {
		if x, ok := x.Kind.(*Value_StructArrayValues); ok {
			return x.StructArrayValues
		}
	}
	return nil
}

func (x *Value) GetDataPayload() *DataPayload {
	if x != nil {
		if x, ok := x.Kind.(*Value_DataPayload); ok {
			return x.DataPayload
		}
	}
	return nil
}

func (x *Value) GetStructVariantValue() *StructVariantValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_StructVariantValue); ok {
			return x.StructVariantValue
		}
	}
	return nil
}

func (x *Value) GetStructVariantArrayValues() *StructVariantList {
	if x != nil {
		if x, ok := x.Kind.(*Value_StructVariantArrayValues); ok {
			return x.StructVariantArrayValues
		}
	}
	return nil
}

type isValue_Kind interface {
	isValue_Kind()
}

type Value_UndefinedValue struct {
	UndefinedValue UndefinedValue `protobuf:"varint,1,opt,name=undefined_value,json=undefinedValue,proto3,enum=st2138.UndefinedValue,oneof"`
}

type Value_EmptyValue struct {
	EmptyValue *Empty `protobuf:"bytes,2,opt,name=empty_value,json=emptyValue,proto3,oneof"` // Used for zero-argument commands
}

type Value_Int32Value struct {
	Int32Value int32 `protobuf:"fixed32,3,opt,name=int32_value,json=int32Value,proto3,oneof"`
}

type Value_Float32Value struct {
	Float32Value float32 `protobuf:"fixed32,4,opt,name=float32_value,json=float32Value,proto3,oneof"`
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,5,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_StructValue struct {
	StructValue *StructValue `protobuf:"bytes,6,opt,name=struct_value,json=structValue,proto3,oneof"`
}

type Value_Int32ArrayValues struct {
	Int32ArrayValues *Int32List `protobuf:"bytes,7,opt,name=int32_array_values,json=int32ArrayValues,proto3,oneof"`
}

type Value_Float32ArrayValues struct {
	Float32ArrayValues *Float32List `protobuf:"bytes,8,opt,name=float32_array_values,json=float32ArrayValues,proto3,oneof"`
}

type Value_StringArrayValues struct {
	StringArrayValues *StringList `protobuf:"bytes,9,opt,name=string_array_values,json=stringArrayValues,proto3,oneof"`
}

type Value_StructArrayValues struct {
	StructArrayValues *StructList `protobuf:"bytes,10,opt,name=struct_array_values,json=structArrayValues,proto3,oneof"`
}

type Value_DataPayload struct {
	DataPayload *DataPayload `protobuf:"bytes,11,opt,name=data_payload,json=dataPayload,proto3,oneof"` // Used for commands that accept or return data blobs
}

type Value_StructVariantValue struct {
	StructVariantValue *StructVariantValue `protobuf:"bytes,12,opt,name=struct_variant_value,json=structVariantValue,proto3,oneof"`
}

type Value_StructVariantArrayValues struct {
	StructVariantArrayValues *StructVariantList `protobuf:"bytes,13,opt,name=struct_variant_array_values,json=structVariantArrayValues,proto3,oneof"`
}

func (*Value_UndefinedValue) isValue_Kind() {}

func (*Value_EmptyValue) isValue_Kind() {}

func (*Value_Int32Value) isValue_Kind() {}

func (*Value_Float32Value) isValue_Kind() {}

func (*Value_StringValue) isValue_Kind() {}

func (*Value_StructValue) isValue_Kind() {}

func (*Value_Int32ArrayValues) isValue_Kind() {}

func (*Value_Float32ArrayValues) isValue_Kind() {}

func (*Value_StringArrayValues) isValue_Kind() {}

func (*Value_StructArrayValues) isValue_Kind() {}

func (*Value_DataPayload) isValue_Kind() {}

func (*Value_StructVariantValue) isValue_Kind() {}

func (*Value_StructVariantArrayValues) isValue_Kind() {}

type Import struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Digest        string                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"` // SHA256 digest of the import file
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Import) Reset() {
	*x = Import{}
	mi := &file_param_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Import) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Import) ProtoMessage() {}

func (x *Import) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Import.ProtoReflect.Descriptor instead.
func (*Import) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{12}
}

func (x *Import) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Import) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

type GetParamPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint32                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"` // Uniquely identifies the device at node scope.
	Oid           string                 `protobuf:"bytes,2,opt,name=oid,proto3" json:"oid,omitempty"`    // Uniquely identifies the param at device scope
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParamPayload) Reset() {
	*x = GetParamPayload{}
	mi := &file_param_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParamPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParamPayload) ProtoMessage() {}

func (x *GetParamPayload) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParamPayload.ProtoReflect.Descriptor instead.
func (*GetParamPayload) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{13}
}

func (x *GetParamPayload) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *GetParamPayload) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

type ParamInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *ParamInfo             `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	ArrayLength   uint32                 `protobuf:"varint,2,opt,name=array_length,json=arrayLength,proto3" json:"array_length,omitempty"` // If this ParamInfoResponse is for an array parameter, include the length of the array
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamInfoResponse) Reset() {
	*x = ParamInfoResponse{}
	mi := &file_param_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamInfoResponse) ProtoMessage() {}

func (x *ParamInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamInfoResponse.ProtoReflect.Descriptor instead.
func (*ParamInfoResponse) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{14}
}

func (x *ParamInfoResponse) GetInfo() *ParamInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *ParamInfoResponse) GetArrayLength() uint32 {
	if x != nil {
		return x.ArrayLength
	}
	return 0
}

// Specifies the OID and potentially its subtree of
// child parameters if the recursive flag is set.
type ParamInfoRequestPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Slot  uint32                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"` // Uniquely identifies the device at node scope.
	// Uniquely identifies starting parameter relative to device.params
	// Specifying "" selects all top-level parameters.
	OidPrefix string `protobuf:"bytes,2,opt,name=oid_prefix,json=oidPrefix,proto3" json:"oid_prefix,omitempty"`
	// Selects whether the param's child parameters should also be returned.
	Recursive     bool `protobuf:"varint,3,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamInfoRequestPayload) Reset() {
	*x = ParamInfoRequestPayload{}
	mi := &file_param_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamInfoRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamInfoRequestPayload) ProtoMessage() {}

func (x *ParamInfoRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamInfoRequestPayload.ProtoReflect.Descriptor instead.
func (*ParamInfoRequestPayload) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{15}
}

func (x *ParamInfoRequestPayload) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *ParamInfoRequestPayload) GetOidPrefix() string {
	if x != nil {
		return x.OidPrefix
	}
	return ""
}

func (x *ParamInfoRequestPayload) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type SetValuePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Oid           string                 `protobuf:"bytes,1,opt,name=oid,proto3" json:"oid,omitempty"`     // Uniquely identifies the param at device scope
	Value         *Value                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"` // The value to apply
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetValuePayload) Reset() {
	*x = SetValuePayload{}
	mi := &file_param_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetValuePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetValuePayload) ProtoMessage() {}

func (x *SetValuePayload) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetValuePayload.ProtoReflect.Descriptor instead.
func (*SetValuePayload) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{16}
}

func (x *SetValuePayload) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

func (x *SetValuePayload) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type SingleSetValuePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint32                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`  // Uniquely identifies the device at node scope.
	Value         *SetValuePayload       `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // The param oid and value to apply
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleSetValuePayload) Reset() {
	*x = SingleSetValuePayload{}
	mi := &file_param_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleSetValuePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleSetValuePayload) ProtoMessage() {}

func (x *SingleSetValuePayload) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleSetValuePayload.ProtoReflect.Descriptor instead.
func (*SingleSetValuePayload) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{17}
}

func (x *SingleSetValuePayload) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *SingleSetValuePayload) GetValue() *SetValuePayload {
	if x != nil {
		return x.Value
	}
	return nil
}

type GetValuePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint32                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"` // Uniquely identifies the device at node scope.
	Oid           string                 `protobuf:"bytes,2,opt,name=oid,proto3" json:"oid,omitempty"`    // Uniquely identifies the param at device scope
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValuePayload) Reset() {
	*x = GetValuePayload{}
	mi := &file_param_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValuePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValuePayload) ProtoMessage() {}

func (x *GetValuePayload) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValuePayload.ProtoReflect.Descriptor instead.
func (*GetValuePayload) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{18}
}

func (x *GetValuePayload) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *GetValuePayload) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

type MultiSetValuePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint32                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`    // Uniquely identifies the device at node scope.
	Values        []*SetValuePayload     `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"` // The param oids and values to apply
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiSetValuePayload) Reset() {
	*x = MultiSetValuePayload{}
	mi := &file_param_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiSetValuePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiSetValuePayload) ProtoMessage() {}

func (x *MultiSetValuePayload) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiSetValuePayload.ProtoReflect.Descriptor instead.
func (*MultiSetValuePayload) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{19}
}

func (x *MultiSetValuePayload) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *MultiSetValuePayload) GetValues() []*SetValuePayload {
	if x != nil {
		return x.Values
	}
	return nil
}

type UpdateSubscriptionsPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint32                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`                                 // Uniquely identifies the device at node scope.
	AddedOids     []string               `protobuf:"bytes,2,rep,name=added_oids,json=addedOids,proto3" json:"added_oids,omitempty"`       // A list of object IDs to add to current subscriptions (or a partial OID with a trailing "*" to indicate all object IDs with the same prefix)
	RemovedOids   []string               `protobuf:"bytes,3,rep,name=removed_oids,json=removedOids,proto3" json:"removed_oids,omitempty"` // A list of object IDs to remove from current subscriptions (or a partial OID with a trailing "*" to indicate all object IDs with the same prefix)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSubscriptionsPayload) Reset() {
	*x = UpdateSubscriptionsPayload{}
	mi := &file_param_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSubscriptionsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSubscriptionsPayload) ProtoMessage() {}

func (x *UpdateSubscriptionsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSubscriptionsPayload.ProtoReflect.Descriptor instead.
func (*UpdateSubscriptionsPayload) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateSubscriptionsPayload) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *UpdateSubscriptionsPayload) GetAddedOids() []string {
	if x != nil {
		return x.AddedOids
	}
	return nil
}

func (x *UpdateSubscriptionsPayload) GetRemovedOids() []string {
	if x != nil {
		return x.RemovedOids
	}
	return nil
}

// Defines a command for a device.
// Commands provide a way to use device connection to execute commands from other devices.
// Superseded by just adding a `respond` field to the Param message.
//
//	message Command {
//	  Param definition = 1; // provides command's input values
//	  bool respond = 2;     // true when the device will respond to the command, false otherwise.
//	}
//
// When streamed, only the value field will be used after the first message.
//
// The proceed flag allows the client to indicate to the server that is has already recieved a payload
// Ex. If a command streams a large file, the client can set proceed to false to indicate to the server
// that it does not need the rest of the file.
type ExecuteCommandPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint32                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`       // Slot id of the device
	Oid           string                 `protobuf:"bytes,2,opt,name=oid,proto3" json:"oid,omitempty"`          // The object id of the command to execute relative to device.commands
	Value         *Value                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`      // The command's parameter value, if any
	Respond       bool                   `protobuf:"varint,4,opt,name=respond,proto3" json:"respond,omitempty"` // False if client wants to surpress response from server
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteCommandPayload) Reset() {
	*x = ExecuteCommandPayload{}
	mi := &file_param_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCommandPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommandPayload) ProtoMessage() {}

func (x *ExecuteCommandPayload) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommandPayload.ProtoReflect.Descriptor instead.
func (*ExecuteCommandPayload) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{21}
}

func (x *ExecuteCommandPayload) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *ExecuteCommandPayload) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

func (x *ExecuteCommandPayload) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ExecuteCommandPayload) GetRespond() bool {
	if x != nil {
		return x.Respond
	}
	return false
}

type Exception struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	ErrorMessage  *PolyglotText          `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Details       string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exception) Reset() {
	*x = Exception{}
	mi := &file_param_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exception) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exception) ProtoMessage() {}

func (x *Exception) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exception.ProtoReflect.Descriptor instead.
func (*Exception) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{22}
}

func (x *Exception) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Exception) GetErrorMessage() *PolyglotText {
	if x != nil {
		return x.ErrorMessage
	}
	return nil
}

func (x *Exception) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

// When streamed, only the response field will be used after the first message.
type CommandResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*CommandResponse_NoResponse
	//	*CommandResponse_Response
	//	*CommandResponse_Exception
	Kind          isCommandResponse_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_param_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{23}
}

func (x *CommandResponse) GetKind() isCommandResponse_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *CommandResponse) GetNoResponse() *Empty {
	if x != nil {
		if x, ok := x.Kind.(*CommandResponse_NoResponse); ok {
			return x.NoResponse
		}
	}
	return nil
}

func (x *CommandResponse) GetResponse() *Value {
	if x != nil {
		if x, ok := x.Kind.(*CommandResponse_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *CommandResponse) GetException() *Exception {
	if x != nil {
		if x, ok := x.Kind.(*CommandResponse_Exception); ok {
			return x.Exception
		}
	}
	return nil
}

type isCommandResponse_Kind interface {
	isCommandResponse_Kind()
}

type CommandResponse_NoResponse struct {
	NoResponse *Empty `protobuf:"bytes,1,opt,name=no_response,json=noResponse,proto3,oneof"` // Server/Device does not have a response for the command.
}

type CommandResponse_Response struct {
	Response *Value `protobuf:"bytes,2,opt,name=response,proto3,oneof"`
}

type CommandResponse_Exception struct {
	Exception *Exception `protobuf:"bytes,3,opt,name=exception,proto3,oneof"` // This is for Server/Device error executing the command.
}

func (*CommandResponse_NoResponse) isCommandResponse_Kind() {}

func (*CommandResponse_Response) isCommandResponse_Kind() {}

func (*CommandResponse_Exception) isCommandResponse_Kind() {}

var File_param_proto protoreflect.FileDescriptor

const file_param_proto_rawDesc = "" +
	"\n" +
	"\vparam.proto\x12\x06st2138\x1a\x0elanguage.proto\x1a\x10constraint.proto\"\x91\x01\n" +
	"\tParamInfo\x12\x10\n" +
	"\x03oid\x18\x01 \x01(\tR\x03oid\x12(\n" +
	"\x04name\x18\x02 \x01(\v2\x14.st2138.PolyglotTextR\x04name\x12%\n" +
	"\x04type\x18\x03 \x01(\x0e2\x11.st2138.ParamTypeR\x04type\x12!\n" +
	"\ftemplate_oid\x18\x04 \x01(\tR\vtemplateOid\"\xe5\x02\n" +
	"\vDataPayload\x12=\n" +
	"\bmetadata\x18\x01 \x03(\v2!.st2138.DataPayload.MetadataEntryR\bmetadata\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\fR\x06digest\x12N\n" +
	"\x10payload_encoding\x18\x03 \x01(\x0e2#.st2138.DataPayload.PayloadEncodingR\x0fpayloadEncoding\x12\x12\n" +
	"\x03url\x18\x04 \x01(\tH\x00R\x03url\x12\x1a\n" +
	"\apayload\x18\x05 \x01(\fH\x00R\apayload\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\x0fPayloadEncoding\x12\x10\n" +
	"\fUNCOMPRESSED\x10\x00\x12\b\n" +
	"\x04GZIP\x10\x01\x12\v\n" +
	"\aDEFLATE\x10\x02B\x06\n" +
	"\x04kind\"\xda\x06\n" +
	"\x05Param\x12(\n" +
	"\x04name\x18\x01 \x01(\v2\x14.st2138.PolyglotTextR\x04name\x12%\n" +
	"\x04type\x18\x02 \x01(\x0e2\x11.st2138.ParamTypeR\x04type\x12\x1b\n" +
	"\tread_only\x18\x03 \x01(\bR\breadOnly\x12\x16\n" +
	"\x06widget\x18\x04 \x01(\tR\x06widget\x12\x1c\n" +
	"\tprecision\x18\x05 \x01(\rR\tprecision\x12#\n" +
	"\x05value\x18\x06 \x01(\v2\r.st2138.ValueR\x05value\x122\n" +
	"\n" +
	"constraint\x18\a \x01(\v2\x12.st2138.ConstraintR\n" +
	"constraint\x12\x1d\n" +
	"\n" +
	"max_length\x18\b \x01(\rR\tmaxLength\x12!\n" +
	"\ftotal_length\x18\t \x01(\rR\vtotalLength\x12!\n" +
	"\faccess_scope\x18\n" +
	" \x01(\tR\vaccessScope\x12A\n" +
	"\fclient_hints\x18\v \x03(\v2\x1e.st2138.Param.ClientHintsEntryR\vclientHints\x121\n" +
	"\x06params\x18\r \x03(\v2\x19.st2138.Param.ParamsEntryR\x06params\x12\x1a\n" +
	"\bresponse\x18\x0e \x01(\bR\bresponse\x12(\n" +
	"\x04help\x18\x0f \x01(\v2\x14.st2138.PolyglotTextR\x04help\x12&\n" +
	"\x06import\x18\x10 \x01(\v2\x0e.st2138.ImportR\x06import\x12\x1f\n" +
	"\void_aliases\x18\x11 \x03(\tR\n" +
	"oidAliases\x12\x1f\n" +
	"\vminimal_set\x18\x12 \x01(\bR\n" +
	"minimalSet\x12\x1c\n" +
	"\tstateless\x18\x13 \x01(\bR\tstateless\x12!\n" +
	"\ftemplate_oid\x18\x14 \x01(\tR\vtemplateOid\x1a>\n" +
	"\x10ClientHintsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aH\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.st2138.ParamR\x05value:\x028\x01\"i\n" +
	"\x12StructVariantValue\x12.\n" +
	"\x13struct_variant_type\x18\x01 \x01(\tR\x11structVariantType\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.st2138.ValueR\x05value\"X\n" +
	"\x11StructVariantList\x12C\n" +
	"\x0fstruct_variants\x18\x01 \x03(\v2\x1a.st2138.StructVariantValueR\x0estructVariants\"\x1f\n" +
	"\tInt32List\x12\x12\n" +
	"\x04ints\x18\x01 \x03(\x0fR\x04ints\"%\n" +
	"\vFloat32List\x12\x16\n" +
	"\x06floats\x18\x01 \x03(\x02R\x06floats\"&\n" +
	"\n" +
	"StringList\x12\x18\n" +
	"\astrings\x18\x01 \x03(\tR\astrings\"\x90\x01\n" +
	"\vStructValue\x127\n" +
	"\x06fields\x18\x01 \x03(\v2\x1f.st2138.StructValue.FieldsEntryR\x06fields\x1aH\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.st2138.ValueR\x05value:\x028\x01\"\a\n" +
	"\x05Empty\"F\n" +
	"\n" +
	"StructList\x128\n" +
	"\rstruct_values\x18\x01 \x03(\v2\x13.st2138.StructValueR\fstructValues\"\xab\x06\n" +
	"\x05Value\x12A\n" +
	"\x0fundefined_value\x18\x01 \x01(\x0e2\x16.st2138.UndefinedValueH\x00R\x0eundefinedValue\x120\n" +
	"\vempty_value\x18\x02 \x01(\v2\r.st2138.EmptyH\x00R\n" +
	"emptyValue\x12!\n" +
	"\vint32_value\x18\x03 \x01(\x0fH\x00R\n" +
	"int32Value\x12%\n" +
	"\rfloat32_value\x18\x04 \x01(\x02H\x00R\ffloat32Value\x12#\n" +
	"\fstring_value\x18\x05 \x01(\tH\x00R\vstringValue\x128\n" +
	"\fstruct_value\x18\x06 \x01(\v2\x13.st2138.StructValueH\x00R\vstructValue\x12A\n" +
	"\x12int32_array_values\x18\a \x01(\v2\x11.st2138.Int32ListH\x00R\x10int32ArrayValues\x12G\n" +
	"\x14float32_array_values\x18\b \x01(\v2\x13.st2138.Float32ListH\x00R\x12float32ArrayValues\x12D\n" +
	"\x13string_array_values\x18\t \x01(\v2\x12.st2138.StringListH\x00R\x11stringArrayValues\x12D\n" +
	"\x13struct_array_values\x18\n" +
	" \x01(\v2\x12.st2138.StructListH\x00R\x11structArrayValues\x128\n" +
	"\fdata_payload\x18\v \x01(\v2\x13.st2138.DataPayloadH\x00R\vdataPayload\x12N\n" +
	"\x14struct_variant_value\x18\f \x01(\v2\x1a.st2138.StructVariantValueH\x00R\x12structVariantValue\x12Z\n" +
	"\x1bstruct_variant_array_values\x18\r \x01(\v2\x19.st2138.StructVariantListH\x00R\x18structVariantArrayValuesB\x06\n" +
	"\x04kind\"2\n" +
	"\x06Import\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\"7\n" +
	"\x0fGetParamPayload\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\rR\x04slot\x12\x10\n" +
	"\x03oid\x18\x02 \x01(\tR\x03oid\"]\n" +
	"\x11ParamInfoResponse\x12%\n" +
	"\x04info\x18\x01 \x01(\v2\x11.st2138.ParamInfoR\x04info\x12!\n" +
	"\farray_length\x18\x02 \x01(\rR\varrayLength\"j\n" +
	"\x17ParamInfoRequestPayload\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\rR\x04slot\x12\x1d\n" +
	"\n" +
	"oid_prefix\x18\x02 \x01(\tR\toidPrefix\x12\x1c\n" +
	"\trecursive\x18\x03 \x01(\bR\trecursive\"H\n" +
	"\x0fSetValuePayload\x12\x10\n" +
	"\x03oid\x18\x01 \x01(\tR\x03oid\x12#\n" +
	"\x05value\x18\x03 \x01(\v2\r.st2138.ValueR\x05value\"Z\n" +
	"\x15SingleSetValuePayload\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\rR\x04slot\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.st2138.SetValuePayloadR\x05value\"7\n" +
	"\x0fGetValuePayload\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\rR\x04slot\x12\x10\n" +
	"\x03oid\x18\x02 \x01(\tR\x03oid\"[\n" +
	"\x14MultiSetValuePayload\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\rR\x04slot\x12/\n" +
	"\x06values\x18\x02 \x03(\v2\x17.st2138.SetValuePayloadR\x06values\"r\n" +
	"\x1aUpdateSubscriptionsPayload\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\rR\x04slot\x12\x1d\n" +
	"\n" +
	"added_oids\x18\x02 \x03(\tR\taddedOids\x12!\n" +
	"\fremoved_oids\x18\x03 \x03(\tR\vremovedOids\"|\n" +
	"\x15ExecuteCommandPayload\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\rR\x04slot\x12\x10\n" +
	"\x03oid\x18\x02 \x01(\tR\x03oid\x12#\n" +
	"\x05value\x18\x03 \x01(\v2\r.st2138.ValueR\x05value\x12\x18\n" +
	"\arespond\x18\x04 \x01(\bR\arespond\"t\n" +
	"\tException\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x129\n" +
	"\rerror_message\x18\x02 \x01(\v2\x14.st2138.PolyglotTextR\ferrorMessage\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\"\xab\x01\n" +
	"\x0fCommandResponse\x120\n" +
	"\vno_response\x18\x01 \x01(\v2\r.st2138.EmptyH\x00R\n" +
	"noResponse\x12+\n" +
	"\bresponse\x18\x02 \x01(\v2\r.st2138.ValueH\x00R\bresponse\x121\n" +
	"\texception\x18\x03 \x01(\v2\x11.st2138.ExceptionH\x00R\texceptionB\x06\n" +
	"\x04kind*\xe1\x01\n" +
	"\tParamType\x12\r\n" +
	"\tUNDEFINED\x10\x00\x12\t\n" +
	"\x05EMPTY\x10\x01\x12\t\n" +
	"\x05INT32\x10\x04\x12\v\n" +
	"\aFLOAT32\x10\x06\x12\n" +
	"\n" +
	"\x06STRING\x10\a\x12\n" +
	"\n" +
	"\x06STRUCT\x10\n" +
	"\x12\x12\n" +
	"\x0eSTRUCT_VARIANT\x10\v\x12\x0f\n" +
	"\vINT32_ARRAY\x10\x0e\x12\x11\n" +
	"\rFLOAT32_ARRAY\x10\x10\x12\x10\n" +
	"\fSTRING_ARRAY\x10\x11\x12\n" +
	"\n" +
	"\x06BINARY\x10\x12\x12\x10\n" +
	"\fSTRUCT_ARRAY\x10 \x12\x18\n" +
	"\x14STRUCT_VARIANT_ARRAY\x10!\x12\b\n" +
	"\x04DATA\x102*%\n" +
	"\x0eUndefinedValue\x12\x13\n" +
	"\x0fUNDEFINED_VALUE\x10\x00B(\n" +
	"\x15catena.core.parameterB\vParamProtosH\x01P\x01b\x06proto3"

var (
	file_param_proto_rawDescOnce sync.Once
	file_param_proto_rawDescData []byte
)

func file_param_proto_rawDescGZIP() []byte {
	file_param_proto_rawDescOnce.Do(func() {
		file_param_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_param_proto_rawDesc), len(file_param_proto_rawDesc)))
	})
	return file_param_proto_rawDescData
}

var file_param_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_param_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_param_proto_goTypes = []any{
	(ParamType)(0),                     // 0: st2138.ParamType
	(UndefinedValue)(0),                // 1: st2138.UndefinedValue
	(DataPayload_PayloadEncoding)(0),   // 2: st2138.DataPayload.PayloadEncoding
	(*ParamInfo)(nil),                  // 3: st2138.ParamInfo
	(*DataPayload)(nil),                // 4: st2138.DataPayload
	(*Param)(nil),                      // 5: st2138.Param
	(*StructVariantValue)(nil),         // 6: st2138.StructVariantValue
	(*StructVariantList)(nil),          // 7: st2138.StructVariantList
	(*Int32List)(nil),                  // 8: st2138.Int32List
	(*Float32List)(nil),                // 9: st2138.Float32List
	(*StringList)(nil),                 // 10: st2138.StringList
	(*StructValue)(nil),                // 11: st2138.StructValue
	(*Empty)(nil),                      // 12: st2138.Empty
	(*StructList)(nil),                 // 13: st2138.StructList
	(*Value)(nil),                      // 14: st2138.Value
	(*Import)(nil),                     // 15: st2138.Import
	(*GetParamPayload)(nil),            // 16: st2138.GetParamPayload
	(*ParamInfoResponse)(nil),          // 17: st2138.ParamInfoResponse
	(*ParamInfoRequestPayload)(nil),    // 18: st2138.ParamInfoRequestPayload
	(*SetValuePayload)(nil),            // 19: st2138.SetValuePayload
	(*SingleSetValuePayload)(nil),      // 20: st2138.SingleSetValuePayload
	(*GetValuePayload)(nil),            // 21: st2138.GetValuePayload
	(*MultiSetValuePayload)(nil),       // 22: st2138.MultiSetValuePayload
	(*UpdateSubscriptionsPayload)(nil), // 23: st2138.UpdateSubscriptionsPayload
	(*ExecuteCommandPayload)(nil),      // 24: st2138.ExecuteCommandPayload
	(*Exception)(nil),                  // 25: st2138.Exception
	(*CommandResponse)(nil),            // 26: st2138.CommandResponse
	nil,                                // 27: st2138.DataPayload.MetadataEntry
	nil,                                // 28: st2138.Param.ClientHintsEntry
	nil,                                // 29: st2138.Param.ParamsEntry
	nil,                                // 30: st2138.StructValue.FieldsEntry
	(*PolyglotText)(nil),               // 31: st2138.PolyglotText
	(*Constraint)(nil),                 // 32: st2138.Constraint
}
var file_param_proto_depIdxs = []int32{
	31, // 0: st2138.ParamInfo.name:type_name -> st2138.PolyglotText
	0,  // 1: st2138.ParamInfo.type:type_name -> st2138.ParamType
	27, // 2: st2138.DataPayload.metadata:type_name -> st2138.DataPayload.MetadataEntry
	2,  // 3: st2138.DataPayload.payload_encoding:type_name -> st2138.DataPayload.PayloadEncoding
	31, // 4: st2138.Param.name:type_name -> st2138.PolyglotText
	0,  // 5: st2138.Param.type:type_name -> st2138.ParamType
	14, // 6: st2138.Param.value:type_name -> st2138.Value
	32, // 7: st2138.Param.constraint:type_name -> st2138.Constraint
	28, // 8: st2138.Param.client_hints:type_name -> st2138.Param.ClientHintsEntry
	29, // 9: st2138.Param.params:type_name -> st2138.Param.ParamsEntry
	31, // 10: st2138.Param.help:type_name -> st2138.PolyglotText
	15, // 11: st2138.Param.import:type_name -> st2138.Import
	14, // 12: st2138.StructVariantValue.value:type_name -> st2138.Value
	6,  // 13: st2138.StructVariantList.struct_variants:type_name -> st2138.StructVariantValue
	30, // 14: st2138.StructValue.fields:type_name -> st2138.StructValue.FieldsEntry
	11, // 15: st2138.StructList.struct_values:type_name -> st2138.StructValue
	1,  // 16: st2138.Value.undefined_value:type_name -> st2138.UndefinedValue
	12, // 17: st2138.Value.empty_value:type_name -> st2138.Empty
	11, // 18: st2138.Value.struct_value:type_name -> st2138.StructValue
	8,  // 19: st2138.Value.int32_array_values:type_name -> st2138.Int32List
	9,  // 20: st2138.Value.float32_array_values:type_name -> st2138.Float32List
	10, // 21: st2138.Value.string_array_values:type_name -> st2138.StringList
	13, // 22: st2138.Value.struct_array_values:type_name -> st2138.StructList
	4,  // 23: st2138.Value.data_payload:type_name -> st2138.DataPayload
	6,  // 24: st2138.Value.struct_variant_value:type_name -> st2138.StructVariantValue
	7,  // 25: st2138.Value.struct_variant_array_values:type_name -> st2138.StructVariantList
	3,  // 26: st2138.ParamInfoResponse.info:type_name -> st2138.ParamInfo
	14, // 27: st2138.SetValuePayload.value:type_name -> st2138.Value
	19, // 28: st2138.SingleSetValuePayload.value:type_name -> st2138.SetValuePayload
	19, // 29: st2138.MultiSetValuePayload.values:type_name -> st2138.SetValuePayload
	14, // 30: st2138.ExecuteCommandPayload.value:type_name -> st2138.Value
	31, // 31: st2138.Exception.error_message:type_name -> st2138.PolyglotText
	12, // 32: st2138.CommandResponse.no_response:type_name -> st2138.Empty
	14, // 33: st2138.CommandResponse.response:type_name -> st2138.Value
	25, // 34: st2138.CommandResponse.exception:type_name -> st2138.Exception
	5,  // 35: st2138.Param.ParamsEntry.value:type_name -> st2138.Param
	14, // 36: st2138.StructValue.FieldsEntry.value:type_name -> st2138.Value
	37, // [37:37] is the sub-list for method output_type
	37, // [37:37] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_param_proto_init() }
func file_param_proto_init() {
	if File_param_proto != nil {
		return
	}
	file_language_proto_init()
	file_constraint_proto_init()
	file_param_proto_msgTypes[1].OneofWrappers = []any{
		(*DataPayload_Url)(nil),
		(*DataPayload_Payload)(nil),
	}
	file_param_proto_msgTypes[11].OneofWrappers = []any{
		(*Value_UndefinedValue)(nil),
		(*Value_EmptyValue)(nil),
		(*Value_Int32Value)(nil),
		(*Value_Float32Value)(nil),
		(*Value_StringValue)(nil),
		(*Value_StructValue)(nil),
		(*Value_Int32ArrayValues)(nil),
		(*Value_Float32ArrayValues)(nil),
		(*Value_StringArrayValues)(nil),
		(*Value_StructArrayValues)(nil),
		(*Value_DataPayload)(nil),
		(*Value_StructVariantValue)(nil),
		(*Value_StructVariantArrayValues)(nil),
	}
	file_param_proto_msgTypes[23].OneofWrappers = []any{
		(*CommandResponse_NoResponse)(nil),
		(*CommandResponse_Response)(nil),
		(*CommandResponse_Exception)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_param_proto_rawDesc), len(file_param_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_param_proto_goTypes,
		DependencyIndexes: file_param_proto_depIdxs,
		EnumInfos:         file_param_proto_enumTypes,
		MessageInfos:      file_param_proto_msgTypes,
	}.Build()
	File_param_proto = out.File
	file_param_proto_goTypes = nil
	file_param_proto_depIdxs = nil
}
