//
// Copyright (c) by the Society of Motion Picture and Television Engineers
//
// Redistribution and use in source and binary forms, with or without modification,
// are permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice, this
// list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice,
// this list of conditions and the following disclaimer in the documentation and/or
// other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its contributors
// may be used to endorse or promote products derived from this software without
// specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
// ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
// ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: service.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x06st2138\x1a\fdevice.proto\x1a\vparam.proto\x1a\x0elanguage.proto\x1a\x14externalobject.proto2\x8e\t\n" +
	"\rCatenaService\x12H\n" +
	"\rDeviceRequest\x12\x1c.st2138.DeviceRequestPayload\x1a\x17.st2138.DeviceComponent0\x01\x124\n" +
	"\x11GetPopulatedSlots\x12\r.st2138.Empty\x1a\x10.st2138.SlotList\x12J\n" +
	"\x0eExecuteCommand\x12\x1d.st2138.ExecuteCommandPayload\x1a\x17.st2138.CommandResponse0\x01\x12^\n" +
	"\x15ExternalObjectRequest\x12$.st2138.ExternalObjectRequestPayload\x1a\x1d.st2138.ExternalObjectPayload0\x01\x12P\n" +
	"\x10ParamInfoRequest\x12\x1f.st2138.ParamInfoRequestPayload\x1a\x19.st2138.ParamInfoResponse0\x01\x128\n" +
	"\bSetValue\x12\x1d.st2138.SingleSetValuePayload\x1a\r.st2138.Empty\x122\n" +
	"\bGetValue\x12\x17.st2138.GetValuePayload\x1a\r.st2138.Value\x12<\n" +
	"\rMultiSetValue\x12\x1c.st2138.MultiSetValuePayload\x1a\r.st2138.Empty\x12c\n" +
	"\x13UpdateSubscriptions\x12\".st2138.UpdateSubscriptionsPayload\x1a&.st2138.DeviceComponent.ComponentParam0\x01\x12K\n" +
	"\bGetParam\x12\x17.st2138.GetParamPayload\x1a&.st2138.DeviceComponent.ComponentParam\x128\n" +
	"\aConnect\x12\x16.st2138.ConnectPayload\x1a\x13.st2138.PushUpdates0\x01\x128\n" +
	"\vAddLanguage\x12\x1a.st2138.AddLanguagePayload\x1a\r.st2138.Empty\x12h\n" +
	"\x13LanguagePackRequest\x12\".st2138.LanguagePackRequestPayload\x1a-.st2138.DeviceComponent.ComponentLanguagePack\x123\n" +
	"\rListLanguages\x12\f.st2138.Slot\x1a\x14.st2138.LanguageList\x12E\n" +
	"\fRefreshToken\x12\x1b.st2138.RefreshTokenPayload\x1a\x18.st2138.ConnectionStatus\x12G\n" +
	"\fRevokeAccess\x12\x1b.st2138.RevokeAccessPayload\x1a\x1a.st2138.RevocationResponseB%\n" +
	"\x13catena.core.serviceB\n" +
	"CatenaCoreH\x01P\x01b\x06proto3"

var file_service_proto_goTypes = []any{
	(*DeviceRequestPayload)(nil),                  // 0: st2138.DeviceRequestPayload
	(*Empty)(nil),                                 // 1: st2138.Empty
	(*ExecuteCommandPayload)(nil),                 // 2: st2138.ExecuteCommandPayload
	(*ExternalObjectRequestPayload)(nil),          // 3: st2138.ExternalObjectRequestPayload
	(*ParamInfoRequestPayload)(nil),               // 4: st2138.ParamInfoRequestPayload
	(*SingleSetValuePayload)(nil),                 // 5: st2138.SingleSetValuePayload
	(*GetValuePayload)(nil),                       // 6: st2138.GetValuePayload
	(*MultiSetValuePayload)(nil),                  // 7: st2138.MultiSetValuePayload
	(*UpdateSubscriptionsPayload)(nil),            // 8: st2138.UpdateSubscriptionsPayload
	(*GetParamPayload)(nil),                       // 9: st2138.GetParamPayload
	(*ConnectPayload)(nil),                        // 10: st2138.ConnectPayload
	(*AddLanguagePayload)(nil),                    // 11: st2138.AddLanguagePayload
	(*LanguagePackRequestPayload)(nil),            // 12: st2138.LanguagePackRequestPayload
	(*Slot)(nil),                                  // 13: st2138.Slot
	(*RefreshTokenPayload)(nil),                   // 14: st2138.RefreshTokenPayload
	(*RevokeAccessPayload)(nil),                   // 15: st2138.RevokeAccessPayload
	(*DeviceComponent)(nil),                       // 16: st2138.DeviceComponent
	(*SlotList)(nil),                              // 17: st2138.SlotList
	(*CommandResponse)(nil),                       // 18: st2138.CommandResponse
	(*ExternalObjectPayload)(nil),                 // 19: st2138.ExternalObjectPayload
	(*ParamInfoResponse)(nil),                     // 20: st2138.ParamInfoResponse
	(*Value)(nil),                                 // 21: st2138.Value
	(*DeviceComponent_ComponentParam)(nil),        // 22: st2138.DeviceComponent.ComponentParam
	(*PushUpdates)(nil),                           // 23: st2138.PushUpdates
	(*DeviceComponent_ComponentLanguagePack)(nil), // 24: st2138.DeviceComponent.ComponentLanguagePack
	(*LanguageList)(nil),                          // 25: st2138.LanguageList
	(*ConnectionStatus)(nil),                      // 26: st2138.ConnectionStatus
	(*RevocationResponse)(nil),                    // 27: st2138.RevocationResponse
}
var file_service_proto_depIdxs = []int32{
	0,  // 0: st2138.CatenaService.DeviceRequest:input_type -> st2138.DeviceRequestPayload
	1,  // 1: st2138.CatenaService.GetPopulatedSlots:input_type -> st2138.Empty
	2,  // 2: st2138.CatenaService.ExecuteCommand:input_type -> st2138.ExecuteCommandPayload
	3,  // 3: st2138.CatenaService.ExternalObjectRequest:input_type -> st2138.ExternalObjectRequestPayload
	4,  // 4: st2138.CatenaService.ParamInfoRequest:input_type -> st2138.ParamInfoRequestPayload
	5,  // 5: st2138.CatenaService.SetValue:input_type -> st2138.SingleSetValuePayload
	6,  // 6: st2138.CatenaService.GetValue:input_type -> st2138.GetValuePayload
	7,  // 7: st2138.CatenaService.MultiSetValue:input_type -> st2138.MultiSetValuePayload
	8,  // 8: st2138.CatenaService.UpdateSubscriptions:input_type -> st2138.UpdateSubscriptionsPayload
	9,  // 9: st2138.CatenaService.GetParam:input_type -> st2138.GetParamPayload
	10, // 10: st2138.CatenaService.Connect:input_type -> st2138.ConnectPayload
	11, // 11: st2138.CatenaService.AddLanguage:input_type -> st2138.AddLanguagePayload
	12, // 12: st2138.CatenaService.LanguagePackRequest:input_type -> st2138.LanguagePackRequestPayload
	13, // 13: st2138.CatenaService.ListLanguages:input_type -> st2138.Slot
	14, // 14: st2138.CatenaService.RefreshToken:input_type -> st2138.RefreshTokenPayload
	15, // 15: st2138.CatenaService.RevokeAccess:input_type -> st2138.RevokeAccessPayload
	16, // 16: st2138.CatenaService.DeviceRequest:output_type -> st2138.DeviceComponent
	17, // 17: st2138.CatenaService.GetPopulatedSlots:output_type -> st2138.SlotList
	18, // 18: st2138.CatenaService.ExecuteCommand:output_type -> st2138.CommandResponse
	19, // 19: st2138.CatenaService.ExternalObjectRequest:output_type -> st2138.ExternalObjectPayload
	20, // 20: st2138.CatenaService.ParamInfoRequest:output_type -> st2138.ParamInfoResponse
	1,  // 21: st2138.CatenaService.SetValue:output_type -> st2138.Empty
	21, // 22: st2138.CatenaService.GetValue:output_type -> st2138.Value
	1,  // 23: st2138.CatenaService.MultiSetValue:output_type -> st2138.Empty
	22, // 24: st2138.CatenaService.UpdateSubscriptions:output_type -> st2138.DeviceComponent.ComponentParam
	22, // 25: st2138.CatenaService.GetParam:output_type -> st2138.DeviceComponent.ComponentParam
	23, // 26: st2138.CatenaService.Connect:output_type -> st2138.PushUpdates
	1,  // 27: st2138.CatenaService.AddLanguage:output_type -> st2138.Empty
	24, // 28: st2138.CatenaService.LanguagePackRequest:output_type -> st2138.DeviceComponent.ComponentLanguagePack
	25, // 29: st2138.CatenaService.ListLanguages:output_type -> st2138.LanguageList
	26, // 30: st2138.CatenaService.RefreshToken:output_type -> st2138.ConnectionStatus
	27, // 31: st2138.CatenaService.RevokeAccess:output_type -> st2138.RevocationResponse
	16, // [16:32] is the sub-list for method output_type
	0,  // [0:16] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_device_proto_init()
	file_param_proto_init()
	file_language_proto_init()
	file_externalobject_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
