FROM catena-base:latest

LABEL org.opencontainers.image.source https://github.com/rossvideo/Catena
LABEL org.opencontainers.image.name="catena-codeql"
LABEL org.opencontainers.image.description="Github codeql environment for the Catena C++ SDK"
LABEL org.opencontainers.image.licenses=CC-BY-ND-4.0
LABEL org.opencontainers.image.vendor="Ross Video"


ENV CLONE_DIR="/opt"
ENV INSTALL_DIR="/usr/local"
ENV GRPC_VER="v1.64.2"

# jwt-cpp
WORKDIR "${CLONE_DIR}"
RUN git clone https://github.com/Thalhammer/jwt-cpp && \
    cd jwt-cpp && \
    mkdir build && \
    cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="${INSTALL_DIR}" .. && \
    make -j 5 && \
    make install

# gtest
WORKDIR "${CLONE_DIR}"
RUN git clone https://github.com/google/googletest.git -b v1.14.0 && \
    cd googletest && \
    mkdir build && \
    cd build && \
    cmake .. -DBUILD_GMOCK=OFF -DCMAKE_INSTALL_PREFIX="${INSTALL_DIR}" && \
    make -j 5 && \
    make install

# grpc
WORKDIR "${CLONE_DIR}"
RUN git clone --recurse-submodules -b "${GRPC_VER}" --depth 1 --shallow-submodules https://github.com/grpc/grpc && \
    cd grpc && \
    mkdir -p cmake/build && \
    cd cmake/build && \
    cmake -DgRPC_INSTALL=ON -DgRPC_BUILD_TESTS=ON -DCMAKE_INSTALL_PREFIX="${INSTALL_DIR}" ../.. && \
    make -j 5 && \
    make install && \
    make -j 5 grpc_cli && \
    cp grpc_cli "${INSTALL_DIR}/bin"