var annotated_dup =
[
    [ "catena", "namespacecatena.html", [
      [ "common", "namespacecatena_1_1common.html", [
        [ "Authorizer", "classcatena_1_1common_1_1Authorizer.html", "classcatena_1_1common_1_1Authorizer" ],
        [ "CommandTag", "structcatena_1_1common_1_1CommandTag.html", null ],
        [ "ConstraintTag", "structcatena_1_1common_1_1ConstraintTag.html", null ],
        [ "Device", "classcatena_1_1common_1_1Device.html", "classcatena_1_1common_1_1Device" ],
        [ "EmptyValue", "structcatena_1_1common_1_1EmptyValue.html", null ],
        [ "FakeLock", "structcatena_1_1common_1_1FakeLock.html", null ],
        [ "FieldInfo", "structcatena_1_1common_1_1FieldInfo.html", null ],
        [ "IConstraint", "classcatena_1_1common_1_1IConstraint.html", "classcatena_1_1common_1_1IConstraint" ],
        [ "ILanguagePack", "classcatena_1_1common_1_1ILanguagePack.html", "classcatena_1_1common_1_1ILanguagePack" ],
        [ "IMenu", "classcatena_1_1common_1_1IMenu.html", "classcatena_1_1common_1_1IMenu" ],
        [ "IMenuGroup", "classcatena_1_1common_1_1IMenuGroup.html", "classcatena_1_1common_1_1IMenuGroup" ],
        [ "IParam", "classcatena_1_1common_1_1IParam.html", "classcatena_1_1common_1_1IParam" ],
        [ "IParamVisitor", "classcatena_1_1common_1_1IParamVisitor.html", "classcatena_1_1common_1_1IParamVisitor" ],
        [ "IPolyglotText", "classcatena_1_1common_1_1IPolyglotText.html", null ],
        [ "LanguagePack", "classcatena_1_1common_1_1LanguagePack.html", "classcatena_1_1common_1_1LanguagePack" ],
        [ "LanguagePackTag", "structcatena_1_1common_1_1LanguagePackTag.html", null ],
        [ "Menu", "classcatena_1_1common_1_1Menu.html", "classcatena_1_1common_1_1Menu" ],
        [ "MenuGroup", "classcatena_1_1common_1_1MenuGroup.html", "classcatena_1_1common_1_1MenuGroup" ],
        [ "MenuGroupTag", "structcatena_1_1common_1_1MenuGroupTag.html", null ],
        [ "MenuTag", "structcatena_1_1common_1_1MenuTag.html", null ],
        [ "NamedChoiceConstraint", "classcatena_1_1common_1_1NamedChoiceConstraint.html", "classcatena_1_1common_1_1NamedChoiceConstraint" ],
        [ "ParamDescriptor", "classcatena_1_1common_1_1ParamDescriptor.html", "classcatena_1_1common_1_1ParamDescriptor" ],
        [ "ParamTag", "structcatena_1_1common_1_1ParamTag.html", null ],
        [ "ParamVisitor", "classcatena_1_1common_1_1ParamVisitor.html", "classcatena_1_1common_1_1ParamVisitor" ],
        [ "ParamWithValue", "classcatena_1_1common_1_1ParamWithValue.html", "classcatena_1_1common_1_1ParamWithValue" ],
        [ "Path", "classcatena_1_1common_1_1Path.html", "classcatena_1_1common_1_1Path" ],
        [ "PicklistConstraint", "classcatena_1_1common_1_1PicklistConstraint.html", "classcatena_1_1common_1_1PicklistConstraint" ],
        [ "PolyglotText", "classcatena_1_1common_1_1PolyglotText.html", null ],
        [ "RangeConstraint", "classcatena_1_1common_1_1RangeConstraint.html", "classcatena_1_1common_1_1RangeConstraint" ],
        [ "StructInfo", "structcatena_1_1common_1_1StructInfo.html", null ],
        [ "SubscriptionManager", "classcatena_1_1common_1_1SubscriptionManager.html", "classcatena_1_1common_1_1SubscriptionManager" ]
      ] ],
      [ "meta", "namespacecatena_1_1meta.html", [
        [ "FrontT", "classcatena_1_1meta_1_1FrontT.html", null ],
        [ "FrontT< TypeList< Head, Tail... > >", "classcatena_1_1meta_1_1FrontT_3_01TypeList_3_01Head_00_01Tail_8_8_8_01_4_01_4.html", null ],
        [ "is_streamable", "structcatena_1_1meta_1_1is__streamable.html", null ],
        [ "is_streamable< T, std::void_t< decltype(std::cout<< std::declval< T >())> >", "structcatena_1_1meta_1_1is__streamable_3_01T_00_01std_1_1void__t_3_01decltype_07std_1_1cout_3_3_f018ad5e508e96c26725f0228af2f889.html", null ],
        [ "is_variant", "structcatena_1_1meta_1_1is__variant.html", null ],
        [ "is_variant< T, std::void_t< decltype(std::get< 0 >(std::declval< T >()))> >", "structcatena_1_1meta_1_1is__variant_3_01T_00_01std_1_1void__t_3_01decltype_07std_1_1get_3_010_01ebdd46a9af85028d423a39579c8d1c53.html", null ],
        [ "NthElementT", "classcatena_1_1meta_1_1NthElementT.html", null ],
        [ "NthElementT< L, 0 >", "classcatena_1_1meta_1_1NthElementT_3_01L_00_010_01_4.html", null ],
        [ "PopFrontT", "classcatena_1_1meta_1_1PopFrontT.html", null ],
        [ "PopFrontT< TypeList< Head, Tail... > >", "classcatena_1_1meta_1_1PopFrontT_3_01TypeList_3_01Head_00_01Tail_8_8_8_01_4_01_4.html", null ],
        [ "PushFrontT", "classcatena_1_1meta_1_1PushFrontT.html", null ],
        [ "PushFrontT< TypeList< Ts... >, T >", "classcatena_1_1meta_1_1PushFrontT_3_01TypeList_3_01Ts_8_8_8_01_4_00_01T_01_4.html", null ],
        [ "TypeList", "classcatena_1_1meta_1_1TypeList.html", null ]
      ] ],
      [ "patterns", "namespacecatena_1_1patterns.html", [
        [ "EnumDecorator", "classcatena_1_1patterns_1_1EnumDecorator.html", "classcatena_1_1patterns_1_1EnumDecorator" ],
        [ "Functory", "classcatena_1_1patterns_1_1Functory.html", "classcatena_1_1patterns_1_1Functory" ],
        [ "GenericFactory", "classcatena_1_1patterns_1_1GenericFactory.html", "classcatena_1_1patterns_1_1GenericFactory" ],
        [ "Singleton", "classcatena_1_1patterns_1_1Singleton.html", "classcatena_1_1patterns_1_1Singleton" ]
      ] ],
      [ "API", "classcatena_1_1API.html", "classcatena_1_1API" ],
      [ "exception_with_status", "structcatena_1_1exception__with__status.html", null ],
      [ "PeerInfo", "classcatena_1_1PeerInfo.html", "classcatena_1_1PeerInfo" ],
      [ "PeerManager", "classcatena_1_1PeerManager.html", "classcatena_1_1PeerManager" ]
    ] ],
    [ "CatenaServiceImpl", "classCatenaServiceImpl.html", "classCatenaServiceImpl" ],
    [ "JWTAuthMetadataProcessor", "classJWTAuthMetadataProcessor.html", null ]
];