cpp-v0.0.14-4: catena::common::ParamWithValue< T > Class Template Reference
catena::common::ParamWithValue< T > Class Template Reference
ParamWithValue is a class that implements the IParam interface for each param type in the device model.
#include <ParamWithValue.h>
Public Types
using TSizeTracker = std::vector< std::size_t >
Public Types inherited from catena::common::IParam
using ParamType = catena::patterns::EnumDecorator< catena::ParamType >
ParamType is an enum class that defines the types of parameters.
using OidAliases = std::vector< std::string >
OidAliases is a vector of strings.
using Path = catena::common::Path
Public Member Functions
ParamWithValue (T &value, IParamDescriptor &descriptor, IDevice &dev, bool isCommand)
Constructs a new ParamWithValue object and adds it to the device.
ParamWithValue (T &value, IParamDescriptor &descriptor)
Constructs a new ParamWithValue object without adding it to the device.
ParamWithValue (T &value, IParamDescriptor &descriptor, std::shared_ptr< std::size_t > mSizeTracker, std::shared_ptr< TSizeTracker > tSizeTracker)
Construct a new ParamWithValue object without adding it to the device. Also carries over size trackers for array parameters.
template<typename FieldType = T, typename ParentType >
ParamWithValue (const FieldInfo< FieldType, ParentType > &field, ParentType &parentValue, IParamDescriptor &parentDescriptor)
Construct a new ParamWithValue object using FieldInfo.
ParamWithValue (const ParamWithValue &)=delete
ParamWithValue can not be copied directly.
ParamWithValue & operator= (const ParamWithValue &)=delete
ParamWithValue (ParamWithValue &&)=default
ParamWithValue has move semantics.
ParamWithValue & operator= (ParamWithValue &&)=default
virtual ~ParamWithValue ()=default
Destructor.
std::unique_ptr< IParam > copy () const override
Creates a shallow copy the parameter.
catena::exception_with_status toProto (catena::Value &value, const IAuthorizer &authz) const override
Serialize the parameter value to protobuf if authorized.
catena::exception_with_status toProto (catena::Param &param, const IAuthorizer &authz) const override
Serializes the parameter descriptor to a protobuf param object. Includes both the descriptor and the value.
catena::exception_with_status toProto (catena::ParamInfoResponse &paramInfo, const IAuthorizer &authz) const override
Serializes the parameter descriptor to a protobuf paramInfo object.
catena::exception_with_status fromProto (const catena::Value &value, const IAuthorizer &authz) override
Serializes the parameter value to protobuf.
IParam::ParamType type () const override
Gets the parameters protobuf value type.
const std::string & getOid () const override
Gets the oid of the param.
void setOid (const std::string &oid) override
Sets the param's oid.
bool readOnly () const override
Returns true if the param is readOnly.
void readOnly (bool flag) override
Sets the read only status of the param.
T & get ()
Gets the value of the parameter.
const T & get () const
Gets the value of the parameter (const version).
std::unique_ptr< IParam > getParam (Path &oid, const IAuthorizer &authz, catena::exception_with_status &status) override
Gets a child parameter by name.
void defineCommand (std::function< std::unique_ptr< IParamDescriptor::ICommandResponder >(const catena::Value &, const bool)> commandImpl)
Defines the parameter's command implementation.
std::unique_ptr< IParamDescriptor::ICommandResponder > executeCommand (const catena::Value &value, const bool respond) const override
Exectutes the parameter's command implementation.
std::size_t size () const override
Returns the size of an array parameter.
std::unique_ptr< IParam > addBack (const IAuthorizer &authz, catena::exception_with_status &status) override
Add an empty value to and return the back of an array parameter.
catena::exception_with_status popBack (const IAuthorizer &authz) override
Pops the back of an array parameter.
const IParamDescriptor & getDescriptor () const override
Gets the parameter's descriptor.
bool isArrayType () const override
Checks if the parameter is an array type.
void addParam (const std::string &oid, IParamDescriptor *param) override
Adds a child parameter.
const catena::common::IConstraint * getConstraint () const override
Gets the parameter's constraint.
const std::string & getScope () const override
Gets the parameter's access scope.
bool validateSetValue (const catena::Value &value, Path::Index index, const IAuthorizer &authz, catena::exception_with_status &ans) override
Validates a setValue operation without changing the param's value.
void resetValidate () override
Resets any trackers that might have been changed in validateSetValue().
Public Member Functions inherited from catena::common::IParam
IParam & operator= (IParam &&)=default
IParam has move semantics.
IParam (IParam &&)=default
IParam (const IParam &)=delete
IParam does not have copy semantics.
IParam & operator= (const IParam &)=delete
Protected Types
using Kind = catena::Value::KindCase
Protected Member Functions
template<typename U >
std::size_t size_ (const U &value) const
Gets the size of the string/array parameter.
std::size_t size_ (const std::string &value) const
Gets the size of the string/array parameter.
template<meta::IsVector U>
std::size_t size_ (const U &value) const
Gets the size of the string/array parameter.
template<typename U >
std::unique_ptr< IParam > addBack_ (U &value, const IAuthorizer &authz, catena::exception_with_status &status)
Adds an empty element to the end of an array parameter.
template<meta::IsVector U>
std::unique_ptr< IParam > addBack_ (U &value, const IAuthorizer &authz, catena::exception_with_status &status)
Adds an empty element to the end of an array parameter.
template<typename U >
catena::exception_with_status popBack_ (U &value, const IAuthorizer &authz)
Removes the last element from an array parameter.
template<meta::IsVector U>
catena::exception_with_status popBack_ (U &value, const IAuthorizer &authz)
Removes the last element from an array parameter.
template<typename U >
std::unique_ptr< IParam > getParam_ (Path &oid, U &value, const IAuthorizer &authz, catena::exception_with_status &status)
get the child parameter that oid points to
template<meta::IsVector U>
std::unique_ptr< IParam > getParam_ (Path &oid, U &value, const IAuthorizer &authz, catena::exception_with_status &status)
get the child parameter that oid points to
template<CatenaStruct U>
std::unique_ptr< IParam > getParam_ (Path &oid, U &value, const IAuthorizer &authz, catena::exception_with_status &status)
get the child parameter that oid points to
template<meta::IsVariant U>
std::unique_ptr< IParam > getParam_ (Path &oid, U &value, const IAuthorizer &authz, catena::exception_with_status &status)
get the child parameter that oid points to
template<typename Struct , typename Tuple >
std::unique_ptr< IParam > findParamByName_ (const Tuple &fields, const std::string &name)
gets the child parameter by name
template<typename Struct , typename Tuple , std::size_t... Is>
std::unique_ptr< IParam > findParamByNameImpl_ (const Tuple &fields, const std::string &name, std::index_sequence< Is... >)
gets the child parameter by name
template<std::size_t I, typename Tuple >
std::unique_ptr< IParam > getParamAtIndex_ (const Tuple &tuple)
Create a new paramWithValue object for the field at index I.
template<typename U , typename V >
catena::exception_with_status validateSetValue_ (U &oldVal, const V &newVal, const catena::Value &protoVal, Path::Index index, const IAuthorizer &authz)
Default overload of validateSetValue_ used in cases where type(U) == type(V).
template<typename U , typename V >
requires (!meta::IsVector<V>)
catena::exception_with_status validateSetValue_ (std::vector< U > &arrayVal, const V &memVal, const catena::Value &protoVal, Path::Index index, const IAuthorizer &authz)
Insert/append value to array overload of validateSetValue_.
Protected Attributes
const std::unordered_map< Kind, std::function< catena::exception_with_status(const catena::Value &, Path::Index, const IAuthorizer &)> > validateSetValueMap_
A map to help routing to the validateSetValue_ functions above. Protobuf is great in that you need to use a seperate function to get each different type of value.
IParamDescriptor & descriptor_
The parameter's descriptor object.
std::reference_wrapper< T > value_
The value of the parameter.
std::shared_ptr< std::size_t > mSizeTracker_ = nullptr
Tracker variable used to keep track of the total size of a string or array. Shared ptr is used as the tracker must be shared between the parent and all copies.
std::shared_ptr< TSizeTracker > tSizeTracker_ = nullptr
A vector used to keep track of the string length at each index of a string array. For all other types, this should be a nullptr. Shared ptr is used as the tracker must be shared between the parent and all copies.
Detailed Description
template<typename T>
class catena::common::ParamWithValue< T >
ParamWithValue is a class that implements the IParam interface for each param type in the device model.
Examples
hello_world.cpp.
Constructor & Destructor Documentation
ParamWithValue() [1/4]
template<typename T > catena::common::ParamWithValue< T >::ParamWithValue (T & value, IParamDescriptor & descriptor, IDevice & dev, bool isCommand) inline
Constructs a new ParamWithValue object and adds it to the device.
Parameters
value The value of the parameter.
descriptor The descriptor associated with the parameter.
dev The device to add the parameter to.
References catena::common::IDevice::addItem(), and catena::common::IParamDescriptor::getOid().
ParamWithValue() [2/4]
template<typename T > catena::common::ParamWithValue< T >::ParamWithValue (T & value, IParamDescriptor & descriptor) inline
Constructs a new ParamWithValue object without adding it to the device.
Parameters
value The value of the parameter.
descriptor The descriptor associated with the parameter.
ParamWithValue() [3/4]
template<typename T > catena::common::ParamWithValue< T >::ParamWithValue (T & value, IParamDescriptor & descriptor, std::shared_ptr< std::size_t > mSizeTracker, std::shared_ptr< TSizeTracker > tSizeTracker) inline
Construct a new ParamWithValue object without adding it to the device. Also carries over size trackers for array parameters.
Parameters
value The value of the parameter.
descriptor The descriptor associated with the parameter.
mSizeTracker A shared pointer to the max size tracker.
tSizeTracker A shared pointer to the total size tracker.
References catena::common::ParamWithValue< T >::mSizeTracker_, and catena::common::ParamWithValue< T >::tSizeTracker_.
ParamWithValue() [4/4]
template<typename T > template<typename FieldType = T, typename ParentType > catena::common::ParamWithValue< T >::ParamWithValue (const FieldInfo< FieldType, ParentType > & field, ParentType & parentValue, IParamDescriptor & parentDescriptor) inline
Construct a new ParamWithValue object using FieldInfo.
Parameters
field The FieldInfo object containing the field name.
parentValue The parent object containing the field values.
parentDescriptor The descriptor associated with the parent param.
Member Function Documentation
addBack()
template<typename T > std::unique_ptr< IParam > catena::common::ParamWithValue< T >::addBack (const IAuthorizer & authz, catena::exception_with_status & status) inline override virtual
Add an empty value to and return the back of an array parameter.
Parameters
authz The IAuthorizer to test write permissions with.
status The status of the operation. OK if successful, otherwise an error.
Returns
A unique ptr to the new element, or nullptr if the operation failed.
Implements catena::common::IParam.
References catena::common::ParamWithValue< T >::addBack_(), and catena::common::ParamWithValue< T >::value_.
addBack_() [1/2]
template<typename T > template<typename U > std::unique_ptr< IParam > catena::common::ParamWithValue< T >::addBack_ (U & value, const IAuthorizer & authz, catena::exception_with_status & status) inline protected
Adds an empty element to the end of an array parameter.
Template Parameters
U The type of the value that we are adding to the back of.
Parameters
value The value that we are adding to the back of.
authz The IAuthorizer to test write permissions with.
status The status of the operation. OK if successful, otherwise an error.
Returns
nullptr.
This generic template is used when the type is not a CatenaStructArray. Since you cant add to the back, it only returns nullptr.
References catena::common::ParamWithValue< T >::descriptor_, catena::common::IParamDescriptor::getOid(), and catena::INVALID_ARGUMENT.
addBack_() [2/2]
template<typename T > template<meta::IsVector U> std::unique_ptr< IParam > catena::common::ParamWithValue< T >::addBack_ (U & value, const IAuthorizer & authz, catena::exception_with_status & status) inline protected
Adds an empty element to the end of an array parameter.
Template Parameters
U the type of the value that we are adding to the back of.
Parameters
value The value that we are adding to the back of.
authz The IAuthorizer to test write permissions with.
status The status of the operation. OK if successful, otherwise an error.
Returns
A unique ptr to the new element, or nullptr if the operation failed.
This specialization is used when the type is a CatenaStructArray.
References catena::common::ParamWithValue< T >::descriptor_, catena::common::IParamDescriptor::getOid(), catena::common::IParamDescriptor::max_length(), catena::OUT_OF_RANGE, catena::PERMISSION_DENIED, and catena::common::IAuthorizer::writeAuthz().
addParam()
template<typename T > void catena::common::ParamWithValue< T >::addParam (const std::string & oid, IParamDescriptor * param) inline override virtual
Adds a child parameter.
Parameters
oid The oid of the child parameter to add.
param The child parameter to add.
Implements catena::common::IParam.
References catena::common::IParamDescriptor::addSubParam(), and catena::common::ParamWithValue< T >::descriptor_.
copy()
template<typename T > std::unique_ptr< IParam > catena::common::ParamWithValue< T >::copy () const inline override virtual
Creates a shallow copy the parameter.
Needed to copy IParam objects.
ParamWithValue objects only contain four references, so they are cheap to copy.
Implements catena::common::IParam.
References catena::common::ParamWithValue< T >::descriptor_, catena::common::ParamWithValue< T >::mSizeTracker_, catena::common::ParamWithValue< T >::tSizeTracker_, and catena::common::ParamWithValue< T >::value_.
defineCommand()
template<typename T > void catena::common::ParamWithValue< T >::defineCommand (std::function< std::unique_ptr< IParamDescriptor::ICommandResponder >(const catena::Value &, const bool)> commandImpl) inline virtual
Defines the parameter's command implementation.
Parameters
commandImpl The new command implementation.
Implements catena::common::IParam.
References catena::common::IParamDescriptor::defineCommand(), and catena::common::ParamWithValue< T >::descriptor_.
executeCommand()
template<typename T > std::unique_ptr< IParamDescriptor::ICommandResponder > catena::common::ParamWithValue< T >::executeCommand (const catena::Value & value, const bool respond) const inline override virtual
Exectutes the parameter's command implementation.
Parameters
value the value to pass to the command implementation.
respond Flag indicating whether the command should respond with a CommandResponse.
Returns
The CommandResponder from the command implementation.
Implements catena::common::IParam.
References catena::common::ParamWithValue< T >::descriptor_, and catena::common::IParamDescriptor::executeCommand().
findParamByName_()
template<typename T > template<typename Struct , typename Tuple > std::unique_ptr< IParam > catena::common::ParamWithValue< T >::findParamByName_ (const Tuple & fields, const std::string & name) inline protected
gets the child parameter by name
Template Parameters
Struct the type of the struct that we are getting the child parameter from
Parameters
fields the tuple of FieldInfo structs that describe the fields of the struct
name the name of the child parameter
Returns
a unique pointer to the child parameter, or nullptr if it does not exist
This function is a helper function for getParam(Path& oid, U& value) that finds the child parameter by name.
This intermediate function in needed to create the index sequence for the given tuple. findParamByNameImpl uses the index sequence to deduce its template parameters.
findParamByNameImpl_()
template<typename T > template<typename Struct , typename Tuple , std::size_t... Is> std::unique_ptr< IParam > catena::common::ParamWithValue< T >::findParamByNameImpl_ (const Tuple & fields, const std::string & name, std::index_sequence< Is... >) inline protected
gets the child parameter by name
Template Parameters
Struct the type of the struct that we are getting the child parameter from
Tuple the tuple of FieldInfo structs that describe the fields of the struct
Is the indices of the fields in the tuple
Parameters
fields the tuple of FieldInfo structs that describe the fields of the struct
name the name of the child parameter
Returns
a unique pointer to the child parameter, or nullptr if it does not exist
This function is a helper function for findParamByName that finds the child parameter by name.
Creates an array of unique pointers to IParam objects. The pointer will be nullptr if the field name does not match the name parameter. If the field name does match the name parameter, the pointer will be a unique pointer to an IParam constructed with the field info.
fromProto()
template<typename T > catena::exception_with_status catena::common::ParamWithValue< T >::fromProto (const catena::Value & value, const IAuthorizer & authz) inline override virtual
Serializes the parameter value to protobuf.
Parameters
dst The protobuf value to serialize to.
authz The authorizer object to containing the client's scopes.
Implements catena::common::IParam.
References catena::common::ParamWithValue< T >::descriptor_, and catena::common::ParamWithValue< T >::value_.
getConstraint()
template<typename T > const catena::common::IConstraint * catena::common::ParamWithValue< T >::getConstraint () const inline override virtual
Gets the parameter's constraint.
Implements catena::common::IParam.
References catena::common::ParamWithValue< T >::descriptor_, and catena::common::IParamDescriptor::getConstraint().
getDescriptor()
template<typename T > const IParamDescriptor & catena::common::ParamWithValue< T >::getDescriptor () const inline override virtual
Gets the parameter's descriptor.
Returns
The parameter's ParamDescriptor object.
Implements catena::common::IParam.
References catena::common::ParamWithValue< T >::descriptor_.
getOid()
template<typename T > const std::string & catena::common::ParamWithValue< T >::getOid () const inline override virtual
Gets the oid of the param.
Returns
The oid of the param
Implements catena::common::IParam.
References catena::common::ParamWithValue< T >::descriptor_, and catena::common::IParamDescriptor::getOid().
getParam()
template<typename T > std::unique_ptr< IParam > catena::common::ParamWithValue< T >::getParam (Path & oid, const IAuthorizer & authz, catena::exception_with_status & status) inline override virtual
Gets a child parameter by name.
Parameters
oid The oid of the child parameter to get.
authz The IAuthorizer to test read permissions with.
status The status of the operation. OK if successful, otherwise an error.
Returns
A unique pointer to the child parameter, or nullptr if the operation failed.
Implements catena::common::IParam.
Examples
hello_world.cpp.
References catena::common::Path::fqoid(), catena::common::ParamWithValue< T >::getParam_(), catena::PERMISSION_DENIED, catena::common::IAuthorizer::readAuthz(), and catena::common::ParamWithValue< T >::value_.
getParam_() [1/4]
template<typename T > template<typename U > std::unique_ptr< IParam > catena::common::ParamWithValue< T >::getParam_ (Path & oid, U & value, const IAuthorizer & authz, catena::exception_with_status & status) inline protected
get the child parameter that oid points to
Template Parameters
U the type of the value that we are getting the child parameter from
Parameters
oid the path to the child parameter
value the value to get the child parameter from
authz The Authorizer object containing the client's scopes.
status The status of the operation. OK if successful, otherwise an error.
Returns
a unique pointer to the child parameter
This generic template is used when the type is not a CatenaStruct or CatenaStructArray. Since this type has no sub-params, it only returns nullptr.
References catena::INVALID_ARGUMENT.
getParam_() [2/4]
template<typename T > template<meta::IsVector U> std::unique_ptr< IParam > catena::common::ParamWithValue< T >::getParam_ (Path & oid, U & value, const IAuthorizer & authz, catena::exception_with_status & status) inline protected
get the child parameter that oid points to
Template Parameters
U the type of the value that we are getting the child parameter from
Parameters
oid the path to the child parameter
value the value to get the child parameter from
authz The Authorizer object containing the client's scopes.
status The status of the operation. OK if successful, otherwise an error.
Returns
a unique pointer to the child parameter, or nullptr if it does not exist
This specialization is used when the type is a CatenaStructArray. This function expects the front segment of the oid to be an index.
References catena::common::ParamWithValue< T >::descriptor_, catena::common::Path::empty(), catena::common::Path::fqoid(), catena::common::Path::front_as_index(), catena::common::Path::front_is_index(), catena::common::ParamWithValue< T >::getParam(), catena::INVALID_ARGUMENT, catena::NOT_FOUND, catena::OUT_OF_RANGE, and catena::common::Path::pop().
getParam_() [3/4]
template<typename T > template<CatenaStruct U> std::unique_ptr< IParam > catena::common::ParamWithValue< T >::getParam_ (Path & oid, U & value, const IAuthorizer & authz, catena::exception_with_status & status) inline protected
get the child parameter that oid points to
Template Parameters
U the type of the value that we are getting the child parameter from
Parameters
oid the path to the child parameter
value the value to get the child parameter from
authz The Authorizer object containing the client's scopes.
status The status of the operation. OK if successful, otherwise an error.
Returns
a unique pointer to the child parameter, or nullptr if it does not exist
This specialization is used when the type is a CatenaStruct. This function expects the front segment of the oid to be a string.
References catena::common::Path::empty(), catena::common::Path::fqoid(), catena::common::Path::front_as_string(), catena::common::Path::front_is_string(), catena::INVALID_ARGUMENT, catena::NOT_FOUND, catena::PERMISSION_DENIED, catena::common::Path::pop(), and catena::common::IAuthorizer::readAuthz().
getParam_() [4/4]
template<typename T > template<meta::IsVariant U> std::unique_ptr< IParam > catena::common::ParamWithValue< T >::getParam_ (Path & oid, U & value, const IAuthorizer & authz, catena::exception_with_status & status) inline protected
get the child parameter that oid points to
Template Parameters
U the type of the value that we are getting the child parameter from
Parameters
oid the path to the child parameter
value the value to get the child parameter from
authz The Authorizer object containing the client's scopes.
status The status of the operation. OK if successful, otherwise an error.
Returns
a unique pointer to the child parameter, or nullptr if it does not exist
This specialization is used when the type is a CatenaStructVariant. This function expects the front segment of the oid to be a string.
References catena::common::ParamWithValue< T >::descriptor_, catena::common::Path::empty(), catena::common::Path::fqoid(), catena::common::Path::front_as_string(), catena::common::Path::front_is_string(), catena::common::ParamWithValue< T >::getParam(), catena::common::IParamDescriptor::getSubParam(), catena::INVALID_ARGUMENT, catena::NOT_FOUND, catena::PERMISSION_DENIED, catena::common::Path::pop(), and catena::common::IAuthorizer::readAuthz().
getParamAtIndex_()
template<typename T > template<std::size_t I, typename Tuple > std::unique_ptr< IParam > catena::common::ParamWithValue< T >::getParamAtIndex_ (const Tuple & tuple) inline protected
Create a new paramWithValue object for the field at index I.
Template Parameters
I the index of the field in the tuple
Parameters
tuple the tuple of FieldInfo structs that describe the fields of the struct
Returns
a unique pointer to the new IParam object
This function is a helper function for findParamByName that creates a new ParamWithValue object for the field at index I of the tuple.
References catena::common::ParamWithValue< T >::descriptor_, and catena::common::ParamWithValue< T >::value_.
getScope()
template<typename T > const std::string & catena::common::ParamWithValue< T >::getScope () const inline override virtual
Gets the parameter's access scope.
Implements catena::common::IParam.
References catena::common::ParamWithValue< T >::descriptor_, and catena::common::IParamDescriptor::getScope().
isArrayType()
template<typename T > bool catena::common::ParamWithValue< T >::isArrayType () const inline override virtual
Checks if the parameter is an array type.
Returns
True if the parameter is an array type (INT32_ARRAY, FLOAT32_ARRAY, STRING_ARRAY, STRUCT_ARRAY, or STRUCT_VARIANT_ARRAY).
Implements catena::common::IParam.
References catena::common::ParamWithValue< T >::type(), and catena::patterns::EnumDecorator< E >::value().
popBack()
template<typename T > catena::exception_with_status catena::common::ParamWithValue< T >::popBack (const IAuthorizer & authz) inline override virtual
Pops the back of an array parameter.
Parameters
authz The IAuthorizer to test write permissions with.
Returns
OK if succcessful, otherwise an error.
Implements catena::common::IParam.
References catena::common::ParamWithValue< T >::popBack_(), and catena::common::ParamWithValue< T >::value_.
popBack_() [1/2]
template<typename T > template<typename U > catena::exception_with_status catena::common::ParamWithValue< T >::popBack_ (U & value, const IAuthorizer & authz) inline protected
Removes the last element from an array parameter.
Template Parameters
U the type of the value that we are poping the back of.
Parameters
value The value that we are poping the back of.
authz The IAuthorizer to test write permissions with.
Returns
catena::exception_with_status error.
This generic template is used when the type is not a CatenaStructArray. Since you cant pop the back, it only returns an error.
References catena::INVALID_ARGUMENT.
popBack_() [2/2]
template<typename T > template<meta::IsVector U> catena::exception_with_status catena::common::ParamWithValue< T >::popBack_ (U & value, const IAuthorizer & authz) inline protected
Removes the last element from an array parameter.
Template Parameters
U the type of the value that we are poping the back of.
Parameters
value The value that we are poping the back of.
authz The IAuthorizer to test write permissions with.
Returns
OK if successful, error otherwise.
This specialization is used when the type is a CatenaStructArray.
References catena::common::ParamWithValue< T >::descriptor_, catena::common::IParamDescriptor::getOid(), catena::OK, catena::OUT_OF_RANGE, catena::PERMISSION_DENIED, and catena::common::IAuthorizer::writeAuthz().
readOnly() [1/2]
template<typename T > bool catena::common::ParamWithValue< T >::readOnly () const inline override virtual
Returns true if the param is readOnly.
Implements catena::common::IParam.
References catena::common::ParamWithValue< T >::descriptor_, and catena::common::IParamDescriptor::readOnly().
readOnly() [2/2]
template<typename T > void catena::common::ParamWithValue< T >::readOnly (bool flag) inline override virtual
Sets the read only status of the param.
Parameters
flag True if the param should be read only, false otherwise.
Implements catena::common::IParam.
References catena::common::ParamWithValue< T >::descriptor_, and catena::common::IParamDescriptor::readOnly().
resetValidate()
template<typename T > void catena::common::ParamWithValue< T >::resetValidate () inline override virtual
Resets any trackers that might have been changed in validateSetValue().
Implements catena::common::IParam.
References catena::common::ParamWithValue< T >::mSizeTracker_, and catena::common::ParamWithValue< T >::tSizeTracker_.
setOid()
template<typename T > void catena::common::ParamWithValue< T >::setOid (const std::string & oid) inline override virtual
Sets the param's oid.
Parameters
oid The new oid for the param.
Implements catena::common::IParam.
References catena::common::ParamWithValue< T >::descriptor_, and catena::common::IParamDescriptor::setOid().
size()
template<typename T > std::size_t catena::common::ParamWithValue< T >::size () const inline override virtual
Returns the size of an array parameter.
Returns
The size of the array parameter, or 0 if the parameter is not an array.
Implements catena::common::IParam.
Examples
hello_world.cpp.
References catena::common::ParamWithValue< T >::size_(), and catena::common::ParamWithValue< T >::value_.
size_() [1/3]
template<typename T > std::size_t catena::common::ParamWithValue< T >::size_ (const std::string & value) const inline protected
Gets the size of the string/array parameter.
Parameters
value The parameter's value.
Returns
The size of the string parameter.
This specialization is used when the type is a std::string.
size_() [2/3]
template<typename T > template<typename U > std::size_t catena::common::ParamWithValue< T >::size_ (const U & value) const inline protected
Gets the size of the string/array parameter.
Parameters
value The parameter's value.
Returns
0.
This generic template is used when the type is not a CatenaStructArray. Since there is no .size() attribute, it only returns 0.
size_() [3/3]
template<typename T > template<meta::IsVector U> std::size_t catena::common::ParamWithValue< T >::size_ (const U & value) const inline protected
Gets the size of the string/array parameter.
Parameters
value The parameter's value.
Returns
The size of the array parameter.
This specialization is used when the type is a CatenaStructArray.
toProto() [1/3]
template<typename T > catena::exception_with_status catena::common::ParamWithValue< T >::toProto (catena::Param & param, const IAuthorizer & authz) const inline override virtual
Serializes the parameter descriptor to a protobuf param object. Includes both the descriptor and the value.
Parameters
param The protobuf object to serialize to.
authz The authorizer object containing the client's scopes.
Implements catena::common::IParam.
References catena::common::ParamWithValue< T >::descriptor_, catena::OK, catena::common::IParamDescriptor::toProto(), and catena::common::ParamWithValue< T >::toProto().
toProto() [2/3]
template<typename T > catena::exception_with_status catena::common::ParamWithValue< T >::toProto (catena::ParamInfoResponse & paramInfo, const IAuthorizer & authz) const inline override virtual
Serializes the parameter descriptor to a protobuf paramInfo object.
Parameters
paramInfo The protobuf value to serialize to.
authz The authorization information.
Implements catena::common::IParam.
References catena::common::ParamWithValue< T >::descriptor_, catena::common::IParamDescriptor::getOid(), catena::OK, catena::PERMISSION_DENIED, catena::common::IAuthorizer::readAuthz(), and catena::common::IParamDescriptor::toProto().
toProto() [3/3]
template<typename T > catena::exception_with_status catena::common::ParamWithValue< T >::toProto (catena::Value & value, const IAuthorizer & authz) const inline override virtual
Serialize the parameter value to protobuf if authorized.
Parameters
value the protobuf object to serialize to.
authz the authorizer object containing the client's scopes.
Implements catena::common::IParam.
References catena::common::ParamWithValue< T >::descriptor_, and catena::common::ParamWithValue< T >::value_.
type()
template<typename T > IParam::ParamType catena::common::ParamWithValue< T >::type () const inline override virtual
Gets the parameters protobuf value type.
Implements catena::common::IParam.
References catena::common::ParamWithValue< T >::descriptor_, and catena::common::IParamDescriptor::type().
validateSetValue()
template<typename T > bool catena::common::ParamWithValue< T >::validateSetValue (const catena::Value & value, Path::Index index, const IAuthorizer & authz, catena::exception_with_status & ans) inline override virtual
Validates a setValue operation without changing the param's value.
Parameters
value The value we want to set the param to.
index The index of the subparam to set (or nullptr if none).
authz The authorizer object to check write permissions with.
ans Catena::exception_with_status output.
Returns
true if valid.
Implements catena::common::IParam.
References catena::INVALID_ARGUMENT, catena::OK, and catena::common::ParamWithValue< T >::validateSetValueMap_.
validateSetValue_() [1/2]
template<typename T > template<typename U , typename V > requires (!meta::IsVector<V>) catena::exception_with_status catena::common::ParamWithValue< T >::validateSetValue_ (std::vector< U > & arrayVal, const V & memVal, const catena::Value & protoVal, Path::Index index, const IAuthorizer & authz) inline protected
Insert/append value to array overload of validateSetValue_.
Parameters
arrayVal The paramWithValue's existing array value.
memVal The value to insert/append.
protoVal The protobuf value memVal was taken from.
index The index to insert the value at. Cannot be Path::kNone and must be within bounds.
authz The authorizer object for checking write permissions.
Returns
catena::exception_with_status.
References catena::common::ParamWithValue< T >::descriptor_, catena::common::IParamDescriptor::getOid(), catena::INVALID_ARGUMENT, catena::common::Path::kEnd, catena::common::Path::kNone, catena::common::IParamDescriptor::max_length(), catena::common::ParamWithValue< T >::mSizeTracker_, catena::OK, catena::OUT_OF_RANGE, catena::common::ParamWithValue< T >::size_(), catena::common::IParamDescriptor::total_length(), catena::common::ParamWithValue< T >::tSizeTracker_, and catena::common::validFromProto().
validateSetValue_() [2/2]
template<typename T > template<typename U , typename V > catena::exception_with_status catena::common::ParamWithValue< T >::validateSetValue_ (U & oldVal, const V & newVal, const catena::Value & protoVal, Path::Index index, const IAuthorizer & authz) inline protected
Default overload of validateSetValue_ used in cases where type(U) == type(V).
Parameters
oldVal The paramWithValue's existing value.
newVal The value to replace oldVal with.
protoVal The protobuf value newVal was taken from.
index The index to insert the value at. Must be Path::kNone.
authz The authorizer object for checking write permissions.
Returns
catena::exception_with_status.
References catena::common::ParamWithValue< T >::descriptor_, catena::common::IParamDescriptor::getOid(), catena::INVALID_ARGUMENT, catena::common::Path::kNone, catena::common::IParamDescriptor::max_length(), catena::common::ParamWithValue< T >::mSizeTracker_, catena::OK, catena::OUT_OF_RANGE, catena::common::ParamWithValue< T >::size_(), and catena::common::validFromProto().
Member Data Documentation
validateSetValueMap_
template<typename T > const std::unordered_map<Kind, std::function<catena::exception_with_status(const catena::Value&, Path::Index, const IAuthorizer&)> > catena::common::ParamWithValue< T >::validateSetValueMap_ protected
A map to help routing to the validateSetValue_ functions above. Protobuf is great in that you need to use a seperate function to get each different type of value.
Parameters
key The value's kind_case().
protoVal The protobuf value object we want passed into validateSetValue_.
index The index to update (or Path::kNone if none).
authz The authorizer object for checking kWrite permissions.
Returns
catena::exception_with_status.
The documentation for this class was generated from the following file:
/home/runner/work/Catena/Catena/sdks/cpp/common/include/ParamWithValue.h