cpp-v0.0.16-15: catena::common::Device Class Reference
catena::common::Device Class Reference
Implements the Device interface defined in the protobuf.
#include <Device.h>
Classes
class DeviceSerializer
DeviceSerializer is a coroutine that serializes the device into a stream of DeviceComponents. This struct manages the state and lifetime of the coroutine. It also provides the interface for resuming the coroutine.
Public Types
using DetailLevel_e = catena::Device_DetailLevel
convenience type aliases to types of objects contained in the device.
using ComponentLanguagePack = catena::DeviceComponent_ComponentLanguagePack
Public Types inherited from catena::common::IDevice
using DetailLevel_e = catena::Device_DetailLevel
convenience type aliases to types of objects contained in the device
using ComponentLanguagePack = catena::DeviceComponent_ComponentLanguagePack
Public Member Functions
Device ()=default
Constructs a new Device object.
Device (uint32_t slot, Device_DetailLevel detail_level, std::vector< std::string > access_scopes, std::string default_scope, bool multi_set_enabled, bool subscriptions)
Constructs a new Device object.
virtual ~Device ()=default
Destroys the Device object.
void slot (const uint32_t slot) override
Set the slot number of the device.
uint32_t slot () const override
Get the slot number of the device.
std::mutex & mutex () override
Gets the device's mutex.
void detail_level (const DetailLevel_e detail_level) override
Sets the default detail level of the device.
DetailLevel_e detail_level () const override
Get the default detail level of the device.
const std::string & getDefaultScope () const override
Gets the device's default scope.
bool subscriptions () const override
Check if subscriptions are enabled for this device.
uint32_t default_max_length () const override
Gets the default max length for this device's array params.
uint32_t default_total_length () const override
Gets the default total length for this device's string array params.
void set_default_max_length (const uint32_t default_max_length) override
Sets the default max length for this device's array params. If default_max_length <= 0, then it reverts default_max_length_ to kDefaultMaxArrayLength.
void set_default_total_length (const uint32_t default_total_length) override
Sets the default total length for this device's array params. If default_total_length <= 0, then it reverts default_total_length_ to kDefaultMaxArrayLength.
void toProto (::catena::Device &dst, const IAuthorizer &authz, bool shallow=true) const override
Creates a protobuf representation of the device.
void toProto (::catena::LanguagePacks &packs) const override
Creates a protobuf representation of the device's language packs.
void toProto (::catena::LanguageList &list) const override
Populates a protobuf LanguageList with the language IDs of the device's supported languages.
bool hasLanguage (const std::string &languageId) const override
Returns true if device supports the specified language.
catena::exception_with_status addLanguage (catena::AddLanguagePayload &language, const IAuthorizer &authz=Authorizer::kAuthzDisabled) override
Adds a language pack to the device. Requires client to have admin:w scope.
catena::exception_with_status removeLanguage (const std::string &languageId, const IAuthorizer &authz=Authorizer::kAuthzDisabled) override
Removes a language pack from the device. Requires client to have admin:w scope. Fails if the language pack was shipped with the device.
catena::exception_with_status getLanguagePack (const std::string &languageId, ComponentLanguagePack &pack) const override
Finds and returns a language pack based on languageId.
std::unique_ptr< IDeviceSerializer > getComponentSerializer (const IAuthorizer &authz, const std::set< std::string > &subscribedOids, catena::Device_DetailLevel dl, bool shallow=false) const override
Gets a serializer for the device.
DeviceSerializer getDeviceSerializer (const IAuthorizer &authz, const std::set< std::string > &subscribedOids, catena::Device_DetailLevel dl, bool shallow=false) const
This is a helper function for the shared IDevice function getComponentSerializer to return a DeviceSerializer object. It can be used on its own if calling from a Device object.
void addItem (const std::string &key, IParam *item) override
add an item to one of the collections owned by the device. Overload for parameters and commands.
void addItem (const std::string &key, IConstraint *item) override
add an item to one of the collections owned by the device. Overload for constraints.
void addItem (const std::string &key, IMenuGroup *item) override
add an item to one of the collections owned by the device. Overload for menu groups.
void addItem (const std::string &key, ILanguagePack *item) override
add an item to one of the collections owned by the device Overload for language packs.
template<typename TAG >
TAG::type * getItem (const std::string &key) const
Gets an item from one of the collections owned by the device.
std::unique_ptr< IParam > getParam (const std::string &fqoid, catena::exception_with_status &status, const IAuthorizer &authz=Authorizer::kAuthzDisabled) const override
Get a parameter by oid with authorization.
std::unique_ptr< IParam > getParam (catena::common::Path &path, catena::exception_with_status &status, const IAuthorizer &authz=Authorizer::kAuthzDisabled) const override
Gets a parameter by oid with authorization.
std::vector< std::unique_ptr< IParam > > getTopLevelParams (catena::exception_with_status &status, const IAuthorizer &authz=Authorizer::kAuthzDisabled) const override
Gets all top level parameters.
std::unique_ptr< IParam > getCommand (const std::string &fqoid, catena::exception_with_status &status, const IAuthorizer &authz=Authorizer::kAuthzDisabled) const override
Gets a command by oid.
bool tryMultiSetValue (catena::MultiSetValuePayload src, catena::exception_with_status &ans, const IAuthorizer &authz=Authorizer::kAuthzDisabled) override
Validates each payload in a multiSetValuePayload without commit changes to param value_s.
catena::exception_with_status commitMultiSetValue (catena::MultiSetValuePayload src, const IAuthorizer &authz) override
Sets the values of a device's parameter's using a MultiSetValuePayload. This function assumes that tryMultiSetValue is called at some point beforehand to validate the call.
catena::exception_with_status setValue (const std::string &jptr, catena::Value &src, const IAuthorizer &authz=Authorizer::kAuthzDisabled) override
Deserialize a protobuf value object into the parameter value pointed to by jptr.
catena::exception_with_status getValue (const std::string &jptr, catena::Value &value, const IAuthorizer &authz=Authorizer::kAuthzDisabled) const override
Serialize the parameter value to protobuf.
bool shouldSendParam (const IParam &param, bool is_subscribed, const IAuthorizer &authz) const override
Check if a parameter should be sent based on detail level and authorization.
vdk::signal< void(const std::string &, const IParam *)> & getValueSetByClient () override
Get the signal emitted when a value is set by the client.
vdk::signal< void(const ILanguagePack *)> & getLanguageAddedPushUpdate () override
Get the signal emitted when a language pack is added to the device.
vdk::signal< void(const std::string &, const IParam *)> & getValueSetByServer () override
Get the signal emitted when a value is set by the server, or business logic.
vdk::signal< void(const std::string &, const IAuthorizer *)> & getDownloadAssetRequest () override
Get the asset request signal.
vdk::signal< void(const std::string &, const IAuthorizer *)> & getUploadAssetRequest () override
Get the upload asset request signal.
vdk::signal< void(const std::string &, const IAuthorizer *)> & getDeleteAssetRequest () override
Get the delete asset request signal.
Public Member Functions inherited from catena::common::IDevice
IDevice ()=default
Constructs a new Device object.
virtual ~IDevice ()=default
Destroys the Device object.
Detailed Description
Implements the Device interface defined in the protobuf.
Member Function Documentation
addItem() [1/4]
void catena::common::Device::addItem (const std::string & key, IConstraint * item) inline override virtual
add an item to one of the collections owned by the device. Overload for constraints.
Parameters
key The item's unique key.
item The item to be added.
Implements catena::common::IDevice.
addItem() [2/4]
void catena::common::Device::addItem (const std::string & key, ILanguagePack * item) inline override virtual
add an item to one of the collections owned by the device Overload for language packs.
Parameters
key The item's unique key
item The item to be added
Implements catena::common::IDevice.
addItem() [3/4]
void catena::common::Device::addItem (const std::string & key, IMenuGroup * item) inline override virtual
add an item to one of the collections owned by the device. Overload for menu groups.
Parameters
key The item's unique key
item The item to be added
Implements catena::common::IDevice.
addItem() [4/4]
void catena::common::Device::addItem (const std::string & key, IParam * item) inline override virtual
add an item to one of the collections owned by the device. Overload for parameters and commands.
Parameters
key The item's unique key.
item The item to be added.
Implements catena::common::IDevice.
References catena::common::IParam::getDescriptor(), and catena::common::IParamDescriptor::isCommand().
addLanguage()
catena::exception_with_status catena::common::Device::addLanguage (catena::AddLanguagePayload & language, const IAuthorizer & authz = Authorizer::kAuthzDisabled) override virtual
Adds a language pack to the device. Requires client to have admin:w scope.
Parameters
language The language to add to the device.
authz The authorizer object containing client's scopes.
Returns
An exception_with_status with status set OK if successful, otherwise an error.
Implements catena::common::IDevice.
commitMultiSetValue()
catena::exception_with_status catena::common::Device::commitMultiSetValue (catena::MultiSetValuePayload src, const IAuthorizer & authz) override virtual
Sets the values of a device's parameter's using a MultiSetValuePayload. This function assumes that tryMultiSetValue is called at some point beforehand to validate the call.
Parameters
src The MultiSetValuePayload to update the device with.
authz The Authroizer with the client's scopes.
Returns
An exception_with_status with status set OK if successful.
Implements catena::common::IDevice.
default_max_length()
uint32_t catena::common::Device::default_max_length () const inline override virtual
Gets the default max length for this device's array params.
Returns
The default max length for this device's array params.
Implements catena::common::IDevice.
default_total_length()
uint32_t catena::common::Device::default_total_length () const inline override virtual
Gets the default total length for this device's string array params.
Returns
The default total length for this device's string array params.
Implements catena::common::IDevice.
detail_level() [1/2]
DetailLevel_e catena::common::Device::detail_level () const inline override virtual
Get the default detail level of the device.
Returns
The device's default detail level.
Implements catena::common::IDevice.
detail_level() [2/2]
void catena::common::Device::detail_level (const DetailLevel_e detail_level) inline override virtual
Sets the default detail level of the device.
Parameters
detail_level the new default detail level of the device.
Implements catena::common::IDevice.
References detail_level().
getCommand()
std::unique_ptr< IParam > catena::common::Device::getCommand (const std::string & fqoid, catena::exception_with_status & status, const IAuthorizer & authz = Authorizer::kAuthzDisabled) const override virtual
Gets a command by oid.
Parameters
fqoid The fully qualified oid of the command.
authz The authorizer object.
status Will contain an error message if the command does not exist.
Returns
A unique pointer to the command, or nullptr if it does not exist.
Implements catena::common::IDevice.
getComponentSerializer()
std::unique_ptr< IDeviceSerializer > catena::common::Device::getComponentSerializer (const IAuthorizer & authz, const std::set< std::string > & subscribedOids, catena::Device_DetailLevel dl, bool shallow = false) const override virtual
Gets a serializer for the device.
Parameters
authz The authorizer object containing the scopes of the client.
subscribedOids The oids of the subscribed parameters.
dl The detail level to retrieve information in.
shallow If true, the device will be returned in parts, otherwise the whole device will be returned in one message.
Returns
A DeviceSerializer object.
Implements catena::common::IDevice.
getDefaultScope()
const std::string & catena::common::Device::getDefaultScope () const inline override virtual
Gets the device's default scope.
Returns
The device's default scope.
Implements catena::common::IDevice.
getDeleteAssetRequest()
vdk::signal< void(const std::string &, const IAuthorizer *)> & catena::common::Device::getDeleteAssetRequest () inline override virtual
Get the delete asset request signal.
Returns
The signal.
Implements catena::common::IDevice.
getDeviceSerializer()
DeviceSerializer catena::common::Device::getDeviceSerializer (const IAuthorizer & authz, const std::set< std::string > & subscribedOids, catena::Device_DetailLevel dl, bool shallow = false) const
This is a helper function for the shared IDevice function getComponentSerializer to return a DeviceSerializer object. It can be used on its own if calling from a Device object.
Parameters
authz The authorizer object containing the scopes of the client
subscribedOids The oids of the subscribed parameters
dl The detail level to retrieve information in.
shallow If true, the device will be returned in parts, otherwise the whole device will be returned in one message
getDownloadAssetRequest()
vdk::signal< void(const std::string &, const IAuthorizer *)> & catena::common::Device::getDownloadAssetRequest () inline override virtual
Get the asset request signal.
Returns
The signal.
Implements catena::common::IDevice.
getItem()
template<typename TAG > TAG::type * catena::common::Device::getItem (const std::string & key) const inline
Gets an item from one of the collections owned by the device.
Returns
nullptr if the item is not found, otherwise the item.
References GET_ITEM.
getLanguageAddedPushUpdate()
vdk::signal< void(const ILanguagePack *)> & catena::common::Device::getLanguageAddedPushUpdate () inline override virtual
Get the signal emitted when a language pack is added to the device.
Returns
The signal.
Implements catena::common::IDevice.
getLanguagePack()
catena::exception_with_status catena::common::Device::getLanguagePack (const std::string & languageId, ComponentLanguagePack & pack) const override virtual
Finds and returns a language pack based on languageId.
Parameters
languageId The language id of the language pack to get (e.g. "en").
pack Output var containing the found LanguagePack.
Returns
exception_with_status containing the status of the operation.
Implements catena::common::IDevice.
getParam() [1/2]
std::unique_ptr< IParam > catena::common::Device::getParam (catena::common::Path & path, catena::exception_with_status & status, const IAuthorizer & authz = Authorizer::kAuthzDisabled) const override virtual
Gets a parameter by oid with authorization.
Parameters
path The full path to the parameter.
status Will contain an error message if the parameter does not exist.
authz The authorizer object to test read permission with.
Returns
a unique pointer to the parameter, or nullptr if it does not exist.
Implements catena::common::IDevice.
getParam() [2/2]
std::unique_ptr< IParam > catena::common::Device::getParam (const std::string & fqoid, catena::exception_with_status & status, const IAuthorizer & authz = Authorizer::kAuthzDisabled) const override virtual
Get a parameter by oid with authorization.
Parameters
fqoid The fully qualified oid of the parameter.
status will contain an error message if the parameter does not exist.
authz The IAuthorizer to test read permission with.
Returns
a unique pointer to the parameter, or nullptr if it does not exist.
Implements catena::common::IDevice.
getTopLevelParams()
std::vector< std::unique_ptr< IParam > > catena::common::Device::getTopLevelParams (catena::exception_with_status & status, const IAuthorizer & authz = Authorizer::kAuthzDisabled) const override virtual
Gets all top level parameters.
Parameters
status The status of the operation.
authz The authorizer object.
Returns
A vector of unique pointers to the top level parameters.
Implements catena::common::IDevice.
getUploadAssetRequest()
vdk::signal< void(const std::string &, const IAuthorizer *)> & catena::common::Device::getUploadAssetRequest () inline override virtual
Get the upload asset request signal.
Returns
The signal.
Implements catena::common::IDevice.
getValue()
catena::exception_with_status catena::common::Device::getValue (const std::string & jptr, catena::Value & value, const IAuthorizer & authz = Authorizer::kAuthzDisabled) const override virtual
Serialize the parameter value to protobuf.
Parameters
jptr Json pointer to the part of the device model to serialize.
dst the protobuf value to serialize to.
authz The IAuthorizer to test read permission with.
Returns
An exception_with_status with status set OK if successful, otherwise an error.
Implements catena::common::IDevice.
getValueSetByClient()
vdk::signal< void(const std::string &, const IParam *)> & catena::common::Device::getValueSetByClient () inline override virtual
Get the signal emitted when a value is set by the client.
Returns
The signal.
Implements catena::common::IDevice.
getValueSetByServer()
vdk::signal< void(const std::string &, const IParam *)> & catena::common::Device::getValueSetByServer () inline override virtual
Get the signal emitted when a value is set by the server, or business logic.
Returns
The signal.
Implements catena::common::IDevice.
hasLanguage()
bool catena::common::Device::hasLanguage (const std::string & languageId) const inline override virtual
Returns true if device supports the specified language.
Parameters
languageId The language id to check for (e.g. "en").
Returns
True if the device supports specified language pack.
Implements catena::common::IDevice.
mutex()
std::mutex & catena::common::Device::mutex () inline override virtual
Gets the device's mutex.
Returns
The device's mutex.
Implements catena::common::IDevice.
removeLanguage()
catena::exception_with_status catena::common::Device::removeLanguage (const std::string & languageId, const IAuthorizer & authz = Authorizer::kAuthzDisabled) override virtual
Removes a language pack from the device. Requires client to have admin:w scope. Fails if the language pack was shipped with the device.
Parameters
language The language to remove from the device.
authz The authorizer object containing client's scopes.
Returns
An exception_with_status with status set OK if successful, otherwise an error.
Implements catena::common::IDevice.
set_default_max_length()
void catena::common::Device::set_default_max_length (const uint32_t default_max_length) inline override virtual
Sets the default max length for this device's array params. If default_max_length <= 0, then it reverts default_max_length_ to kDefaultMaxArrayLength.
Parameters
default_max_length The device's new default max length.
Implements catena::common::IDevice.
References default_max_length(), and catena::common::kDefaultMaxArrayLength.
set_default_total_length()
void catena::common::Device::set_default_total_length (const uint32_t default_total_length) inline override virtual
Sets the default total length for this device's array params. If default_total_length <= 0, then it reverts default_total_length_ to kDefaultMaxArrayLength.
Parameters
default_total_length The device's new default total length.
Implements catena::common::IDevice.
References default_total_length(), and catena::common::kDefaultMaxArrayLength.
setValue()
catena::exception_with_status catena::common::Device::setValue (const std::string & jptr, catena::Value & src, const IAuthorizer & authz = Authorizer::kAuthzDisabled) override virtual
Deserialize a protobuf value object into the parameter value pointed to by jptr.
Parameters
jptr Json pointer to the part of the device model to update.
src The value to update the parameter with.
authz The IAuthorizer to test with.
Returns
An exception_with_status with status set OK if successful, otherwise an error.
This method essentially redirects the input values to tryMultiSetValue() and commitMultiSetValue(). It remains to support the old way of setting values.
Implements catena::common::IDevice.
shouldSendParam()
bool catena::common::Device::shouldSendParam (const IParam & param, bool is_subscribed, const IAuthorizer & authz) const override virtual
Check if a parameter should be sent based on detail level and authorization.
Parameters
param The parameter to check.
is_subscribed True if the parameter is subscribed, false otherwise.
authz The authorizer object.
Returns
True if the parameter should be sent, false otherwise.
Implements catena::common::IDevice.
slot() [1/2]
uint32_t catena::common::Device::slot () const inline override virtual
Get the slot number of the device.
Returns
The device's slot number.
Implements catena::common::IDevice.
slot() [2/2]
void catena::common::Device::slot (const uint32_t slot) inline override virtual
Set the slot number of the device.
Parameters
slot The device's new slot number.
Implements catena::common::IDevice.
References slot().
subscriptions()
bool catena::common::Device::subscriptions () const inline override virtual
Check if subscriptions are enabled for this device.
Returns
True if subscriptions are enabled, False otherwise.
Implements catena::common::IDevice.
toProto() [1/3]
void catena::common::Device::toProto (::catena::Device & dst, const IAuthorizer & authz, bool shallow = true) const override virtual
Creates a protobuf representation of the device.
Parameters
dst the protobuf representation of the device.
authz The authorizer object containing client's scopes.
shallow if true, only the top-level info is copied, params, commands etc are not copied. Design intent is to permit large models to stream their parameters instead of sending a huge device model in one big lump.
N.B. This method is not thread-safe. It is the caller's responsibility to ensure that the device is not modified while this method is running. This class provides a LockGuard helper class to make this easier.
Implements catena::common::IDevice.
toProto() [2/3]
void catena::common::Device::toProto (::catena::LanguageList & list) const override virtual
Populates a protobuf LanguageList with the language IDs of the device's supported languages.
Parameters
list The protobuf language list object.
Implements catena::common::IDevice.
toProto() [3/3]
void catena::common::Device::toProto (::catena::LanguagePacks & packs) const override virtual
Creates a protobuf representation of the device's language packs.
Parameters
packs the protobuf representation of the language packs.
Implements catena::common::IDevice.
tryMultiSetValue()
bool catena::common::Device::tryMultiSetValue (catena::MultiSetValuePayload src, catena::exception_with_status & ans, const IAuthorizer & authz = Authorizer::kAuthzDisabled) override virtual
Validates each payload in a multiSetValuePayload without commit changes to param value_s.
Parameters
src The MultiSetValuePayload to validate.
ans The exception_with_status to return.
authz The IAuthorizer to test with.
Returns
True if the call is valid.
Implements catena::common::IDevice.
The documentation for this class was generated from the following file:
/home/runner/work/Catena/Catena/sdks/cpp/common/include/Device.h