cpp-v0.0.16-15: catena::common::ParamDescriptor Class Reference
catena::common::ParamDescriptor Class Reference
ParamDescriptor provides information about a parameter as well as command definition and execution functions.
#include <ParamDescriptor.h>
Classes
class CommandResponder
CommandResponder is a coroutine that allows commands to return multiple responses throughout its execution's lifetime.
Public Types
using OidAliases = std::vector< std::string >
Public Member Functions
ParamDescriptor ()=delete
ParamDescriptor does not have a default constructor.
ParamDescriptor (ParamDescriptor &value)=delete
ParamDescriptor does not have copy semantics.
ParamDescriptor & operator= (const ParamDescriptor &value)=delete
ParamDescriptor does not have copy semantics.
ParamDescriptor (ParamDescriptor &&value)=default
ParamDescriptor has move semantics.
ParamDescriptor & operator= (ParamDescriptor &&value)=default
ParamDescriptor has move semantics.
virtual ~ParamDescriptor ()=default
default destructor
ParamDescriptor (catena::ParamType type, const OidAliases &oid_aliases, const PolyglotText::ListInitializer name, const std::string &widget, const std::string &scope, bool read_only, const std::string &oid, const std::string &template_oid, catena::common::IConstraint *constraint, bool isCommand, bool response, IDevice &dm, uint32_t max_length, std::size_t total_length, uint32_t precision, bool minimal_set, IParamDescriptor *parent)
the main constructor
ParamType type () const override
get the parameter type
const PolyglotText::DisplayStrings & name () const override
get the parameter name
const std::string & getOid () const override
get the parameter oid
void setOid (const std::string &oid) override
set the parameter oid
bool hasTemplateOid () const override
return true if the parameter has a template oid
const std::string & templateOid () const override
get the parameter's template oid
bool readOnly () const override
return the readOnly status of the parameter
void readOnly (bool flag) override
set the readOnly status of the parameter
const std::string & getScope () const override
get the access scope of the parameter
bool minimalSet () const override
get the minimal set status of the parameter
void setMinimalSet (bool flag) override
set the minimal set status of the parameter
uint32_t max_length () const override
Returns the max length an array/string parameter can be. If max length is not set in the .JSON file, then the default value of 1024 is used. The default value can also be configured with the command line argument "--default_max_length=#".
std::size_t total_length () const override
Returns the total length the sum of all strings in a string_array parameter can be. If max length is not set in the .JSON file, then the default value of 1024 is used. The default value can also be configured with the command line argument "--default_total_length=#".
uint32_t precision () const override
Returns the precision of the parameter.
void toProto (catena::Param &param, const IAuthorizer &authz) const override
serialize param meta data in to protobuf message
void toProto (catena::ParamInfo &paramInfo, const IAuthorizer &authz) const override
serialize param meta data in to protobuf message
const std::string & name (const std::string &language) const override
get the parameter name by language
void addSubParam (const std::string &oid, IParamDescriptor *item) override
add an item to one of the collections owned by the device
IParamDescriptor & getSubParam (const std::string &oid) const override
gets a sub parameter's paramDescriptor
const std::unordered_map< std::string, IParamDescriptor * > & getAllSubParams () const override
return all sub parameters
const catena::common::IConstraint * getConstraint () const override
get a constraint by oid
void defineCommand (std::function< std::unique_ptr< ICommandResponder >(const catena::Value &, const bool)> commandImpl) override
Defines the command implementation if the parameter is a command.
std::unique_ptr< ICommandResponder > executeCommand (const catena::Value &value, const bool respond) override
Executes the command implementation.
bool isCommand () const override
return true if this is a command parameter
Public Member Functions inherited from catena::common::IParamDescriptor
IParamDescriptor ()=default
ParamDescriptor does not have a default constructor.
IParamDescriptor (IParamDescriptor &value)=delete
ParamDescriptor does not have copy semantics.
IParamDescriptor & operator= (const IParamDescriptor &value)=delete
ParamDescriptor does not have copy semantics.
IParamDescriptor (IParamDescriptor &&value)=default
ParamDescriptor has move semantics.
IParamDescriptor & operator= (IParamDescriptor &&value)=default
ParamDescriptor has move semantics.
virtual ~IParamDescriptor ()=default
default destructor
Detailed Description
ParamDescriptor provides information about a parameter as well as command definition and execution functions.
Constructor & Destructor Documentation
ParamDescriptor()
catena::common::ParamDescriptor::ParamDescriptor (catena::ParamType type, const OidAliases & oid_aliases, const PolyglotText::ListInitializer name, const std::string & widget, const std::string & scope, bool read_only, const std::string & oid, const std::string & template_oid, catena::common::IConstraint * constraint, bool isCommand, bool response, IDevice & dm, uint32_t max_length, std::size_t total_length, uint32_t precision, bool minimal_set, IParamDescriptor * parent) inline
the main constructor
Parameters
type the parameter type
oid_aliases the parameter's oid aliases
name the parameter's name
widget the parameter's widget
scope the parameter's access scope
read_only the parameter's read-only status
oid the parameter's oid
template_oid the parameter's template oid
constraint the parameter's constraint
isCommand the parameter's command status
response true if the command returns a response when executed
dm the device that the parameter belongs to
max_length the parameter's maximum length
total_length the parameter's total length
precision the number of decimal places to display for floats
minimalSet the parameter's minimal set status
parent the parent parameter
References catena::common::IParamDescriptor::addSubParam(), and setOid().
Member Function Documentation
addSubParam()
void catena::common::ParamDescriptor::addSubParam (const std::string & oid, IParamDescriptor * item) inline override virtual
add an item to one of the collections owned by the device
Template Parameters
TAG identifies the collection to which the item will be added
Parameters
key item's unique key
item the item to be added
Implements catena::common::IParamDescriptor.
defineCommand()
void catena::common::ParamDescriptor::defineCommand (std::function< std::unique_ptr< ICommandResponder >(const catena::Value &, const bool)> commandImpl) inline override virtual
Defines the command implementation if the parameter is a command.
Parameters
commandImpl A function that takes a protobuf Value and a response bool and returns a CommandResponder.
The passed function will be executed when executeCommand is called on this param object. If this is not a command parameter, an exception will be thrown.
Implements catena::common::IParamDescriptor.
executeCommand()
std::unique_ptr< ICommandResponder > catena::common::ParamDescriptor::executeCommand (const catena::Value & value, const bool respond) inline override virtual
Executes the command implementation.
Parameters
value the value to pass to the command implementation
respond Flag indicating whether the command should respond with a CommandResponse.
Returns
The CommandResponder from the command implementation
If executeCommand is called for a command that has not been defined, then the returned command response will be an exception with type UNIMPLEMENTED
Implements catena::common::IParamDescriptor.
getAllSubParams()
const std::unordered_map< std::string, IParamDescriptor * > & catena::common::ParamDescriptor::getAllSubParams () const inline override virtual
return all sub parameters
Returns
a map of all sub parameters
Implements catena::common::IParamDescriptor.
getConstraint()
const catena::common::IConstraint * catena::common::ParamDescriptor::getConstraint () const inline override virtual
get a constraint by oid
Implements catena::common::IParamDescriptor.
getOid()
const std::string & catena::common::ParamDescriptor::getOid () const inline override virtual
get the parameter oid
Implements catena::common::IParamDescriptor.
getScope()
const std::string & catena::common::ParamDescriptor::getScope () const override virtual
get the access scope of the parameter
Implements catena::common::IParamDescriptor.
getSubParam()
IParamDescriptor & catena::common::ParamDescriptor::getSubParam (const std::string & oid) const inline override virtual
gets a sub parameter's paramDescriptor
Returns
ParamDescriptor of the sub parameter
Implements catena::common::IParamDescriptor.
hasTemplateOid()
bool catena::common::ParamDescriptor::hasTemplateOid () const inline override virtual
return true if the parameter has a template oid
Implements catena::common::IParamDescriptor.
isCommand()
bool catena::common::ParamDescriptor::isCommand () const inline override virtual
return true if this is a command parameter
Implements catena::common::IParamDescriptor.
max_length()
uint32_t catena::common::ParamDescriptor::max_length () const override virtual
Returns the max length an array/string parameter can be. If max length is not set in the .JSON file, then the default value of 1024 is used. The default value can also be configured with the command line argument "--default_max_length=#".
Returns
max_length_
Implements catena::common::IParamDescriptor.
minimalSet()
bool catena::common::ParamDescriptor::minimalSet () const inline override virtual
get the minimal set status of the parameter
Implements catena::common::IParamDescriptor.
name() [1/2]
const PolyglotText::DisplayStrings & catena::common::ParamDescriptor::name () const inline override virtual
get the parameter name
Implements catena::common::IParamDescriptor.
References catena::common::PolyglotText::displayStrings().
name() [2/2]
const std::string & catena::common::ParamDescriptor::name (const std::string & language) const override virtual
get the parameter name by language
Parameters
language the language to get the name for
Returns
the name in the specified language, or an empty string if the language is not found
Implements catena::common::IParamDescriptor.
precision()
uint32_t catena::common::ParamDescriptor::precision () const inline override virtual
Returns the precision of the parameter.
Implements catena::common::IParamDescriptor.
readOnly() [1/2]
bool catena::common::ParamDescriptor::readOnly () const inline override virtual
return the readOnly status of the parameter
Implements catena::common::IParamDescriptor.
readOnly() [2/2]
void catena::common::ParamDescriptor::readOnly (bool flag) inline override virtual
set the readOnly status of the parameter
Implements catena::common::IParamDescriptor.
setMinimalSet()
void catena::common::ParamDescriptor::setMinimalSet (bool flag) inline override virtual
set the minimal set status of the parameter
Implements catena::common::IParamDescriptor.
setOid()
void catena::common::ParamDescriptor::setOid (const std::string & oid) inline override virtual
set the parameter oid
Implements catena::common::IParamDescriptor.
templateOid()
const std::string & catena::common::ParamDescriptor::templateOid () const inline override virtual
get the parameter's template oid
Implements catena::common::IParamDescriptor.
toProto() [1/2]
void catena::common::ParamDescriptor::toProto (catena::Param & param, const IAuthorizer & authz) const override virtual
serialize param meta data in to protobuf message
Parameters
param the protobuf message to serialize to
authz the authorization information
this function will populate all non-value fields of the protobuf param message with the information from the ParamDescriptor
Implements catena::common::IParamDescriptor.
toProto() [2/2]
void catena::common::ParamDescriptor::toProto (catena::ParamInfo & paramInfo, const IAuthorizer & authz) const override virtual
serialize param meta data in to protobuf message
Parameters
paramInfo the protobuf message to serialize to
authz the authorization information
this function will populate all non-value fields of the protobuf param message with the information from the ParamDescriptor
Implements catena::common::IParamDescriptor.
total_length()
std::size_t catena::common::ParamDescriptor::total_length () const override virtual
Returns the total length the sum of all strings in a string_array parameter can be. If max length is not set in the .JSON file, then the default value of 1024 is used. The default value can also be configured with the command line argument "--default_total_length=#".
Returns
total_length_
Implements catena::common::IParamDescriptor.
type()
ParamType catena::common::ParamDescriptor::type () const inline override virtual
get the parameter type
Implements catena::common::IParamDescriptor.
The documentation for this class was generated from the following file:
/home/runner/work/Catena/Catena/sdks/cpp/common/include/ParamDescriptor.h