Catena_cpp-v0.0.1: catena::full::ParamAccessor Class Reference
catena::full::ParamAccessor Class Reference
Public Types
using Mutex = DeviceModel::Mutex
Mutexlock type.
using Getter = catena::patterns::Functory< catena::Value::KindCase, void, void *, const catena::Value * >
type alias for the getter function for scalar types
using Setter = catena::patterns::Functory< catena::Value::KindCase, void, catena::Value *, const void * >
type alias for the setter Functory for scalar types
using GetterAt = catena::patterns::Functory< catena::Value::KindCase, void, void *, const catena::Value *, const ParamIndex >
type alias for the getter function for vector types
using SetterAt = catena::patterns::Functory< catena::Value::KindCase, void, catena::Value *, const void *, const ParamIndex >
type alias for the setter Functory for vector types
using VariantInfoGetter = catena::patterns::Functory< std::type_index, const catena::full::VariantInfo & >
type alias for the function that gets the VariantInfo for a type
using ValueGetter = catena::patterns::Functory< catena::Value::KindCase, void, Value *, const Value & >
type alias for the function that gets values from the device model for delivery to attached clients
using ValueSetter = catena::patterns::Functory< catena::Value::KindCase, void, Value &, const Value & >
type alias for the function that sets values in the device model in response to client requests
using ValueGetterAt = catena::patterns::Functory< catena::Value::KindCase, void, Value *, const Value &, ParamIndex >
type alias for the function that gets values from the device model for delivery to attached clients
using ValueSetterAt = catena::patterns::Functory< catena::Value::KindCase, void, Value &, const Value &, ParamIndex >
type alias for the function that sets values in the device model in response to client requests
Public Member Functions
ParamAccessor (DeviceModel &dm, DeviceModel::ParamAccessorData &pad, const std::string &oid, const std::string &scope)
Construct a new ParamAccessor object.
ParamAccessor ()=delete
ParamAccessor has no default constructor.
ParamAccessor (const ParamAccessor &other)=default
ParamAccessor copy constructor.
ParamAccessor & operator= (const ParamAccessor &rhs)=default
ParamAccessor copy assignment.
ParamAccessor (ParamAccessor &&other)=default
ParamAccessor move constructor.
ParamAccessor & operator= (ParamAccessor &&rhs)=default
ParamAccessor move assignment.
template<bool Threadsafe = true>
const Value & value () const
get accessor to the value of the parameter
template<bool Threadsafe>
std::unique_ptr< ParamAccessor > subParam (const std::string &fieldName)
get accessor to sub-parameter matching fieldName
template<bool Threadsafe>
const std::unique_ptr< ParamAccessor > subParam (const std::string &fieldName) const
get accessor to sub-parameter matching fieldName, const version
template<bool Threadsafe = true, typename V >
void getValue (V &dst) const
Get the value of the stored parameter to which objects of this class provide access.
template<bool Threadsafe = true, typename V >
void getValue (V &dst, const ParamIndex idx) const
Get the value of the stored parameter to which this object provides access from an array with the specified index.
template<bool Threadsafe = true, typename V >
void setValue (const V &src)
Set the value of the stored parameter to which this object provides access.
template<bool Threadsafe = true, typename V >
void setValue (const V &src, const ParamIndex idx)
Set the value of the stored parameter to which this object provides access.
template<bool Threadsafe = true>
void getValue (Value *dst) const
get the parameter's value packaged as a catena::Value object for sending to a client.
template<bool Threadsafe = true>
void getValue (Value *dst, ParamIndex idx, std::vector< std::string > &clientScopes) const
get the parameter's value packaged as a catena::Value object for sending to a client.
void setValue (const std::string &peer, const Value &src)
set the parameter's value packaged as a catena::Value object most likely received from client
void setValue (const std::string &peer, const Value &src, ParamIndex idx, std::vector< std::string > &clientScopes)
set the parameter's value packaged as a catena::Value object most likely received from client
void getParam (catena::DeviceComponent_ComponentParam *dst, std::vector< std::string > &clientScopes) const
get the parameter as a device component with unauthorized fields removed
bool checkScope (const std::vector< std::string > &clientScopes) const
check if the client is authorized to access the parameter
bool checkScope (const std::vector< std::string > &clientScopes, const std::string &paramScope) const
check if the client is authorized to access the parameter
const std::string & oid () const
get the parameter's fully qualified object id
size_t id () const
get the parameter's unique id
bool operator== (const ParamAccessor &rhs) const
comparison operator, returns true if the 2 ids are equal
bool isList () const
returns true if the param is an array (list in protobuf) type.
Constructor & Destructor Documentation
ParamAccessor() [1/3]
catena::full::ParamAccessor::ParamAccessor (DeviceModel & dm, DeviceModel::ParamAccessorData & pad, const std::string & oid, const std::string & scope)
Construct a new ParamAccessor object.
Parameters
dm the parent device model.
pad the data to initialize the param accessor
ParamAccessor() [2/3]
catena::full::ParamAccessor::ParamAccessor (const ParamAccessor & other) default
ParamAccessor copy constructor.
Parameters
other
ParamAccessor() [3/3]
catena::full::ParamAccessor::ParamAccessor (ParamAccessor && other) default
ParamAccessor move constructor.
Parameters
other
Member Function Documentation
checkScope() [1/2]
bool catena::full::ParamAccessor::checkScope (const std::vector< std::string > & clientScopes) const
check if the client is authorized to access the parameter
Parameters
clientScopes the scopes of the client making the request
Returns
true if the client is authorized, false otherwise
Todo:
add option to check scope for write access
checkScope() [2/2]
bool catena::full::ParamAccessor::checkScope (const std::vector< std::string > & clientScopes, const std::string & paramScope) const
check if the client is authorized to access the parameter
Parameters
clientScopes the scopes of the client making the request
paramScope the scope of the parameter to be accessed
Returns
true if the client is authorized, false otherwise
Todo:
add option to check scope for write access
getParam()
void catena::full::ParamAccessor::getParam (catena::DeviceComponent_ComponentParam * dst, std::vector< std::string > & clientScopes) const
get the parameter as a device component with unauthorized fields removed
Parameters
dst [out] a parameter component with unathorized fields removed
clientScopes [in] the scopes of the client requesting the parameter
Exceptions
catena::exception_with_status catena::Status::PERMISSION_DENIED if the client is not authorized
getValue() [1/4]
template<bool Threadsafe = true, typename V > void catena::full::ParamAccessor::getValue (V & dst) const inline
Get the value of the stored parameter to which objects of this class provide access.
Exceptions
catena::exception_with_status catena::Status::UNIMPLEMENTED if support for V is not implemented, or with catena::Status::UNKNOWN if an unknown exception is thrown is encountered. Other catena::exception_with_status exceptions are re-thrown with no change to their status.
Template Parameters
V type of the value stored by the param. This must be a native type.
Parameters
dst reference to the destination object written to by this method.
References BAD_STATUS, catena::patterns::Singleton< Functory< K, R, Ms... > >::getInstance(), catena::INVALID_ARGUMENT, and catena::full::VariantInfo::members.
getValue() [2/4]
template<bool Threadsafe = true, typename V > void catena::full::ParamAccessor::getValue (V & dst, const ParamIndex idx) const inline
Get the value of the stored parameter to which this object provides access from an array with the specified index.
Exceptions
catena::exception_with_status catena::Status::UNIMPLEMENTED if support for objects of type V is not supported, or with catena::Status::UNKNOWN if an unknown exception is encountered, or catena::Status::RANGE_ERROR if the index is out of range.
Template Parameters
V type of the value stored by the param. This must be a native type.
Parameters
dst reference to the destination object written to by this method.
idx index into the array
References catena::patterns::Singleton< Functory< K, R, Ms... > >::getInstance(), and catena::full::getKindCase().
getValue() [3/4]
template<bool Threadsafe = true> void catena::full::ParamAccessor::getValue (Value * dst) const inline
get the parameter's value packaged as a catena::Value object for sending to a client.
Parameters
dst [out] destination for the value
idx [in] index into the array, if set to kParamEnd, the entire array is returned
Exceptions
catena::exception_with_status catena::Status::UNIMPLEMENTED if support for the parameter type is not implemented, or with catena::Status::UNKNOWN if an unknown exception is encountered, or with catena::Status::RANGE_ERROR if the index is out of range.
Template Parameters
Threadsafe if true, the method will assert the DeviceModel's mutex. If false, no lock is asserted - use when making recursive calls to avoid deadlock.
References catena::patterns::Singleton< Functory< K, R, Ms... > >::getInstance(), and value().
getValue() [4/4]
template<bool Threadsafe = true> void catena::full::ParamAccessor::getValue (Value * dst, ParamIndex idx, std::vector< std::string > & clientScopes) const inline
get the parameter's value packaged as a catena::Value object for sending to a client.
Parameters
dst [out] destination for the value
idx [in] index into the array, if set to kParamEnd, the entire array is returned
clientScopes [in] the scopes of the client requesting the value
Exceptions
catena::exception_with_status catena::Status::UNIMPLEMENTED if support for the parameter type is not implemented, or with catena::Status::UNKNOWN if an unknown exception is encountered, or with catena::Status::RANGE_ERROR if the index is out of range.
catena::exception_with_status catena::Status::PERMISSION_DENIED if the client is not authorized
Template Parameters
Threadsafe if true, the method will assert the DeviceModel's mutex. If false, no lock is asserted - use when making recursive calls to avoid deadlock.
References BAD_STATUS, and catena::PERMISSION_DENIED.
operator=() [1/2]
ParamAccessor& catena::full::ParamAccessor::operator= (const ParamAccessor & rhs) default
ParamAccessor copy assignment.
Parameters
rhs
operator=() [2/2]
ParamAccessor& catena::full::ParamAccessor::operator= (ParamAccessor && rhs) default
ParamAccessor move assignment.
Parameters
rhs,right hand side of the equals sign
setValue() [1/4]
void catena::full::ParamAccessor::setValue (const std::string & peer, const Value & src)
set the parameter's value packaged as a catena::Value object most likely received from client
Parameters
dst [out] destination for the value
idx [in] index into the array, if set to kParamEnd, the entire array is returned
Exceptions
catena::exception_with_status catena::Status::UNIMPLEMENTED if support for the parameter type is not implemented, or with catena::Status::UNKNOWN if an unknown exception is encountered, or with catena::Status::RANGE_ERROR if the index is out of range.
Threadsafe - asserts a lock on the DeviceModel's mutex.
setValue() [2/4]
void catena::full::ParamAccessor::setValue (const std::string & peer, const Value & src, ParamIndex idx, std::vector< std::string > & clientScopes)
set the parameter's value packaged as a catena::Value object most likely received from client
Parameters
dst [out] destination for the value
idx [in] index into the array, if set to kParamEnd, the entire array is returned
clientScopes [in] the scopes of the client requesting the value
Exceptions
catena::exception_with_status catena::Status::UNIMPLEMENTED if support for the parameter type is not implemented, or with catena::Status::UNKNOWN if an unknown exception is encountered, or with catena::Status::RANGE_ERROR if the index is out of range.
Threadsafe - asserts a lock on the DeviceModel's mutex.
setValue() [3/4]
template<bool Threadsafe = true, typename V > void catena::full::ParamAccessor::setValue (const V & src) inline
Set the value of the stored parameter to which this object provides access.
Exceptions
catena::exception_with_status catena::Status::UNIMPLEMENTED if support for V is not implemented, or with catena::Status::UNKNOWN if an unknown exception is thrown is encountered. Other catena::exception_with_status exceptions are re-thrown with no change to their status.
Template Parameters
V type of the value stored by the param. This must be a native type.
References catena::patterns::Singleton< Functory< K, R, Ms... > >::getInstance(), catena::full::VariantInfo::lookup, and catena::full::VariantInfo::members.
setValue() [4/4]
template<bool Threadsafe = true, typename V > void catena::full::ParamAccessor::setValue (const V & src, const ParamIndex idx) inline
Set the value of the stored parameter to which this object provides access.
Exceptions
catena::exception_with_status catena::Status::UNIMPLEMENTED if support for V is not implemented, or with catena::Status::UNKNOWN if an unknown exception is thrown is encountered. Other catena::exception_with_status exceptions are re-thrown with no change to their status.
Template Parameters
V type of the value stored by the param. This must be a native type.
Threadsafe if true, the method will assert the DeviceModel's mutex.
Parameters
src the value to set the parameter owned by the ParamAccessor to.
idx index into the array, if set to kParamEnd, the value is appended to the array
References catena::patterns::Singleton< Functory< K, R, Ms... > >::getInstance(), and catena::full::getKindCase().
subParam() [1/2]
template<bool Threadsafe> std::unique_ptr<ParamAccessor> catena::full::ParamAccessor::subParam (const std::string & fieldName) inline
get accessor to sub-parameter matching fieldName
Parameters
fieldName name of the sub-parameter
Returns
unique_ptr to ParamAccessor interface
Exceptions
catena::exception_with_status if fieldName is not a sub-parameter
catena::exception_with_status if fieldName is not a struct or variant type
Note that the value element of the returned sub-param references the appropriate part of the parent's value element. This is because the value element in the child param descriptor is not part of the active value of the larger object. If even present, it's used as the default value for the matching part of the parent's value object.
This method is threadsafe because it asserts the DeviceModel's mutex.
References BAD_STATUS, catena::INVALID_ARGUMENT, and value().
subParam() [2/2]
template<bool Threadsafe> const std::unique_ptr<ParamAccessor> catena::full::ParamAccessor::subParam (const std::string & fieldName) const inline
get accessor to sub-parameter matching fieldName, const version
Parameters
fieldName name of the sub-parameter
Returns
unique_ptr to ParamAccessor interface
Exceptions
catena::exception_with_status if fieldName is not a sub-parameter
catena::exception_with_status if fieldName is not a struct or variant type
Note that the value element of the returned sub-param references the appropriate part of the parent's value element. This is because the value element in the child param descriptor is not part of the active value of the larger object. If even present, it's used as the default value for the matching part of the parent's value object.
This method is threadsafe because it asserts the DeviceModel's mutex.
References BAD_STATUS, catena::INVALID_ARGUMENT, and value().
The documentation for this class was generated from the following file:
/home/runner/work/Catena/Catena/sdks/cpp/full/include/ParamAccessor.h