Catena_cpp-v0.0.1: catena::common::AuthzInfo Class Reference
catena::common::AuthzInfo Class Reference
Class for handling authorization information.
#include <AuthzInfo.h>
Public Member Functions
AuthzInfo (const ParamDescriptor &pd, const std::string &scope)
Construct a new AuthzInfo object.
virtual ~AuthzInfo ()=default
Destroy the AuthzInfo object.
AuthzInfo subParamInfo (std::string oid) const
Creates a AuthzInfo object for a sub parameter.
bool readAuthz () const
Check if the client has read authorization.
bool writeAuthz () const
Check if the client has write authorization.
const catena::common::IConstraint * getConstraint () const
Detailed Description
Class for handling authorization information.
Constructor & Destructor Documentation
AuthzInfo()
catena::common::AuthzInfo::AuthzInfo (const ParamDescriptor & pd, const std::string & scope) inline
Construct a new AuthzInfo object.
Parameters
pd the ParamDescriptor of the object
scope the scope of the object
Member Function Documentation
readAuthz()
bool catena::common::AuthzInfo::readAuthz () const inline
Check if the client has read authorization.
Returns
true if the client has read authorization
Todo:
implement readAuthz
subParamInfo()
AuthzInfo catena::common::AuthzInfo::subParamInfo (std::string oid) const inline
Creates a AuthzInfo object for a sub parameter.
Parameters
oid the oid of the sub parameter
Returns
AuthzInfo the AuthzInfo object for the sub parameter
References AuthzInfo(), and catena::common::ParamDescriptor::getSubParam().
writeAuthz()
bool catena::common::AuthzInfo::writeAuthz () const inline
Check if the client has write authorization.
Returns
true if the client has write authorization
Todo:
implement writeAuthz
References catena::common::ParamDescriptor::readOnly().
The documentation for this class was generated from the following file:
/home/runner/work/Catena/Catena/sdks/cpp/common/include/AuthzInfo.h