cpp-v0.0.16-15: catena::REST::SocketReader Class Reference
catena::REST::SocketReader Class Reference
A helper class which reads from the client socket using boost and extracts relevant information pertaining to a REST request.
#include <SocketReader.h>
Public Member Functions
SocketReader (IServiceImpl *service)
Constructor for the SocketReader class.
void read (tcp::socket &socket) override
Reads information from the inputted socket and extracts relevant information pertaining to the REST request.
RESTMethod method () const override
Returns the HTTP method of the request.
const std::string & endpoint () const override
Returns the endpoint of the request (parameter, etc.)
uint32_t slot () const override
Returns the slot of the device to make the API call on.
const std::string & fqoid () const override
Returns the fqoid of the asset to make the API call on.
bool hasField (const std::string &key) const override
Returns true if the field exists in the URL, regardless of its value.
const std::string & fields (const std::string &key) const override
Returns the field "key" queried from the URL, or an empty sting if it does not exist.
const std::string & jwsToken () const override
Returns the client's jws token.
const std::string & origin () const override
Returns the origin of the request.
st2138::Device_DetailLevel detailLevel () const override
Returns the detail level to return the response in.
const std::string & jsonBody () const override
Returns the json body of the request, which may be empty.
bool stream () const override
Returns true if the client wants a stream response.
IServiceImpl * service () override
Returns a pointer to the ServiceImpl.
bool authorizationEnabled () const override
Returns true if authorization is enabled for this service.
const std::string & EOPath () const override
Returns the path to the external object.
catena::common::IConnectionQueue & connectionQueue () override
Returns the ConnectionQueue object.
catena::common::ISubscriptionManager & subscriptionManager () override
Returns a reference to the subscription manager.
Public Member Functions inherited from catena::REST::ISocketReader
ISocketReader (const ISocketReader &)=default
ISocketReader & operator= (const ISocketReader &)=default
ISocketReader (ISocketReader &&)=default
ISocketReader & operator= (ISocketReader &&)=default
Detailed Description
A helper class which reads from the client socket using boost and extracts relevant information pertaining to a REST request.
This includes (if applicable):
The HTTP method (GET, POST, etc.)
The endpoint being accessed (param, etc.)
The slot of the device to make the API call on.
The fqoid of an asset to access.
The fields queried from the URL.
The client's jws token.
The origin of the request.
The detail level to return the response in.
The json body of the request.
A flag indicating whether to return the response as a stream.
It also contains links to several objects from the service, such as the subscription manager, the external object path, and the connection queue.
Constructor & Destructor Documentation
SocketReader()
catena::REST::SocketReader::SocketReader (IServiceImpl * service) inline
Constructor for the SocketReader class.
Parameters
service Pointer to the ServiceImpl.
Member Function Documentation
authorizationEnabled()
bool catena::REST::SocketReader::authorizationEnabled () const inline override virtual
Returns true if authorization is enabled for this service.
Implements catena::REST::ISocketReader.
References catena::REST::IServiceImpl::authorizationEnabled().
connectionQueue()
catena::common::IConnectionQueue & catena::REST::SocketReader::connectionQueue () inline override virtual
Returns the ConnectionQueue object.
Implements catena::REST::ISocketReader.
References catena::REST::IServiceImpl::connectionQueue().
detailLevel()
st2138::Device_DetailLevel catena::REST::SocketReader::detailLevel () const inline override virtual
Returns the detail level to return the response in.
Implements catena::REST::ISocketReader.
endpoint()
const std::string & catena::REST::SocketReader::endpoint () const inline override virtual
Returns the endpoint of the request (parameter, etc.)
Implements catena::REST::ISocketReader.
EOPath()
const std::string & catena::REST::SocketReader::EOPath () const inline override virtual
Returns the path to the external object.
Implements catena::REST::ISocketReader.
References catena::REST::IServiceImpl::EOPath().
fields()
const std::string & catena::REST::SocketReader::fields (const std::string & key) const inline override virtual
Returns the field "key" queried from the URL, or an empty sting if it does not exist.
Parameters
key The name of the field to retrieve.
Implements catena::REST::ISocketReader.
fqoid()
const std::string & catena::REST::SocketReader::fqoid () const inline override virtual
Returns the fqoid of the asset to make the API call on.
Implements catena::REST::ISocketReader.
hasField()
bool catena::REST::SocketReader::hasField (const std::string & key) const inline override virtual
Returns true if the field exists in the URL, regardless of its value.
Parameters
key The name of the field to check.
Implements catena::REST::ISocketReader.
jsonBody()
const std::string & catena::REST::SocketReader::jsonBody () const inline override virtual
Returns the json body of the request, which may be empty.
Implements catena::REST::ISocketReader.
jwsToken()
const std::string & catena::REST::SocketReader::jwsToken () const inline override virtual
Returns the client's jws token.
Implements catena::REST::ISocketReader.
method()
RESTMethod catena::REST::SocketReader::method () const inline override virtual
Returns the HTTP method of the request.
Implements catena::REST::ISocketReader.
origin()
const std::string & catena::REST::SocketReader::origin () const inline override virtual
Returns the origin of the request.
Implements catena::REST::ISocketReader.
read()
void catena::REST::SocketReader::read (tcp::socket & socket) override virtual
Reads information from the inputted socket and extracts relevant information pertaining to the REST request.
Parameters
socket The socket to read from.
Implements catena::REST::ISocketReader.
service()
IServiceImpl * catena::REST::SocketReader::service () inline override virtual
Returns a pointer to the ServiceImpl.
Implements catena::REST::ISocketReader.
slot()
uint32_t catena::REST::SocketReader::slot () const inline override virtual
Returns the slot of the device to make the API call on.
Implements catena::REST::ISocketReader.
stream()
bool catena::REST::SocketReader::stream () const inline override virtual
Returns true if the client wants a stream response.
Implements catena::REST::ISocketReader.
subscriptionManager()
catena::common::ISubscriptionManager & catena::REST::SocketReader::subscriptionManager () inline override virtual
Returns a reference to the subscription manager.
Implements catena::REST::ISocketReader.
References catena::REST::IServiceImpl::subscriptionManager().
The documentation for this class was generated from the following file:
/home/runner/work/Catena/Catena/sdks/cpp/connections/REST/include/SocketReader.h