cpp-v0.0.15-896: catena::REST::AssetRequest Class Reference
catena::REST::AssetRequest Class Reference
Controller class for the Asset REST endpoint.
#include <AssetRequest.h>
Public Types
using IDevice = catena::common::IDevice
using SlotMap = catena::common::SlotMap
Public Member Functions
AssetRequest (tcp::socket &socket, ISocketReader &context, SlotMap &dms)
Constructor for the Asset endpoint controller.
void proceed () override
The Asset endpoint's main process.
Static Public Member Functions
static std::string payloadEncodingToString (catena::DataPayload::PayloadEncoding encoding)
Converts the PayloadEncoding enum to a string.
static ICallData * makeOne (tcp::socket &socket, ISocketReader &context, SlotMap &dms)
Creates a new controller object for use with GenericFactory.
Protected Member Functions
void extractPayload (const std::string &filePath)
Extracts the payload from the context and decompresses it if needed.
void writeConsole_ (CallStatus status, bool ok) const override
Writes the current state of the request to the console.
Static Protected Member Functions
static void compress (std::vector< uint8_t > &input, int windowBits)
Compresses the input data using the specified window bits.
static void deflate_compress (std::vector< uint8_t > &input)
Compresses the input data using deflate compression.
static void gzip_compress (std::vector< uint8_t > &input)
Compresses the input data using gzip compression.
static void decompress (std::vector< uint8_t > &input, int windowBits)
Decompresses the input data using the specified window bits.
static void deflate_decompress (std::vector< uint8_t > &input)
Decompresses the input data using deflate compression.
static void gzip_decompress (std::vector< uint8_t > &input)
Decompresses the input data using gzip compression.
static bool get_last_write_time (const std::string &path, std::time_t &out_time)
Gets the last write time of the file.
Protected Attributes
tcp::socket & socket_
The socket to write the response to.
ISocketReader & context_
The ISocketReader object used to read the client's request.
SocketWriter writer_
The SocketWriter object for writing to socket_.
SlotMap & dms_
A map of slots to ptrs to their corresponding device.
int objectId_
ID of the object.
Static Protected Attributes
static int objectCounter_
The total # of asset endpoint controller objects.
Detailed Description
Controller class for the Asset REST endpoint.
This controller supports four methods:
GET: Writes the requested external object to the client. Supports both stream and unary responses.
POST: Uploads an external object to the server.
PUT: Overwrites an existing external object on the server.
DELETE: Deletes an external object from the server.
Constructor & Destructor Documentation
AssetRequest()
catena::REST::AssetRequest::AssetRequest (tcp::socket & socket, ISocketReader & context, SlotMap & dms)
Constructor for the Asset endpoint controller.
Parameters
socket The socket to write the response to.
context The ISocketReader object used to read the client's request.
dms A map of slots to ptrs to their corresponding device.
Member Function Documentation
compress()
static void catena::REST::AssetRequest::compress (std::vector< uint8_t > & input, int windowBits) static protected
Compresses the input data using the specified window bits.
Parameters
input The input data to compress.
windowBits The window bits to use for compression.
decompress()
static void catena::REST::AssetRequest::decompress (std::vector< uint8_t > & input, int windowBits) static protected
Decompresses the input data using the specified window bits.
Parameters
input The input data to decompress.
windowBits The window bits to use for decompression.
deflate_compress()
static void catena::REST::AssetRequest::deflate_compress (std::vector< uint8_t > & input) static protected
Compresses the input data using deflate compression.
Parameters
input The input data to compress.
deflate_decompress()
static void catena::REST::AssetRequest::deflate_decompress (std::vector< uint8_t > & input) static protected
Decompresses the input data using deflate compression.
Parameters
input The input data to decompress.
get_last_write_time()
static bool catena::REST::AssetRequest::get_last_write_time (const std::string & path, std::time_t & out_time) static protected
Gets the last write time of the file.
Parameters
path The path to the file.
out_time The output time.
Returns
True if the last write time is valid, false otherwise.
gzip_compress()
static void catena::REST::AssetRequest::gzip_compress (std::vector< uint8_t > & input) static protected
Compresses the input data using gzip compression.
Parameters
input The input data to compress.
gzip_decompress()
static void catena::REST::AssetRequest::gzip_decompress (std::vector< uint8_t > & input) static protected
Decompresses the input data using gzip compression.
Parameters
input The input data to decompress.
makeOne()
static ICallData * catena::REST::AssetRequest::makeOne (tcp::socket & socket, ISocketReader & context, SlotMap & dms) inline static
Creates a new controller object for use with GenericFactory.
Parameters
socket The socket to write the response to.
context The ISocketReader object used to read the client's request.
dms A map of slots to ptrs to their corresponding device.
payloadEncodingToString()
static std::string catena::REST::AssetRequest::payloadEncodingToString (catena::DataPayload::PayloadEncoding encoding) static
Converts the PayloadEncoding enum to a string.
Parameters
encoding The PayloadEncoding enum value to convert.
Returns
The string representation of the PayloadEncoding.
proceed()
void catena::REST::AssetRequest::proceed () override virtual
The Asset endpoint's main process.
Implements catena::REST::ICallData.
writeConsole_()
void catena::REST::AssetRequest::writeConsole_ (CallStatus status, bool ok) const inline override protected virtual
Writes the current state of the request to the console.
Parameters
status The current state of the request (kCreate, kFinish, etc.)
ok The status of the request (open or closed).
Implements catena::REST::ICallData.
References context_, catena::patterns::EnumDecorator< E >::getForwardMap(), catena::REST::ISocketReader::method(), objectId_, and catena::common::timeNow().
The documentation for this class was generated from the following file:
/home/runner/work/Catena/Catena/sdks/cpp/connections/REST/include/controllers/AssetRequest.h