Catena_cpp-v0.0.1: catena::lite::ParamWithValue< T > Class Template Reference
catena::lite::ParamWithValue< T > Class Template Reference
ParamWithValue is a class that implements the IParam interface for each param type in the device model.
#include <ParamWithValue.h>
Public Member Functions
ParamWithValue (T &value, ParamDescriptor &descriptor, Device &dev, bool isCommand)
Construct a new ParamWithValue object and add it to the device.
ParamWithValue (T &value, ParamDescriptor &descriptor)
Construct a new ParamWithValue object without adding it to device.
template<typename FieldType = T, typename ParentType >
ParamWithValue (const FieldInfo< FieldType, ParentType > &field, ParentType &parentValue, ParamDescriptor &parentDescriptor)
Construct a new ParamWithValue object using FieldInfo.
ParamWithValue (const ParamWithValue &)=delete
ParamWithValue can not be copied directly.
ParamWithValue & operator= (const ParamWithValue &)=delete
ParamWithValue can not be copied directly.
ParamWithValue (ParamWithValue &&)=default
ParamWithValue has move semantics.
ParamWithValue & operator= (ParamWithValue &&)=default
ParamWithValue has move semantics.
virtual ~ParamWithValue ()=default
default destructor
std::unique_ptr< IParam > copy () const override
creates a shallow copy the parameter
catena::exception_with_status toProto (catena::Value &value, std::string &clientScope) const override
serialize the parameter value to protobuf if authorized
catena::exception_with_status toProto (catena::Param &param, std::string &clientScope) const override
serialize the parameter descriptor to protobuf include both the descriptor and the value
catena::exception_with_status fromProto (const catena::Value &value, std::string &clientScope) override
deserialize the parameter value from protobuf if authorized
IParam::ParamType type () const override
get the parameters protobuf value type
const std::string & getOid () const override
get the parameter oid
void setOid (const std::string &oid) override
set the parameter oid
bool readOnly () const override
return the params read only flag
void readOnly (bool flag) override
set the params read only flag
T & get ()
get the value of the parameter
const T & get () const
get the value of the parameter (const version)
std::unique_ptr< IParam > getParam (Path &oid, catena::exception_with_status &status) override
get a child parameter by name
void defineCommand (std::function< catena::CommandResponse(catena::Value)> command) override
define a command for the parameter
catena::CommandResponse executeCommand (const catena::Value &value) const override
execute the command for the parameter
void addParam (const std::string &oid, ParamDescriptor *param)
add a child parameter
const catena::common::IConstraint * getConstraint () const override
get a constraint by oid
const std::string getScope () const override
get the parameter scope
Public Member Functions inherited from catena::common::IParam
IParam & operator= (IParam &&)=default
IParam has move semantics.
IParam (IParam &&)=default
IParam (const IParam &)=delete
IParam does not have copy semantics.
IParam & operator= (const IParam &)=delete
Additional Inherited Members
Public Types inherited from catena::common::IParam
using ParamType = catena::patterns::EnumDecorator< catena::ParamType >
ParamType is an enum class that defines the types of parameters.
using OidAliases = std::vector< std::string >
OidAliases is a vector of strings.
using Path = catena::common::Path
Detailed Description
template<typename T>
class catena::lite::ParamWithValue< T >
ParamWithValue is a class that implements the IParam interface for each param type in the device model.
Member Function Documentation
copy()
template<typename T > std::unique_ptr<IParam> catena::lite::ParamWithValue< T >::copy () const inline override virtual
creates a shallow copy the parameter
Needed to copy IParam objects
ParamWithValue objects only contain two references, so they are cheap to copy
Implements catena::common::IParam.
fromProto()
template<typename T > catena::exception_with_status catena::lite::ParamWithValue< T >::fromProto (const catena::Value & value, std::string & clientScope) inline override virtual
deserialize the parameter value from protobuf if authorized
Parameters
value the protobuf value to deserialize from
clientScope the client scope
Implements catena::common::IParam.
References catena::INVALID_ARGUMENT, catena::OK, catena::PERMISSION_DENIED, catena::lite::AuthzInfo::readAuthz(), and catena::lite::AuthzInfo::writeAuthz().
getParam()
template<typename T > std::unique_ptr<IParam> catena::lite::ParamWithValue< T >::getParam (Path & oid, catena::exception_with_status & status) inline override virtual
get a child parameter by name
Parameters
oid the path to the child parameter
Returns
a unique pointer to the child parameter, or nullptr if it does not exist
Implements catena::common::IParam.
toProto() [1/2]
template<typename T > catena::exception_with_status catena::lite::ParamWithValue< T >::toProto (catena::Param & param, std::string & clientScope) const inline override virtual
serialize the parameter descriptor to protobuf include both the descriptor and the value
Parameters
param the protobuf value to serialize to
clientScope the client scope
Implements catena::common::IParam.
References catena::INVALID_ARGUMENT, catena::OK, catena::lite::AuthzInfo::readAuthz(), and catena::lite::ParamDescriptor::toProto().
toProto() [2/2]
template<typename T > catena::exception_with_status catena::lite::ParamWithValue< T >::toProto (catena::Value & value, std::string & clientScope) const inline override virtual
serialize the parameter value to protobuf if authorized
Parameters
value the protobuf value to serialize to
clientScope the client scope
Implements catena::common::IParam.
References catena::INVALID_ARGUMENT, catena::OK, and catena::lite::AuthzInfo::readAuthz().
The documentation for this class was generated from the following file:
/home/runner/work/Catena/Catena/sdks/cpp/lite/include/ParamWithValue.h