cpp-v0.0.10-5: catena::patterns::EnumDecorator< E > Class Template Reference
catena::patterns::EnumDecorator< E > Class Template Reference
Enhances default C++ enums by adding functionality for converting between enum values, strings and integral types.
#include <EnumDecorator.h>
Public Types
using etype = E
using utype = typename std::underlying_type< E >::type
using FwdMap = std::unordered_map< E, std::string >
using RevMap = std::unordered_map< std::string, E >
Public Member Functions
EnumDecorator ()
Default constructor. Value of object will be 0.
EnumDecorator (E value)
Construct from an enum value.
EnumDecorator (const std::string &str)
Construct from a string.
const RevMap & getReverseMap ()
provide the reverse map of strings to enum values
const FwdMap & getForwardMap () const
provide the forward map of enum values to strings
EnumDecorator (utype value)
construct from a value of the enum's underlying integral type.
EnumDecorator (const EnumDecorator &other)=default
EnumDecorators have copy semantics.
EnumDecorator & operator= (const EnumDecorator &other)=default
EnumDecorators have copy semantics.
EnumDecorator (EnumDecorator &&other)=default
EnumDecorators have move semantics.
EnumDecorator & operator= (EnumDecorator &&other)=default
EnumDecorators have move semantics.
E value () const
value accessor.
E operator() () const
value accessor, alternative syntax.
operator utype () const
cast to the enum's underlying integral type
operator std::string () const
cast to a string
const std::string & toString () const
get the string representation of the enum value
bool operator== (const EnumDecorator &other) const
equality operator
bool operator!= (const EnumDecorator &other) const
inequality operator
Detailed Description
template<typename E>
class catena::patterns::EnumDecorator< E >
Enhances default C++ enums by adding functionality for converting between enum values, strings and integral types.
Examples
enum_decorator.cpp.
Constructor & Destructor Documentation
EnumDecorator() [1/3]
template<typename E > catena::patterns::EnumDecorator< E >::EnumDecorator (E value) inline
Construct from an enum value.
Parameters
value the enum value
EnumDecorator() [2/3]
template<typename E > catena::patterns::EnumDecorator< E >::EnumDecorator (const std::string & str) inline
Construct from a string.
Beware, the default value is set to 0, which may not be a valid enum value.
Parameters
str the string representation of the enum value
References catena::patterns::EnumDecorator< E >::getReverseMap().
EnumDecorator() [3/3]
template<typename E > catena::patterns::EnumDecorator< E >::EnumDecorator (utype value) inline
construct from a value of the enum's underlying integral type.
Sets the value of the object to 0 if the integral value is not valid.
Parameters
value the integral value
Member Function Documentation
getForwardMap()
template<typename E > const FwdMap & catena::patterns::EnumDecorator< E >::getForwardMap () const inline
provide the forward map of enum values to strings
Returns
the forward map
getReverseMap()
template<typename E > const RevMap & catena::patterns::EnumDecorator< E >::getReverseMap () inline
provide the reverse map of strings to enum values
lazy implementation
Returns
the reverse map
operator utype()
template<typename E > catena::patterns::EnumDecorator< E >::operator utype () const inline
cast to the enum's underlying integral type
Returns
the current enum value or the default value if the object is not valid.
References catena::patterns::EnumDecorator< E >::value().
operator!=()
template<typename E > bool catena::patterns::EnumDecorator< E >::operator!= (const EnumDecorator< E > & other) const inline
inequality operator
Returns
true if the enum values are different, false if they are equal, and false if either object is not valid.
operator()()
template<typename E > E catena::patterns::EnumDecorator< E >::operator() () const inline
value accessor, alternative syntax.
Returns
the current enum value.
operator==()
template<typename E > bool catena::patterns::EnumDecorator< E >::operator== (const EnumDecorator< E > & other) const inline
equality operator
Returns
true if the enum values are equal, false if they are different, and false if either object is not valid.
References catena::patterns::EnumDecorator< E >::value().
value()
template<typename E > E catena::patterns::EnumDecorator< E >::value () const inline
value accessor.
Returns
the current enum value.
The documentation for this class was generated from the following files:
/home/runner/work/Catena/Catena/sdks/cpp/common/include/patterns/EnumDecorator.h
/home/runner/work/Catena/Catena/sdks/cpp/common/include/Enums.h
/home/runner/work/Catena/Catena/sdks/cpp/common/include/IParam.h
/home/runner/work/Catena/Catena/sdks/cpp/connections/REST/include/SocketReader.h