cpp-v0.0.12-2: catena::common::Connect Class Reference
catena::common::Connect Class Reference
Pure virtual class for Connect RPCs. Contains functions for updating the response message with parameter values. Can only be inherited.
#include <Connect.h>
Public Member Functions
virtual ~Connect ()=default
Descructor.
uint32_t priority () const override
Returns the connection's priority.
uint32_t objectId () const override
Returns the object Id.
bool operator< (const IConnect &otherConnection) const override
Returns true if this has less prioirty than otherConnection.
void shutdown () override
Forcefully shuts down the connection.
Public Member Functions inherited from catena::common::IConnect
virtual ~IConnect ()=default
Descructor.
Protected Member Functions
Connect ()=delete
Constructor.
Connect (SlotMap &dms, ISubscriptionManager &subscriptionManager)
Constructor for the Connect class.
Connect (const Connect &)=delete
Connect does not have copy semantics.
Connect & operator= (const Connect &)=delete
Connect (Connect &&)=delete
Connect does not have move semantics.
Connect & operator= (Connect &&)=delete
void updateResponse_ (const std::string &oid, const IParam *p, uint32_t slot) override
Updates the response message with parameter values and handles authorization checks.
void updateResponse_ (const ILanguagePack *l, uint32_t slot) override
Updates the response message with an ILanguagePack and handles authorization checks.
void initAuthz_ (const std::string &jwsToken, bool authz=false) override
Sets up the authorizer object with the jwsToken and calculates connection priority.
Protected Member Functions inherited from catena::common::IConnect
virtual bool isCancelled ()=0
Returns true if the call has been canceled.
Protected Attributes
uint32_t priority_ = 0
The priority of the connection.
std::shared_ptr< catena::common::Authorizer > sharedAuthz_
Shared ptr to maintain ownership of authorizer.
catena::common::Authorizer * authz_
The authorizer object containing client's scopes.
SlotMap & dms_
A map of slots to ptrs to their corresponding device.
bool hasUpdate_ = false
Bool indicating whether the child has an update to write.
std::condition_variable cv_
A condition variable used to wait for an update.
catena::PushUpdates res_
Server response (updates).
std::string language_
The language of the response.
catena::Device_DetailLevel detailLevel_
The detail level of the response.
ISubscriptionManager & subscriptionManager_
The subscription manager.
std::string userAgent_
The user agent of the client.
bool forceConnection_
Flag to force a connection.
bool shutdown_ = false
Flag indicating whether to shut down the connection.
uint32_t objectId_ = 0
ID of the Connect object.
Detailed Description
Pure virtual class for Connect RPCs. Contains functions for updating the response message with parameter values. Can only be inherited.
Todo:
Implement subscriptionManager.
Constructor & Destructor Documentation
~Connect()
virtual catena::common::Connect::~Connect () virtual default
Descructor.
Reimplemented in catena::REST::Connect.
Connect()
catena::common::Connect::Connect (SlotMap & dms, ISubscriptionManager & subscriptionManager) inline protected
Constructor for the Connect class.
Parameters
dms A map of slots to ptrs to their corresponding device.
authz true if authorization is enabled, false otherwise.
jwsToken The client's JWS token.
subscriptionManager The subscription manager.
Member Function Documentation
initAuthz_()
void catena::common::Connect::initAuthz_ (const std::string & jwsToken, bool authz = false) inline override protected virtual
Sets up the authorizer object with the jwsToken and calculates connection priority.
priority_ = scope * 2 + write + (adm:w && forceConnection)
Parameters
jwsToken The jwsToken to use for authorization.
authz true if authorization is enabled, false otherwise.
Implements catena::common::IConnect.
References authz_, forceConnection_, catena::common::Authorizer::kAuthzDisabled, catena::PERMISSION_DENIED, priority_, catena::common::Authorizer::readAuthz(), sharedAuthz_, and catena::common::Authorizer::writeAuthz().
objectId()
uint32_t catena::common::Connect::objectId () const inline override virtual
Returns the object Id.
Implements catena::common::IConnect.
References objectId_.
operator<()
bool catena::common::Connect::operator< (const IConnect & otherConnection) const inline override virtual
Returns true if this has less prioirty than otherConnection.
Implements catena::common::IConnect.
References catena::common::IConnect::objectId(), objectId_, catena::common::IConnect::priority(), and priority_.
priority()
uint32_t catena::common::Connect::priority () const inline override virtual
Returns the connection's priority.
Implements catena::common::IConnect.
References priority_.
shutdown()
void catena::common::Connect::shutdown () inline override virtual
Forcefully shuts down the connection.
Implements catena::common::IConnect.
References cv_, hasUpdate_, and shutdown_.
updateResponse_() [1/2]
void catena::common::Connect::updateResponse_ (const ILanguagePack * l, uint32_t slot) inline override protected virtual
Updates the response message with an ILanguagePack and handles authorization checks.
Parameters
l The added ILanguagePack emitted by device.
Implements catena::common::IConnect.
References authz_, cv_, hasUpdate_, catena::common::IConnect::isCancelled(), catena::common::Authorizer::readAuthz(), res_, and catena::common::ILanguagePack::toProto().
updateResponse_() [2/2]
void catena::common::Connect::updateResponse_ (const std::string & oid, const IParam * p, uint32_t slot) inline override protected virtual
Updates the response message with parameter values and handles authorization checks.
Parameters
oid - The OID of the value to update
p - The parameter to update
Implements catena::common::IConnect.
References authz_, cv_, detailLevel_, dms_, catena::common::IParam::getDescriptor(), hasUpdate_, catena::common::IConnect::isCancelled(), catena::common::IParamDescriptor::isCommand(), catena::common::ISubscriptionManager::isSubscribed(), catena::common::IParamDescriptor::minimalSet(), catena::OK, catena::common::Authorizer::readAuthz(), res_, subscriptionManager_, and catena::common::IParam::toProto().
Member Data Documentation
forceConnection_
bool catena::common::Connect::forceConnection_ protected
Flag to force a connection.
Only applicable if client has admin:w scope.
priority_
uint32_t catena::common::Connect::priority_ = 0 protected
The priority of the connection.
priority_ = scope * 2 + write + (adm:w && forceConnection)
userAgent_
std::string catena::common::Connect::userAgent_ protected
The user agent of the client.
No idea what this is used for and if its even needed here.
The documentation for this class was generated from the following file:
/home/runner/work/Catena/Catena/sdks/cpp/common/include/rpc/Connect.h