Catena_cpp-v0.0.1: /home/runner/work/Catena/Catena/sdks/cpp/common/include/StructInfo.h File Reference
StructInfo.h File Reference
Structured data serialization and deserialization to protobuf.
#include <meta/Typelist.h>
#include <meta/IsVector.h>
#include <meta/Variant.h>
#include <AuthzInfo.h>
#include <interface/param.pb.h>
#include <string>
#include <cstddef>
#include <vector>
#include <utility>
Classes
struct catena::common::EmptyValue
EmptyValue is used for commands that do not have a value.
struct catena::common::StructInfo< T >
StructInfo is specialized at compile time to provide type information about a struct.
struct catena::common::FieldInfo< FieldType, StructType >
FieldInfo pairs the name of a field with the type information needed to access it.
Namespaces
catena
Functions
template<typename T >
void catena::common::toProto (catena::Value &dst, const T *src, const AuthzInfo &auth)
template<typename T >
void catena::common::fromProto (const catena::Value &src, T *dst, const AuthzInfo &auth)
template<std::size_t size>
std::size_t catena::common::_findTypeIndex (const std::string &typeName, const std::array< const char *, size > &typeNames)
helper function to find the index of a type in a list of type names
template<meta::IsVariant V, std::size_t Index>
void catena::common::_changeType (V &variant, const std::size_t newTypeIndex)
_changeType is a helper function to change the type held by a variant
Variables
EmptyValue catena::common::emptyValue
template<typename T >
concept catena::common::CatenaStruct
CatenaStruct concept checks that a type is a struct generated by the Catena code generator.
template<typename T >
concept catena::common::CatenaStructArray = meta::IsVector<T> && CatenaStruct<typename T::value_type>
CatenaStructArray concept checks that a type is a vector of structs that meet the CatenaStruct concept.
template<typename T >
concept catena::common::IsVariantArray = meta::IsVector<T> && meta::IsVariant<typename T::value_type>
IsVariantArray concept checks that a type is a vector of variants.
template<meta::IsVariant U>
constexpr std::array< const char *, 0 > catena::common::alternativeNames {}
AltenativeNames is specialized in the generated code to provide the names of the alternatives in a variant.
Detailed Description
Structured data serialization and deserialization to protobuf.
Author
John R. Naylor
John Danen
Date
2024-07-07
Function Documentation
_changeType()
template<meta::IsVariant V, std::size_t Index> void catena::common::_changeType (V & variant, const std::size_t newTypeIndex)
_changeType is a helper function to change the type held by a variant
Template Parameters
V the type of the variant
Index the index of the current type being checked
Parameters
variant the variant to change the type of
newTypeIndex the index of the new type to change to
This function is used by fromProto to change the type of a variant to the type specified in the src protobuf message. It is a recursive function that checks each type in the variant until it finds the type that matches the newTypeIndex. If the type is not found, the variant is left unchanged. If the type is found, the variant is changed to the default value of the new type.
References catena::common::_changeType().
_findTypeIndex()
template<std::size_t size> std::size_t catena::common::_findTypeIndex (const std::string & typeName, const std::array< const char *, size > & typeNames) inline
helper function to find the index of a type in a list of type names
Parameters
typeName the name of the type to find
typeNames the list of type names to search
Returns
the index of the type in the list or the size of the list if the type is not found
References catena::common::_findTypeIndex().
fromProto()
template<typename T > void catena::common::fromProto (const catena::Value & src, T * dst, const AuthzInfo & auth)
Free standing method to deserialize a value from protobuf
generic template declaration
Template Parameters
T the type of the value
fromProto specialization to deserialize an entire array of structured data from protobuf
enabled if T is a vector of struct with isCatenaStruct defined
Template Parameters
T the type of the value
fromProto specialization to deserialize a single struct value from protobuf.
recursively calls fromProto for each field in the struct
enabled if T has isCatenaStruct defined
Template Parameters
T the type of the value
&(dst->*(field.memberPtr)) will pass the address of the corresponding value field in dst to the fromProto function.
the correct specialization of fromProto will be called based on the type of the field memberPtr.
&(dst->*(field.memberPtr)) will pass the address of the corresponding value field in dst to the fromProto function.
the correct specialization of fromProto will be called based on the type of the field memberPtr.
References catena::common::fromProto().
toProto()
template<typename T > void catena::common::toProto (catena::Value & dst, const T * src, const AuthzInfo & auth)
Free standing method to serialize a value to protobuf
generic template declaration
Template Parameters
T the type of the value
toProto specialization to serialize an entire array of structured data to protobuf
enabled if T is a vector of CatenaStruct
Template Parameters
T the type of the value
toProto specialization to serialize a single struct value to protobuf.
recursively calls toProto for each field in the struct
enabled if T has matches the CatenaStruct concept
Template Parameters
T the type of the value
&(src->*(field.memberPtr)) will pass the address of the corresponding field in src to the toProto function.
the correct specializtion of toProto will be called based on the type of the field memberPtr.
&(src->*(field.memberPtr)) will pass the address of the corresponding field in src to the toProto function.
the correct specializtion of toProto will be called based on the type of the field memberPtr.
References catena::common::toProto().
Variable Documentation
alternativeNames
template<meta::IsVariant U> constexpr std::array<const char*, 0> catena::common::alternativeNames {} constexpr
AltenativeNames is specialized in the generated code to provide the names of the alternatives in a variant.
Template Parameters
U the type of the variant
The Catena code generator will specialize this template for every variant in the json device model that does not have a template_oid. The specialization will contain a vector of strings that contains the names of each alternative in the variant.
CatenaStruct
template<typename T > concept catena::common::CatenaStruct
Initial value:
= requires {
    typename T::isCatenaStruct;
}
CatenaStruct concept checks that a type is a struct generated by the Catena code generator.
Template Parameters
T the type to check
This concept is used to specialize template functions for any struct type generated by the Catena code generator. The Catena code generator will add a using declaration to the struct that defines isCatenaStruct as a type. This concept checks for the presence of that type.
all types that meet this constraint will also provide a specialization of StructInfo.
CatenaStructArray
template<typename T > concept catena::common::CatenaStructArray = meta::IsVector<T> && CatenaStruct<typename T::value_type>
CatenaStructArray concept checks that a type is a vector of structs that meet the CatenaStruct concept.
Template Parameters
T the type to check
This concept is used to specialize template functions for any vector of struct type generated by the Catena code generator.
IsVariantArray
template<typename T > concept catena::common::IsVariantArray = meta::IsVector<T> && meta::IsVariant<typename T::value_type>
IsVariantArray concept checks that a type is a vector of variants.
Template Parameters
T the type to check
This concept is used to specialize template functions for any vector of variant type generated by the Catena code generator.