name: Coverage

on:
  push:
    branches:
      - test

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Dev Container Image
        run: |
          docker buildx build \
           -f .devcontainer/devcontainer.dockerfile \
           --build-arg CONNECTIONS='gRPC;REST' \
           --build-arg CMAKE_BUILD_TYPE='Debug' \
           -t catena-devcontainer .

          echo "-----------------0"
          
          docker run --rm -v ${{ github.workspace }}:/workspace catena-devcontainer \
            /bin/bash -c "cp -r coverage /workspace/coverage"

          echo "---------------1"
          ls -la

          echo "---------------2"
          ls -la ${{ github.workspace }}

          echo "---------------3"
          ls -la ${{ github.workspace }}/coverage
          
        
      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-xml
          path: coverage/coverage.xml

