name: Coverage

on:
  push:
    branches:
      - main
      - develop

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Dev Container Image
        run: |
          docker build -f .devcontainer/devcontainer.dockerfile -t catena-devcontainer .
          docker run --rm --name catena-container \
            -v ${{ github.workspace }}:/home/catenauser/Catena \
            -w /home/catenauser/Catena \
            catena-devcontainer \
            /bin/bash -c './scripts/run_coverage.sh'

          echo "---------------1"
          ls -la
          echo "---------------2"
          ls -la ${{ github.workspace }}
          echo "---------------3"
          ls -la ${{ github.workspace }}/coverage
          
        
      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-xml
          path: coverage/coverage.xml

