name: C++ Unit Tests

on:
  push:
    branches:
      - test_trivy_pipeline

jobs:
  configure:
    name: Configure
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rossvideo/catena-toolchain-cpp:latest

    env:
      CMAKE_BUILD_TYPE: Debug
      CONNECTIONS: gRPC;REST
      BUILD_TARGET: build/cpp

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure
        run: |
          mkdir -p ~/Catena/${BUILD_TARGET}
          cmake -G Ninja \
            -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} \
            -DCONNECTIONS=${CONNECTIONS} \
            -DCMAKE_CXX_FLAGS="--coverage" \
            -DCMAKE_C_FLAGS="--coverage" \
            -DCMAKE_EXE_LINKER_FLAGS="--coverage" \
            -DCMAKE_INSTALL_PREFIX=/usr/local/.local \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE \
            -DGLOG_LOGGING_DIR=${HOME}/Catena/logs \
            -B ~/Catena/${BUILD_TARGET} \
            -S ./sdks/cpp

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cpp-build-artifacts
          path: ~/Catena/build/cpp/
          retention-days: 1

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rossvideo/catena-toolchain-cpp:latest
    needs: configure

    env:
      CMAKE_BUILD_TYPE: Debug
      CONNECTIONS: gRPC;REST
      BUILD_TARGET: build/cpp

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: cpp-build-artifacts
          path: ~/Catena/build/cpp/
      
      - name: build
        run: |
          cd ~/Catena/${BUILD_TARGET}
          ninja -C ~/Catena/${BUILD_TARGET} -j$(nproc)

      - name: Run Tests
        run: |
          ctest --test-dir ~/Catena/${BUILD_TARGET} -V --rerun-failed > test_results.log
          # check if file contains "100% tests passed"
          if grep -q "100% tests passed" test_results.log; then
            echo "All tests passed!"
          else
            echo "Some tests failed."
            exit 1
          fi

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: cpp-unit-tests-results
          path: test_results.log
          retention-days: 7
        if: failure()

  coverage:
    name: Generate Coverage Report
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rossvideo/catena-toolchain-cpp:latest
    needs: configure

    env:
      CMAKE_BUILD_TYPE: Debug
      CONNECTIONS: gRPC;REST
      BUILD_TARGET: build/cpp

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: cpp-build-artifacts
          path: ~/Catena/build/cpp/
      
      - name: build
        run: |
          cd ~/Catena/${BUILD_TARGET}
          ninja -C ~/Catena/${BUILD_TARGET} -j$(nproc)

      - name: Run Tests for Coverage
        run: |
          ctest --test-dir ~/Catena/${BUILD_TARGET} -V

      - name: Generate Coverage Report
        run: |
          gcovr --root ~/Catena --filter sdks/cpp -e '(.+/)?build/' -e '(.+/)?tests/' -e '(.+/)?examples/' --lcov=coverage.info --cobertura=coverage.xml

      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml

  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rossvideo/catena-toolchain-cpp:latest
    needs: configure

    env:
      CMAKE_BUILD_TYPE: Debug
      CONNECTIONS: gRPC;REST
      BUILD_TARGET: build/cpp

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: cpp-build-artifacts
          path: ~/Catena/build/cpp/
      
      - name: build
        run: |
          cd ~/Catena/${BUILD_TARGET}
          ninja -C ~/Catena/${BUILD_TARGET} -j$(nproc)

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: cpp

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3