# This file is used to generate the Doxygen documentation and deploy it to GitHub Pages.
name: "Doxygen GitHub Pages Deploy Action"


on:
    push:
      branches: [ "develop", "main", "doxygen" ]
    pull_request:
      branches: [ "develop", "main" ]
    schedule:
      - cron: '25 16 * * 2'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Install Toolchain
              run: |
                  sudo apt-get update -y
                  sudo apt-get install -y -qq doxygen
                  sudo apt-get install -y -qq graphviz
                  sudo apt-get install ninja-build
                  sudo add-apt-repository -y ppa:linuxuprising/pandoc
                  sudo apt-get update -y
                  sudo apt-get install -y -qq pandoc

            - name: Make a build directory and run CMake
              run: |
                  mkdir -p sdks/cpp/build
                  cd sdks/cpp/build
                  cmake -DONLY_DOCS=ON -G Ninja ..
                  ninja doxygen
                  tar -zcvf github-pages doxygen/html

            # Render Markdown files from /docs to HTML
            - name: Convert Markdown to HTML
              run: |
                  mkdir -p sdks/cpp/build/markdown
                  for file in docs/*.md; do
                      filename=$(basename "$file" .md)
                      pandoc "$file" -o "sdks/cpp/build/markdown/$filename.html"
                  done

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./sdks/cpp/build
