# This file is used to generate the Doxygen documentation and deploy it to GitHub Pages.
name: "Doxygen GitHub Pages Deploy Action"


on:
    push:
      branches: [ "develop", "main", "doxygen" ]
    pull_request:
      branches: [ "develop", "main" ]
    schedule:
      - cron: '25 16 * * 2'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Install Toolchain
              run: |
                  sudo apt-get update -y
                  sudo apt-get install -y -qq wget doxygen graphviz ninja-build
                  wget https://github.com/jgm/pandoc/releases/download/3.1.2/pandoc-3.1.2-linux-amd64.tar.gz
                  tar -xvf pandoc-3.1.2-linux-amd64.tar.gz
                  sudo mv pandoc-3.1.2/bin/pandoc /usr/local/bin/

            - name: Make a build directory, run CMake and Ninja to build Doxygen files
              run: |
                  mkdir -p sdks/cpp/build
                  cd sdks/cpp/build
                  cmake -DONLY_DOCS=ON -G Ninja ..
                  ninja doxygen

            # Copy Doxygen files to a "doxygen" subdirectory for GitHub Pages
            - name: Prepare Doxygen files for GitHub Pages
              run: |
                  mkdir -p sdks/cpp/build/github-pages/doxygen
                  cp -r sdks/cpp/build/doxygen/html/* sdks/cpp/build/github-pages/doxygen

            # Convert Markdown files to HTML and store in a "docs" subdirectory
            - name: Convert Markdown to HTML
              run: |
                  mkdir -p sdks/cpp/build/github-pages/docs
                  for file in docs/*.md; do
                      filename=$(basename "$file" .md)
                      pandoc "$file" -o "sdks/cpp/build/github-pages/docs/$filename.html"
                  done

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./sdks/cpp/build/github-pages