name: trivy-nightly
on:
  push:
    branches:
      - test_trivy_pipeline

jobs:
  Trivy:
    name: Trivy vulnerability scanner
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
          skip-dirs: '.git,build,coverage,docs,sdks/java,unittests'
          skip-files: 'pom.xml'

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
          category: 'Trivy Scan Results'
  
  Coverage_report:
    name: Get unit tests coverage report
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run unit tests
        run: |
          ./scripts/run_coverage.sh -c --html -v
        
      - name: Upload coverage report
        uses: github/codeql-action/upload-coverage@v3
        with:
          coverage_file: 'coverage/coverage.xml'
          format: 'cobertura'
          category: 'Unit Tests Coverage'
      