name: trivy-nightly
on:
  push:
    branches:
      - test_trivy_pipeline

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'

      - name: echo results
        run: |
          echo "Trivy scan completed. Results are in trivy-results.sarif"
          if [ -f trivy-results.sarif ]; then
            echo "------------------- Results file content:"
            echo "$(cat trivy-results.sarif)"
            echo "------------------- End of results file content."
          else
            echo "------------------- Results file does not exist."
            exit 1
          fi
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
          category: 'Trivy Scan Results'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 